### ISSUE TITLE
nvidia-smi overview

### ISSUE THREAD

**Issue by xgdgsc** [netdata/netdata#10228]
##### Feature idea summary

Currently there' s only seperate cards metrics, less useful than the plain nvidia-smi output for me.

##### Expected behavior

Provide a concise overview like nvidia-smi output.

**Comment by ilyam8** [comment]
Hi @xgdgsc 

Are you referring to this output?

```
[ilyam@pc ~]$ nvidia-smi
Wed Nov 11 11:04:05 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.113      Driver Version: 418.113      CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960     Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   30C    P8    10W / 130W |     43MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       533      G   /usr/lib/Xorg                                 16MiB |
|    0      1105      G   /usr/bin/kwin_x11                              8MiB |
|    0      1132      G   /usr/bin/plasmashell                          15MiB |
+-----------------------------------------------------------------------------+
```

---

That is indeed more compact view, unfortunately we are limited in representation options atm 🤷‍♂️ 

What we can do is to add some metrics (ex.: fan, temp, power) as gauges like we have in `System Overview`

<img width="1175" alt="Screenshot 2020-11-11 at 11 16 09" src="https://user-images.githubusercontent.com/22274335/98786556-4ecb7c80-240f-11eb-9760-cc018116b15e.png">


What do you think?

**Comment by xgdgsc** [comment]
Yes. I have 4 cards that needs overview. Something like the system overview would be great.

**Comment by ilyam8** [comment]
What metrics would you like to have in the overview?

**Comment by xgdgsc** [comment]
gpu memory and temperature would suffice for me

**Comment by xgdgsc** [comment]
Here the nvidia-smi tab disappears after running for a day or two. Any ideas?

**Comment by ilyam8** [comment]
Hi. I would check error.log

```cmd
cd /path/to/netdata/log/dir
grep nvidia_smi error.log
```

and try debug mode (as `netdata` user)

```cmd
cd /path/to/netdata/plugins.d
./python.d.plugin debug nolock nvidia_smi
```

**Comment by xgdgsc** [comment]
[nvnetdata.log](https://github.com/netdata/netdata/files/5621588/nvnetdata.log)

log like this

**Comment by ilyam8** [comment]
Let's see debug output

**Comment by xgdgsc** [comment]
```
BEGIN nvidia_smi.gpu2_user_mem 7999310
SET 'gpu2_user_mem_ychen' = 2167
SET 'gpu2_user_mem_xzhang' = 1715
END

BEGIN nvidia_smi.gpu2_mem_utilization 7999310
SET 'gpu2_memory_util' = 58
END

BEGIN nvidia_smi.gpu0_user_num 7999310
SET 'gpu0_user_num' = 2
END

BEGIN nvidia_smi.gpu1_pci_bandwidth 7999310
SET 'gpu1_rx_util' = 5842000
SET 'gpu1_tx_util' = 822000
END

BEGIN nvidia_smi.gpu1_user_num 7999310
SET 'gpu1_user_num' = 2
END

BEGIN nvidia_smi.gpu2_gpu_utilization 7999310
SET 'gpu2_gpu_util' = 96
END

BEGIN nvidia_smi.gpu2_user_num 7999310
SET 'gpu2_user_num' = 2
END

2020-12-02 10:52:34: python.d ERROR: nvidia_smi[nvidia_smi] : update() unhandled exception: invalid literal for int() with base 10: 'Unknown'
2020-12-02 10:52:34: python.d ERROR: nvidia_smi[nvidia_smi] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 197, in run
    updated = self.update(interval=since)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 243, in update
    ok = chart.update(data, interval)
  File "/usr/libexec/netdata/python.d/python_modules/bases/charts.py", line 250, in update
    value = dim.get_value(data)
  File "/usr/libexec/netdata/python.d/python_modules/bases/charts.py", line 348, in get_value
    return int(data[self.id])
ValueError: invalid literal for int() with base 10: 'Unknown'

2020-12-02 10:52:34: python.d DEBUG: nvidia_smi[nvidia_smi] : update => [FAILED] (elapsed time: -, failed retries in a row: 1)
BEGIN nvidia_smi.gpu3_encoder_utilization 9000040
SET 'gpu3_encoder_util' = 0
SET 'gpu3_decoder_util' = 0
END

```

**Comment by xgdgsc** [comment]
[netdata.zip](https://github.com/netdata/netdata/files/5626728/netdata.zip)

**Comment by ilyam8** [comment]
@xgdgsc it seems we have `Unknown` as a value in the _data_

https://github.com/netdata/netdata/blob/94fc082263b81c662997986acc6c91207ab7c162/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L474

Let's add _data_ logging

```python
        self.debug(data)
        return data or None
```

and see debug output again

**Comment by xgdgsc** [comment]
[netdata2.zip](https://github.com/netdata/netdata/files/5633134/netdata2.zip)

**Comment by ilyam8** [comment]
I see, it is

>  'gpu2_fan_speed': 'Unknown',
