### ISSUE TITLE
smartd_log module from python plugin crashes with a ScannerError

### ISSUE THREAD

**Issue by lapin-b** [netdata/netdata#10235]
##### Bug report summary
When setting up the storage device monitoring with `smartd` according to [the relevant documentation](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/smartd_log/) and executing the module in debug mode, a ScannerError shows up and the script halts:

```
netdata@zionketh:~$ /usr/libexec/netdata/plugins.d/python.d.plugin smartd_log debug trace
2020-11-13 15:55:10: python.d INFO: plugin[main] : using python v2
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : [smartd_log] looking for 'smartd_log.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2020-11-13 15:55:10: python.d DEBUG: plugin[main] : [smartd_log] loading '/etc/netdata/python.d/smartd_log.conf'
2020-11-13 15:55:10: python.d ERROR: plugin[main] : [smartd_log] error on loading '/etc/netdata/python.d/smartd_log.conf' : ScannerError()
2020-11-13 15:55:10: python.d ERROR: plugin[main] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 249, in load_module_config
    config.load(abs_path)
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 193, in load
    self.config.update(load_config(abs_path) or dict())
  File "/usr/libexec/netdata/python.d/python_modules/bases/loaders.py", line 46, in load_config
    return load_yaml(stream)
  File "/usr/libexec/netdata/python.d/python_modules/bases/loaders.py", line 39, in load_yaml
    return loader.get_single_data()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/constructor.py", line 38, in get_single_data
    node = self.get_single_node()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 37, in get_single_node
    document = self.compose_document()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 56, in compose_document
    node = self.compose_node(None, None)
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 85, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 134, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 65, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/parser.py", line 99, in check_event
    self.current_event = self.state()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/parser.py", line 450, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/scanner.py", line 117, in check_token
    self.fetch_more_tokens()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/scanner.py", line 258, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/etc/netdata/python.d/smartd_log.conf", line 70, column 1

2020-11-13 15:55:10: python.d INFO: plugin[main] : [smartd_log] has no job configs, skipping it
2020-11-13 15:55:10: python.d INFO: plugin[main] : no jobs to run
netdata@zionketh:~$ 
```

##### OS / Environment
```
Linux zionketh 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

Netdata is running on the Proxmox hypervisor.

The `smartmontools` version is 7.1

##### Netdata version

netdata v1.26.0-186-g4f11789

##### Component Name

Collectors

##### Steps To Reproduce
Assuming that smartmontools is installed and configured as the documentation states

1. Edit `/etc/netdata/python.d/smartd_log.conf` with the command `./edit-config python.d/smartd_log.conf`
2. Set the log path according to your installation:
```
local:
    log_path: '/var/log/smartd'
```
3. Become `netdata`: `sudo -u netdata /bin/bash`
4. Run the python.d plugin for smartd_log module, in debug - trace mode: `/usr/libexec/netdata/plugins.d/python.d.plugin smartd_log debug trace`
5. Observe the error

A few test case lines produced by smartd:

```
2020-11-13 14:47:28;	1;100;0;	9;100;14573;	12;100;158;	148;100;0;	149;100;0;	167;100;0;	168;100;0;	169;100;118;	170;100;140;	172;100;0;	173;100;0;	181;100;0;	182;100;0;	187;100;0;	192;100;129;	194;24;94490984472;	196;100;0;	199;100;0;	218;100;0;	231;45;55;	233;100;80218;	241;100;30903;	242;100;18255;	244;100;556;	245;100;592;	246;100;743562;
2020-11-13 14:57:28;	1;100;0;	9;100;14574;	12;100;158;	148;100;0;	149;100;0;	167;100;0;	168;100;0;	169;100;118;	170;100;140;	172;100;0;	173;100;0;	181;100;0;	182;100;0;	187;100;0;	192;100;129;	194;24;94490984472;	196;100;0;	199;100;0;	218;100;0;	231;45;55;	233;100;80219;	241;100;30903;	242;100;18255;	244;100;556;	245;100;592;	246;100;743567;
2020-11-13 15:07:28;	1;100;0;	9;100;14574;	12;100;158;	148;100;0;	149;100;0;	167;100;0;	168;100;0;	169;100;118;	170;100;140;	172;100;0;	173;100;0;	181;100;0;	182;100;0;	187;100;0;	192;100;129;	194;24;94490984472;	196;100;0;	199;100;0;	218;100;0;	231;45;55;	233;100;80220;	241;100;30904;	242;100;18255;	244;100;556;	245;100;592;	246;100;743575;
```

##### Expected behavior
The script should not error out and the graphs should appear on the dashboard.

**Comment by ilyam8** [comment]
Hi @lapin-b 

`ScannerError` comes from yaml parser, `/etc/netdata/python.d/smartd_log.conf` has YAML syntax error.

You can check it using http://www.yamllint.com/ (copy paste your config in there)

**Comment by lapin-b** [comment]
Hi @ilyam8,

I guess I've made the mistake of hitting the tab key in nano when the `edit-file` script opened it!

Thanks for pointing that out ^^'
