### ISSUE TITLE
python.d/nvidia_smi: ValueError: invalid literal for int() with base 10: 'Unknown'

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10311]
```
BEGIN nvidia_smi.gpu2_user_mem 7999310
SET 'gpu2_user_mem_ychen' = 2167
SET 'gpu2_user_mem_xzhang' = 1715
END

BEGIN nvidia_smi.gpu2_mem_utilization 7999310
SET 'gpu2_memory_util' = 58
END

BEGIN nvidia_smi.gpu0_user_num 7999310
SET 'gpu0_user_num' = 2
END

BEGIN nvidia_smi.gpu1_pci_bandwidth 7999310
SET 'gpu1_rx_util' = 5842000
SET 'gpu1_tx_util' = 822000
END

BEGIN nvidia_smi.gpu1_user_num 7999310
SET 'gpu1_user_num' = 2
END

BEGIN nvidia_smi.gpu2_gpu_utilization 7999310
SET 'gpu2_gpu_util' = 96
END

BEGIN nvidia_smi.gpu2_user_num 7999310
SET 'gpu2_user_num' = 2
END

2020-12-02 10:52:34: python.d ERROR: nvidia_smi[nvidia_smi] : update() unhandled exception: invalid literal for int() with base 10: 'Unknown'
2020-12-02 10:52:34: python.d ERROR: nvidia_smi[nvidia_smi] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 197, in run
    updated = self.update(interval=since)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 243, in update
    ok = chart.update(data, interval)
  File "/usr/libexec/netdata/python.d/python_modules/bases/charts.py", line 250, in update
    value = dim.get_value(data)
  File "/usr/libexec/netdata/python.d/python_modules/bases/charts.py", line 348, in get_value
    return int(data[self.id])
ValueError: invalid literal for int() with base 10: 'Unknown'

2020-12-02 10:52:34: python.d DEBUG: nvidia_smi[nvidia_smi] : update => [FAILED] (elapsed time: -, failed retries in a row: 1)
BEGIN nvidia_smi.gpu3_encoder_utilization 9000040
SET 'gpu3_encoder_util' = 0
SET 'gpu3_decoder_util' = 0
END

```

_Originally posted by @xgdgsc in https://github.com/netdata/netdata/issues/10228#issuecomment-736954633_

**Comment by ilyam8** [comment]
> 'gpu2_fan_speed': 'Unknown'

causes the issue
