### ISSUE TITLE
SocketService.py tries to print binary data

### ISSUE THREAD

**Issue by rda0** [netdata/netdata#10597]
##### Bug report summary
https://github.com/netdata/netdata/blob/767cbf022517e3ae0f05fcf882e1353e0d05ab63/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py#L250 tries to print binary data if `raw=True`, which breaks `ntpd` python module when peers are enabled (`show_peers: yes`).

##### OS / Environment

```
Linux time1 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

netdata v1.29.0
 

##### Component Name

- https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py
- https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ntpd

##### Steps To Reproduce

Configure ntpd to show peers:

```
localhost:
  name: 'local'
  host: 'localhost'
  port: '123'
  show_peers: yes
  peer_filter: ''

localhost_ipv4:
  name: 'local'
  host: '127.0.0.1'
  port: '123'
  show_peers: yes
  peer_filter: ''

localhost_ipv6:
  name: 'local'
  host: '::1'
  port: '123'
  show_peers: yes
  peer_filter: ''
```

Run the module:

```
+time1:/etc/netdata/python.d# su - netdata -s /bin/bash
netdata@time1:~$ /usr/libexec/netdata/plugins.d/python.d.plugin ntpd debug trace nolock
2021-02-04 15:48:44: python.d INFO: plugin[main] : using python v2
2021-02-04 15:48:44: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2021-02-04 15:48:44: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2021-02-04 15:48:44: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2021-02-04 15:48:44: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2021-02-04 15:48:44: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2021-02-04 15:48:44: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2021-02-04 15:48:45: python.d DEBUG: plugin[main] : [ntpd] looking for 'ntpd.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2021-02-04 15:48:45: python.d DEBUG: plugin[main] : [ntpd] loading '/etc/netdata/python.d/ntpd.conf'
2021-02-04 15:48:45: python.d DEBUG: plugin[main] : [ntpd] '/etc/netdata/python.d/ntpd.conf' is loaded
2021-02-04 15:48:45: python.d INFO: plugin[main] : [ntpd] built 3 job(s) configs
2021-02-04 15:48:45: python.d DEBUG: plugin[main] : ntpd[localhost] was previously active, applying recovering settings
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : No unix socket specified. Trying TCP/IP socket.
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : No TLS preference specified, not using TLS.
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : No request specified. Using: ""
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : Creating socket to "::1", port 123
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : connecting socket to "::1", port 123
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : set socket connect timeout to: 2.0
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : connected to "::1", port 123
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : set socket write timeout to: 2.0
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : sending request: 
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : receiving response
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : set socket read timeout to: 2.0
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : received data
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : final response: \version="ntpd 4.2.8p12@1.3728-o (1)", processor="x86_64",
system="Linux/4.19.0-6-amd64", leap=0, stratum=1, precision=-22,
rootdelay=0.000, rootdisp=1.075, refid=PPS, reftime=0xe3c687c7.516c2ecc,
clock=0xe3c687cd.1adaee1a, peer=30561, tc=4, mintc=3, offset=-0.004940,
frequency=25.261, sys_jitter=0.004597, clk_jitter=0.006,
clk_wander=0.002

2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : closing socket
2021-02-04 15:48:45: python.d INFO: plugin[main] : ntpd[localhost] : check success
CHART netdata.runtime_ntpd_local '' 'Execution time for ntpd_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2021-02-04 15:48:45: python.d INFO: plugin[main] : ntpd[localhost_ipv4] : already served by another job, skipping it
2021-02-04 15:48:45: python.d INFO: plugin[main] : ntpd[localhost_ipv6] : already served by another job, skipping it
2021-02-04 15:48:45: python.d DEBUG: ntpd[localhost] : started, update frequency: 1
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : Creating socket to "::1", port 123
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : connecting socket to "::1", port 123
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : set socket connect timeout to: 2.0
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : connected to "::1", port 123
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : set socket write timeout to: 2.0
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : sending request: 
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : receiving response
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : set socket read timeout to: 2.0
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : received data
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : final response: \version="ntpd 4.2.8p12@1.3728-o (1)", processor="x86_64",
system="Linux/4.19.0-6-amd64", leap=0, stratum=1, precision=-22,
rootdelay=0.000, rootdisp=1.090, refid=PPS, reftime=0xe3c687c7.516c2ecc,
clock=0xe3c687ce.0808f14a, peer=30561, tc=4, mintc=3, offset=-0.004940,
frequency=25.261, sys_jitter=0.004597, clk_jitter=0.006,
clk_wander=0.002

2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : closing socket
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : Creating socket to "::1", port 123
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : connecting socket to "::1", port 123
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : set socket connect timeout to: 2.0
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : connected to "::1", port 123
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : set socket write timeout to: 2.0
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : sending request: 
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : receiving response
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : set socket read timeout to: 2.0
2021-02-04 15:48:46: python.d DEBUG: ntpd[localhost] : received data
2021-02-04 15:48:46: python.d ERROR: ntpd[localhost] : update() unhandled exception: 'ascii' codec can't decode byte 0x81 in position 1: ordinal not in range(128)
2021-02-04 15:48:46: python.d ERROR: ntpd[localhost] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 197, in run
    updated = self.update(interval=since)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 222, in update
    data = self.get_data()
  File "/usr/libexec/netdata/python.d/ntpd.chart.py", line 286, in get_data
    self.find_new_peers()
  File "/usr/libexec/netdata/python.d/ntpd.chart.py", line 299, in find_new_peers
    new_peers = dict((p.real_name, p) for p in self.get_peers())
  File "/usr/libexec/netdata/python.d/ntpd.chart.py", line 331, in get_peers
    raw_data = self._get_raw_data(raw=True)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 270, in _get_raw_data
    data = self._receive(raw)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 250, in _receive
    self.debug(u'final response: {0}'.format(data))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 1: ordinal not in range(128)
```

##### Expected behavior

Does not try to print binary data. Maybe the line https://github.com/netdata/netdata/blob/767cbf022517e3ae0f05fcf882e1353e0d05ab63/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py#L250 needs to be changed to:

```python
self.debug(u'final response: {0}'.format(data if not raw else u'binary data'))
```

**Comment by ilyam8** [comment]
@rda0 Hi! Long time no see 🙃 . Since you've suggested the fix... willinig to make a PR?

**Comment by rda0** [comment]
@ilyam8 Hi! I guess it is a good sign if you don't hear from me 😉. Netdata has been working really great for us! Thank you!! I was just migrating our agents from source installation to a packaged version and noticed the bug.

I will make a PR by tomorrow 👍️
