### ISSUE TITLE
Problem with Netdata on the PostgreSQL database with cascading replication

### ISSUE THREAD

**Issue by vitabaks** [netdata/netdata#11453]
##### Bug report summary

When installing and configuring Netdata for monitoring the local postgres database configured in the cascade replication mode, there are simply no postgres charts in the netdata dashboard.

When debugging the postgres module, we observe the following error:
```
sudo /usr/libexec/netdata/plugins.d/python.d.plugin postgres debug trace nolock
2021-08-24 12:54:09: python.d INFO: plugin[main] : using python v2
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : [postgres] looking for 'postgres.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : [postgres] loading '/usr/lib/netdata/conf.d/python.d/postgres.conf'
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : [postgres] '/usr/lib/netdata/conf.d/python.d/postgres.conf' is loaded
2021-08-24 12:54:09: python.d INFO: plugin[main] : [postgres] built 4 job(s) configs
2021-08-24 12:54:09: python.d DEBUG: plugin[main] : postgres[socket] was previously active, applying recovering settings
2021-08-24 12:54:09: python.d DEBUG: postgres[socket] : server version: 130004
2021-08-24 12:54:09: python.d DEBUG: postgres[socket] : superuser: True
2021-08-24 12:54:09: python.d DEBUG: postgres[socket] : discovered databases ['postgres']
2021-08-24 12:54:09: python.d DEBUG: postgres[socket] : discovered secondaries: ['pgnode02']
2021-08-24 12:54:09: python.d DEBUG: postgres[socket] : discovered replication slots: ['pgnode02']
2021-08-24 12:54:09: python.d INFO: plugin[main] : postgres[socket] : check success
CHART netdata.runtime_postgres_local '' 'Execution time for postgres_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1 '' 'python.d.plugin' 'postgres'
DIMENSION run_time 'run time' absolute 1 1

2021-08-24 12:54:09: python.d INFO: plugin[main] : postgres[tcp] : already served by another job, skipping it
2021-08-24 12:54:09: python.d INFO: plugin[main] : postgres[tcpipv4] : already served by another job, skipping it
2021-08-24 12:54:09: python.d INFO: plugin[main] : postgres[tcpipv6] : already served by another job, skipping it
2021-08-24 12:54:09: python.d DEBUG: postgres[socket] : started, update frequency: 1
2021-08-24 12:54:10: python.d DEBUG: postgres[socket] : get_data() returned no data
2021-08-24 12:54:10: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 1)
2021-08-24 12:54:11: python.d DEBUG: postgres[socket] : get_data() returned no data
2021-08-24 12:54:11: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 2)
2021-08-24 12:54:12: python.d DEBUG: postgres[socket] : get_data() returned no data
2021-08-24 12:54:12: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 3)
2021-08-24 12:54:13: python.d DEBUG: postgres[socket] : get_data() returned no data
2021-08-24 12:54:13: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 4)
2021-08-24 12:54:14: python.d DEBUG: postgres[socket] : get_data() returned no data
2021-08-24 12:54:14: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 5)
^C2021-08-24 12:54:15: python.d INFO: plugin[main] : exiting from main...
```
The following errors are found in the PostgreSQL logs:
```
grep ERROR /var/log/postgresql/postgresql-*
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:36 EDT [32382-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:37 EDT [32387-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:38 EDT [32388-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:39 EDT [32389-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:40 EDT [32390-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:43 EDT [32399-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:46 EDT [32400-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:49 EDT [32401-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:52 EDT [32402-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:32:55 EDT [32403-1] [local] postgres@postgres ERROR:  recovery is in progress
/var/log/postgresql/postgresql-Tue.log:2021-08-24 12:33:01 EDT [32404-1] [local] postgres@postgres ERROR:  recovery is in progress

```

SQL Statement
```
2021-08-24 12:56:20 EDT [12343-1] [local] postgres@postgres ERROR:  recovery is in progress
2021-08-24 12:56:20 EDT [12343-2] [local] postgres@postgres HINT:  WAL control functions cannot be executed during recovery.
2021-08-24 12:56:20 EDT [12343-3] [local] postgres@postgres STATEMENT:
        WITH wal_size AS (
          SELECT
            setting::int AS val
          FROM pg_settings
          WHERE name = 'wal_segment_size'
          )
        SELECT
            slot_name,
            slot_type,
            replslot_wal_keep,
            count(slot_file) AS replslot_files
        FROM
            (SELECT
                slot.slot_name,
                CASE
                    WHEN slot_file <> 'state' THEN 1
                END AS slot_file ,
                slot_type,
                COALESCE (
                  floor(
                    (pg_wal_lsn_diff(pg_current_wal_lsn (),slot.restart_lsn)
                     - (pg_walfile_name_offset (restart_lsn)).file_offset) / (s.val)
                  ),0) AS replslot_wal_keep
            FROM pg_replication_slots slot
            LEFT JOIN (
                SELECT
                    slot2.slot_name,
                    pg_ls_dir('pg_replslot/' || slot2.slot_name) AS slot_file
                FROM pg_replication_slots slot2
                ) files (slot_name, slot_file)
                ON slot.slot_name = files.slot_name
            CROSS JOIN wal_size s
            ) AS d
        GROUP BY
            slot_name,
            slot_type,
            replslot_wal_keep;

```

https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/postgres/postgres.chart.py#L559

##### OS / Environment

```
Linux pgnode01 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

```
Version: netdata v1.31.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-cloud' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           NO (by user request)
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES shared-lib
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method

Installed Netdata with kickstart.sh
Also, the problem is reproduced when installing using the .deb package.

##### Component Name

python.d.plugin/postgres

##### Steps To Reproduce

1. Install postgresql and configure cascading replication;
2. Install and configure Netdata for Postgres monitoring;
3. Check the availability of Postgres charts for a PostgreSQL node with cascading replication.

You can use my [playbook](https://github.com/vitabaks/postgresql_cluster) to prepare an environment with Patroni standby cluster.

PostgreSQL High-Availability Cluster based on Patroni in standby_cluster mode, and also Netdata (using kickstart.sh) will be installed and configured.

For the test, you will need at least 2 virtual servers (for Patroni cluster) + 1 source PostgreSQL server.

example:

```shell
# Install Ansible on one control node (which could easily be a laptop)
sudo apt update && sudo apt install python3-pip sshpass git -y 
sudo pip3 install ansible

# Clone the playbook repository
git clone https://github.com/vitabaks/postgresql_cluster.git

# Go to the playbook directory
cd postgresql_cluster/

# Edit the inventory file
## Specify the ip addresses and connection settings (ansible_user, ansible_ssh_pass or ansible_ssh_private_key_file) for your environment
vim inventory

# Run playbook
ansible-playbook deploy_pgcluster.yml --extra-vars '{"patroni_standby_cluster":{"host":"10.128.64.136", "port":"5432"}, "netdata_install": "yes"}'
```

in this example, the IP address 10.128.64.136 is the source from which the standby leader will be replicated.

If you don't have a database for the source role, here an example for installing and configuring the source for the Patroni standby cluster:
```shell
# for debian/ubuntu
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

sudo apt update && sudo apt install -y postgresql-13

sudo -u postgres pg_createcluster 13 main

echo "listen_addresses = '*'" >> /etc/postgresql/13/main/postgresql.conf
echo "host  all  all  0.0.0.0/0  md5" >> /etc/postgresql/13/main/pg_hba.conf
echo "host  replication replicator  0.0.0.0/0 md5" >> /etc/postgresql/13/main/pg_hba.conf

sudo -u postgres pg_ctlcluster 13 main start

sudo -u postgres psql -c "alter role postgres with password 'postgres-pass'"
sudo -u postgres psql -c "create role replicator with LOGIN REPLICATION password 'replicator-pass'"

```

Links:
https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster 

##### Expected behavior

The PostgreSQL databases with cascade replication are defined and charts are displayed in Netdata dashboard `http://MY_HOST:19999/#menu_postgres_local`, 
there are no errors related to the netdata python.d.plugin/postgres module in the PostgreSQL logs.

**Comment by ilyam8** [comment]
Hi, @vitabaks. Thanks for reporting the problem.

@anayrat, hi, as always, your help would be appreciated. Any ideas what's happening?

**Comment by anayrat** [comment]
Indeed, I was able to reproduce the issue:

- Create a replication slot on a standby
- execute the above query
This remind me this issue from another project: https://github.com/OPMDG/check_pgactivity/issues/203

**Comment by ilyam8** [comment]
Thanks! Can you suggest a fix:
 - do not execute the query on a standby
 - modify the query

I checked the referenced issue, and it looks like we need 2nd. Any chance you can submit a PR?

**Comment by anayrat** [comment]
@vitabaks can you try with this fix? https://github.com/netdata/netdata/pull/11455/commits/fac3ff725aede8f8f36e34f8131e401120427606

**Comment by vitabaks** [comment]
> can you try with this fix? fac3ff7

@anayrat thanks!

I replaced the file postgres.chart.py (with your changes) and restarted the netdata service, but there are still no postgres charts on standby leader.
Here is the error that I see when debugging:

```
sudo /usr/libexec/netdata/plugins.d/python.d.plugin postgres debug trace nolock
2021-08-25 04:57:50: python.d INFO: plugin[main] : using python v2
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : [postgres] looking for 'postgres.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : [postgres] loading '/usr/lib/netdata/conf.d/python.d/postgres.conf'
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : [postgres] '/usr/lib/netdata/conf.d/python.d/postgres.conf' is loaded
2021-08-25 04:57:50: python.d INFO: plugin[main] : [postgres] built 4 job(s) configs
2021-08-25 04:57:50: python.d DEBUG: plugin[main] : postgres[socket] was previously active, applying recovering settings
2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : server version: 130004
2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : superuser: True
2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : discovered databases ['postgres']
2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : discovered secondaries: ['pgnode02']
2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : discovered replication slots: ['pgnode02']
2021-08-25 04:57:50: python.d INFO: plugin[main] : postgres[socket] : check success
CHART netdata.runtime_postgres_local '' 'Execution time for postgres_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1 '' 'python.d.plugin' 'postgres'
DIMENSION run_time 'run time' absolute 1 1

2021-08-25 04:57:50: python.d INFO: plugin[main] : postgres[tcp] : already served by another job, skipping it
2021-08-25 04:57:50: python.d INFO: plugin[main] : postgres[tcpipv4] : already served by another job, skipping it
2021-08-25 04:57:50: python.d INFO: plugin[main] : postgres[tcpipv6] : already served by another job, skipping it
2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : started, update frequency: 1
2021-08-25 04:57:50: python.d ERROR: postgres[socket] : update() unhandled exception: 'dict' object does not support indexing
2021-08-25 04:57:50: python.d ERROR: postgres[socket] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 197, in run
    updated = self.update(interval=since)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 222, in update
    data = self.get_data()
  File "/usr/libexec/netdata/python.d/postgres.chart.py", line 1194, in get_data
    self.query_stats(cursor, query, metrics)
  File "/usr/libexec/netdata/python.d/postgres.chart.py", line 1205, in query_stats
    cursor.execute(query, dict(databases=tuple(self.databases)))
  File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
TypeError: 'dict' object does not support indexing

2021-08-25 04:57:50: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 1)
2021-08-25 04:57:51: python.d ERROR: postgres[socket] : update() unhandled exception: 'dict' object does not support indexing
2021-08-25 04:57:51: python.d ERROR: postgres[socket] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 197, in run
    updated = self.update(interval=since)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 222, in update
    data = self.get_data()
  File "/usr/libexec/netdata/python.d/postgres.chart.py", line 1194, in get_data
    self.query_stats(cursor, query, metrics)
  File "/usr/libexec/netdata/python.d/postgres.chart.py", line 1205, in query_stats
    cursor.execute(query, dict(databases=tuple(self.databases)))
  File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
TypeError: 'dict' object does not support indexing

2021-08-25 04:57:51: python.d DEBUG: postgres[socket] : update => [FAILED] (elapsed time: -, failed retries in a row: 2)

```

**Comment by ilyam8** [comment]
@anayrat I am not sure, I googled the problem and the fix is

> Use "%%" instead of "%" in your queries

**Comment by vitabaks** [comment]
> I am not sure, I googled the problem and the fix is

yes it works

```sql

QUERY_REPSLOT_FILES = {
    DEFAULT: """
WITH wal_size AS (
  SELECT
    setting::int AS val
  FROM pg_settings
  WHERE name = 'wal_segment_size'
  )
SELECT
    slot_name,
    slot_type,
    replslot_wal_keep,
    count(slot_file) AS replslot_files
FROM
    (SELECT
        slot.slot_name,
        CASE
            WHEN slot_file <> 'state' THEN 1
        END AS slot_file ,
        slot_type,
        COALESCE (
          floor(
            CASE WHEN pg_is_in_recovery()
            THEN (
              pg_wal_lsn_diff(pg_last_wal_receive_lsn(), slot.restart_lsn)
              -- this is needed to account for whole WAL retention and
              -- not only size retention
              + (pg_wal_lsn_diff(restart_lsn, '0/0') %% s.val)
            ) / s.val
            ELSE (
              pg_wal_lsn_diff(pg_current_wal_lsn(), slot.restart_lsn)
              -- this is needed to account for whole WAL retention and
              -- not only size retention
              + (pg_walfile_name_offset(restart_lsn)).file_offset
            ) / s.val
            END
          ),0) AS replslot_wal_keep
    FROM pg_replication_slots slot
    LEFT JOIN (
        SELECT
            slot2.slot_name,
            pg_ls_dir('pg_replslot/' || slot2.slot_name) AS slot_file
        FROM pg_replication_slots slot2
        ) files (slot_name, slot_file)
        ON slot.slot_name = files.slot_name
    CROSS JOIN wal_size s
    ) AS d
GROUP BY
    slot_name,
    slot_type,
    replslot_wal_keep;
""",
    V10: """
WITH wal_size AS (
  SELECT
    current_setting('wal_block_size')::INT * setting::INT AS val
  FROM pg_settings
  WHERE name = 'wal_segment_size'
  )
SELECT
    slot_name,
    slot_type,
    replslot_wal_keep,
    count(slot_file) AS replslot_files
FROM
    (SELECT
        slot.slot_name,
        CASE
            WHEN slot_file <> 'state' THEN 1
        END AS slot_file ,
        slot_type,
        COALESCE (
          floor(
            CASE WHEN pg_is_in_recovery()
            THEN (
              pg_wal_lsn_diff(pg_last_wal_receive_lsn(), slot.restart_lsn)
              -- this is needed to account for whole WAL retention and
              -- not only size retention
              + (pg_wal_lsn_diff(restart_lsn, '0/0') %% s.val)
            ) / s.val
            ELSE (
              pg_wal_lsn_diff(pg_current_wal_lsn(), slot.restart_lsn)
              -- this is needed to account for whole WAL retention and
              -- not only size retention
              + (pg_walfile_name_offset(restart_lsn)).file_offset
            ) / s.val
            END
          ),0) AS replslot_wal_keep
    FROM pg_replication_slots slot
    LEFT JOIN (
        SELECT
            slot2.slot_name,
            pg_ls_dir('pg_replslot/' || slot2.slot_name) AS slot_file
        FROM pg_replication_slots slot2
        ) files (slot_name, slot_file)
        ON slot.slot_name = files.slot_name
    CROSS JOIN wal_size s
    ) AS d
GROUP BY
    slot_name,
    slot_type,
    replslot_wal_keep;
""",
}
```

**Comment by anayrat** [comment]
oh, sorry for the error, I pushed the last version with `%%`
