### ISSUE TITLE
Core on shutdown - Red Hat 7.9

### ISSUE THREAD

**Issue by bnesbitt** [netdata/netdata#11472]
##### Bug report summary

Intermittent coring observed on shutdown on Red Hat 7.9. It's hard to reproduce every time unfortunately:
`(gdb) bt
#0  0x00007f9f194e5387 in raise () from /lib64/libc.so.6
#1  0x00007f9f194e6a78 in abort () from /lib64/libc.so.6
#2  0x00007f9f19ec414b in uv_async_send () from /lib64/libuv.so.1
#3  0x0000000000421770 in commands_exit () at daemon/commands.c:717
#4  signals_handle () at daemon/signals.c:260
#5  main (argc=<optimized out>, argv=<optimized out>) at daemon/main.c:1379
(gdb) f 3
#3  0x0000000000421770 in commands_exit () at daemon/commands.c:717
717	daemon/commands.c: No such file or directory.
(gdb) p i
$1 = <optimized out>
(gdb) p command_server_initialized
$2 = 1
`

Red Hat 7.9 is using libuv 1.32:
`-bash-4.2# rpm -qf /lib64/libuv.so.1
libuv-1.32.0-1.el7.x86_64
`

Is this a supported version or do we need to use a newer version?

##### OS / Environment

```
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.9 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

##### Netdata version

-bash-4.2# netdata -W buildinfo
Version: netdata v1.31.0
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-libJudy=externaldeps/libJudy' '--with-bundled-lws=externaldeps/libwebsockets' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO

##### Installation method

Installed via rpm

##### Component Name

daemon

##### Steps To Reproduce

No exact steps unfortunately as this appears to be intermittent on shutdown.

**Comment by Ferroin** [comment]
To clarify, did you install through EPEL, or through [our official repositories](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages)?

**Comment by bnesbitt** [comment]
> To clarify, did you install through EPEL, or through [our official repositories](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages)?

Hi,

Yes I got the RPM from the official repo https://packagecloud.io/netdata/netdata, in particular: **netdata-1.31.0-1.el7.x86_64**
https://packagecloud.io/netdata/netdata/packages/el/7/netdata-1.31.0-1.el7.x86_64.rpm

Regards
Brian.

**Comment by erdem2000** [comment]
Hi @bnesbitt,  I tried to reproduce the issue but couldn't be succesfull.  
Are you still experiencing this issue?

**Comment by bnesbitt** [comment]
> Hi @bnesbitt, I tried to reproduce the issue but couldn't be succesfull. Are you still experiencing this issue?

No we haven't seen this one in a while. We're now on 1.34 and we haven't seen this core.
