### ISSUE TITLE
[Bug]: Agent crash during anomaly calculation

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#12648]
### Bug description

The `host->sender` is null causing a crash

```
#0  __GI___pthread_mutex_lock (mutex=mutex@entry=0xc0) at ../nptl/pthread_mutex_lock.c:67
#1  0x000055fe8516a4f2 in __netdata_mutex_lock (mutex=0xc0) at libnetdata/locks/locks.c:57
#2  0x000055fe8532efe8 in rrdpush_sender_thread_spawn (host=0x5601e619f7f0) at streaming/rrdpush.c:468
#3  rrdset_done_push (st=st@entry=0x5601ede38d40) at streaming/rrdpush.c:342
#4  0x000055fe8528c680 in rrdset_done (st=0x5601ede38d40) at database/rrdset.c:1551
#5  0x000055fe8519fa4d in updateDimensionsChart (NumAnomalousDimensions=0, NumNormalDimensions=<optimized out>, NumTrainedDimensions=<optimized out>, RH=<optimized out>) at ml/Host.cc:62
#6  ml::DetectableHost::detectOnce (this=this@entry=0x5601e61941f0) at ml/Host.cc:446
#7  0x000055fe851a19f7 in ml::DetectableHost::detect (this=0x5601e61941f0) at ml/Host.cc:488
#8  0x000055fe851a1aa0 in std::__invoke_impl<void, void (ml::DetectableHost::*)(), ml::DetectableHost*> (__t=<optimized out>, __f=<optimized out>) at /usr/include/c++/10/bits/invoke.h:73
#9  std::__invoke<void (ml::DetectableHost::*)(), ml::DetectableHost*> (__fn=<optimized out>) at /usr/include/c++/10/bits/invoke.h:95
#10 std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> >::_M_invoke<0ul, 1ul> (this=<optimized out>) at /usr/include/c++/10/thread:264
#11 std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> >::operator() (this=<optimized out>) at /usr/include/c++/10/thread:271
#12 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> > >::_M_run (this=<optimized out>) at /usr/include/c++/10/thread:215
#13 0x00007efe7f23aed0 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007efe7f341ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007efe7ef44def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Expected behavior

Agent should not crash

### Steps to reproduce

Not quite sure. It may be there case that the calculation is running while a child disconnects. I will update with more info
if I can pin point it

### Installation method

from source

### System info

```shell
Linux gce-parent1 5.10.0-12-cloud-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.33.1-323-g5ad40fcd3
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by stelfrag** [comment]
I am adding another bt from another crash (it may or may not be related). If needed we will make another issue to investigate. 

The agent information is the same

```
#0  0x000056527565fec2 in rrdset_done (st=0x5655b1f6f670) at database/rrdset.c:1404
#1  0x0000565275574077 in updateRateChart (AnomalyRate=0, RH=<optimized out>) at ml/Host.cc:100
#2  ml::DetectableHost::detectOnce (this=this@entry=0x5655b02894b0) at ml/Host.cc:447
#3  0x00005652755759f7 in ml::DetectableHost::detect (this=0x5655b02894b0) at ml/Host.cc:488
#4  0x0000565275575aa0 in std::__invoke_impl<void, void (ml::DetectableHost::*)(), ml::DetectableHost*> (__t=<optimized out>, __f=<optimized out>)
    at /usr/include/c++/10/bits/invoke.h:73
#5  std::__invoke<void (ml::DetectableHost::*)(), ml::DetectableHost*> (__fn=<optimized out>) at /usr/include/c++/10/bits/invoke.h:95
#6  std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> >::_M_invoke<0ul, 1ul> (this=<optimized out>)
    at /usr/include/c++/10/thread:264
#7  std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> >::operator() (this=<optimized out>) at /usr/include/c++/10/thread:271
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> > >::_M_run (this=<optimized out>)
    at /usr/include/c++/10/thread:215
#9  0x00007f7531994ed0 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f7531a9bea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f753169edef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


#0  0x000056527565fec2 in rrdset_done (st=0x5655b1f6f670) at database/rrdset.c:1404
1404	    if (likely(!st->state->is_ar_chart)) {


(gdb) p st->state
$9 = (struct rrdset_volatile *) 0x100000001000000
(gdb) p st->state->is_ar_chart 
Cannot access memory at address 0x100000001000070
(gdb) 
```

**Comment by stelfrag** [comment]
```
#0  0x000055ef487eeec2 in rrdset_done (st=0x55f045e2f7f0) at database/rrdset.c:1404
#1  0x000055ef4870364b in updateWindowLengthChart (WindowLength=<optimized out>, RH=0x55f03d987000) at ml/Host.cc:137
#2  ml::DetectableHost::detectOnce (this=this@entry=0x55f03d9711b0) at ml/Host.cc:448
#3  0x000055ef487049f7 in ml::DetectableHost::detect (this=0x55f03d9711b0) at ml/Host.cc:488
#4  0x000055ef48704aa0 in std::__invoke_impl<void, void (ml::DetectableHost::*)(), ml::DetectableHost*> (__t=<optimized out>, __f=<optimized out>)
    at /usr/include/c++/10/bits/invoke.h:73
#5  std::__invoke<void (ml::DetectableHost::*)(), ml::DetectableHost*> (__fn=<optimized out>) at /usr/include/c++/10/bits/invoke.h:95
#6  std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> >::_M_invoke<0ul, 1ul> (this=<optimized out>)
    at /usr/include/c++/10/thread:264
#7  std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> >::operator() (this=<optimized out>) at /usr/include/c++/10/thread:271
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (ml::DetectableHost::*)(), ml::DetectableHost*> > >::_M_run (this=<optimized out>)
    at /usr/include/c++/10/thread:215
#9  0x00007fb677687ed0 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fb67778eea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007fb677391def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
