### ISSUE TITLE
[Bug]: Core on chart obsoletion

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#12901]
### Bug description

Core dump 

```
#1  0x000055832fb70f2a in freez (ptr=<optimized out>) at libnetdata/libnetdata.c:166
#2  0x000055832fc96d0b in rrdvar_free (host=host@entry=0x55841bb1f9f0, tree=tree@entry=0x55844e191000, rv=0x55844e1c02a0) at database/rrdvar.c:65
#3  0x000055832fc8cf18 in rrddimvar_free_variables (rs=rs@entry=0x55844e1c0120) at database/rrddimvar.c:19
#4  0x000055832fc8d52a in rrddimvar_free (rs=0x55844e1c0120) at database/rrddimvar.c:199
#5  0x000055832fc911e6 in rrdhost_cleanup_obsolete_charts (host=host@entry=0x55841bb1f9f0) at database/rrdhost.c:1502
#6  0x000055832fc914c6 in rrd_cleanup_obsolete_charts () at database/rrdhost.c:1582
#7  0x000055832fb5f7ea in service_main (ptr=0x558330ba0498) at daemon/service.c:33
#8  0x000055832fb7d785 in thread_start (ptr=<optimized out>) at libnetdata/threads/threads.c:185
#9  0x00007f3e1dae8ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f3e1d6ebdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Expected behavior

No crash

### Steps to reproduce

Unknown for now

### Installation method

from source

### System info

```shell
Linux gce-parent1 5.10.0-12-cloud-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.34.0-186-g7c2bb7e16
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb -DNETDATA_WITHOUT_LONG_DOUBLE -DxNETDATA_TRACE_RWLOCKS=1 -DxNETDATA_TRACE_RWLOCKS_WAIT_TIME_TO_IGNORE_USEC=0' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by stelfrag** [comment]
Closing as this was due to unrelated corruption in host creation (in part of the code that is not in production)
