### ISSUE TITLE
[Bug]: Service thread crashes

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#13499]
### Bug description

I get a segmentation fault by the service thread:

```
-rw------- 1 root    root    1139531776 May  8 22:55 'core-!usr!sbin!netdata-SERVICE-11-0-0-10867-1652039710'
```

Although netdata is compiled with gdb options, I get no output from gdb:

```
gdb -c /tmp/'core-!usr!sbin!netdata-SERVICE-11-0-0-10867-1652039710' /usr/sbin/netdata
(gdb) bt
#0  0x000055f0ab08edad in ?? ()
#1  0x3765353334643437 in ?? ()
#2  0x000055f0bf824ec0 in ?? ()
#3  0x000055f0bf8252e0 in ?? ()
#4  0x000055f0ab08f100 in ?? ()
#5  0x000055f0bf8234b0 in ?? ()
#6  0x000055f0bf824ed0 in ?? ()
#7  0x000055f0be78cfe0 in ?? ()
#8  0x0000000000000000 in ?? ()
```

```
cat /etc/netdata/.environment 
# Created by installer
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/13/bin:${PATH}"
CFLAGS="-O1 -ggdb -Wall -Wextra"
LDFLAGS=""
MAKEOPTS="-j4"
NETDATA_TMPDIR="/tmp"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=" --with-bundled-protobuf"
NETDATA_ADDED_TO_GROUPS=" docker nginx varnish haproxy adm nsd proxy squid ceph nobody"
INSTALL_UID="0"
NETDATA_GROUP="root"
REINSTALL_OPTIONS=""
RELEASE_CHANNEL="nightly"
IS_NETDATA_STATIC_BINARY="no"
NETDATA_LIB_DIR="/var/lib/netdata"
```

### Expected behavior

Not crash

### Steps to reproduce

I am not sure.
This is a parent.

### Installation method

from source

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux box 5.15.25-gentoo-dist #1 SMP Wed Feb 23 14:32:41 -00 2022 x86_64 Intel(R) Celeron(R) CPU J1900 @ 1.99GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
```

### Netdata build info

```shell
Version: netdata v1.35.0-265-g5b5eac5ed
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb -Wall -Wextra' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by MrZammler** [comment]
Costa hi! Just to make sure, it's a fresh core, despite date of file being May 8?

**Comment by ktsaou** [comment]
I am closing this. I will try to reproduce.
