### ISSUE TITLE
[Bug]: SIGABRT netdata

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#13680]
### Bug description

After we merge the PR https://github.com/netdata/netdata/pull/13646 I began to have `SIGABRT` on `Raspberry PI` when I stop netdata:

```sh
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/usr/sbin/netdata --special-spawn-server'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0xb6902340 (LWP 24401))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0xb692e364 in __GI_abort () at abort.c:79
#2  0x0004e880 in crash_netdata () at libnetdata/log/log.c:856
#3  0x0004f8d4 in fatal_int (file=file@entry=0x2a2e18 "spawn/spawn_server.c", function=0x1 <error: Cannot access memory at address 0x1>, function@entry=0x2a318c <__FUNCTION__.1> "wait_children", line=line@entry=142, 
    fmt=0x2606cc "Assertion `%s' failed") at libnetdata/log/log.c:908
#4  0x001a991c in wait_children (arg=<optimized out>) at spawn/spawn_server.c:142
#5  0xb6b0d310 in start_thread (arg=0xb6902340) at pthread_create.c:477
#6  0xb69f2da8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

### Expected behavior

Stop netdata without any issues.

### Steps to reproduce

1. Compile netdata with flags `CFLAGS="-Og -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -Wformat-truncation=2 -Wunused-result -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1"`
2. Run `netdata` during few minutes, and stop it.
3. Run `coredumpctl list` to check if you have a `SIGABRT`

### Installation method

from source

### System info

```shell
root@potinho:/home/thiago/Netdata/netdata# uname -a; grep -HvE "^#|URL" /etc/*release
Linux potinho 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
```

### Netdata build info

```shell
Version: netdata v1.36.0-129-ga6a7a8c8b
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-lto' '--with-bundled-protobuf' 'CFLAGS=-Og -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -Wformat-truncation=2 -Wunused-result -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO 
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

An additional information, this is not happening everytime. I had to start and stop netdata frequently.

**Comment by MrZammler** [comment]
Hi Thiago.

Have you still got this problem? I'm trying to reproduce it, does your rpi have been set up for alert notifications? Did you notice if it happens when/after a notification is triggered?

**Comment by thiagoftsm** [comment]
Last two days I worked with my raspberry pi the whole day and I did not have this issue again, so I am closing it.
