### ISSUE TITLE
[Bug]: Attempting free on address which was not malloc()-ed (eBPF)

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata#13922]
### Bug description

See below:

```
=================================================================
==75566==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x603000012190 in thread T1
    #0 0x55dda0d72867 in free (/usr/libexec/netdata/plugins.d/ebpf.plugin+0xdc867)
    #1 0x55dda0e4bb9d in freez libnetdata/libnetdata.c:406
    #2 0x55dda0e10eb1 in cleanup_variables_from_other_threads collectors/ebpf.plugin/ebpf_apps.c:978
    #3 0x55dda0e11b6f in collect_data_for_all_processes collectors/ebpf.plugin/ebpf_apps.c:1134
    #4 0x55dda0de063c in process_collector collectors/ebpf.plugin/ebpf_process.c:1152
    #5 0x55dda0de0cb2 in ebpf_process_thread collectors/ebpf.plugin/ebpf_process.c:1362
    #6 0x55dda0e72675 in thread_start libnetdata/threads/threads.c:203
    #7 0x7f19fe64cb42 in start_thread nptl/pthread_create.c:442
    #8 0x7f19fe6de9ff  (/lib/x86_64-linux-gnu/libc.so.6+0x1269ff)

0x603000012190 is located 16 bytes to the right of 32-byte region [0x603000012160,0x603000012180)
allocated by thread T11 here:
    #0 0x55dda0d72d87 in calloc (/usr/libexec/netdata/plugins.d/ebpf.plugin+0xdcd87)
    #1 0x55dda0e4bc4b in callocz libnetdata/libnetdata.c:416
    #2 0x55dda0dced02 in ebpf_fd_allocate_global_vectors collectors/ebpf.plugin/ebpf_fd.c:1102
    #3 0x55dda0dd13ea in ebpf_fd_thread collectors/ebpf.plugin/ebpf_fd.c:1164
    #4 0x55dda0e72675 in thread_start libnetdata/threads/threads.c:203
    #5 0x7f19fe64cb42 in start_thread nptl/pthread_create.c:442

Thread T1 created by T0 here:
    #0 0x55dda0d169f5 in __interceptor_pthread_create (/usr/libexec/netdata/plugins.d/ebpf.plugin+0x809f5)
    #1 0x55dda0e72cd0 in netdata_thread_create libnetdata/threads/threads.c:217
    #2 0x55dda0dbe42f in main collectors/ebpf.plugin/ebpf.c:2203
    #3 0x7f19fe5e1d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Thread T11 created by T0 here:
    #0 0x55dda0d169f5 in __interceptor_pthread_create (/usr/libexec/netdata/plugins.d/ebpf.plugin+0x809f5)
    #1 0x55dda0e72cd0 in netdata_thread_create libnetdata/threads/threads.c:217
    #2 0x55dda0dbe42f in main collectors/ebpf.plugin/ebpf.c:2203
    #3 0x7f19fe5e1d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: bad-free (/usr/libexec/netdata/plugins.d/ebpf.plugin+0xdc867) in free
==75566==ABORTING
2022-10-31 21:54:45: netdata ERROR : PLUGINSD[ebpf] : (0238@parser/parser.c     :parser_next    ): read failed: end of file (errno 9, Bad file descriptor)
2022-10-31 21:54:45: netdata ERROR : PLUGINSD[ebpf] : (0133@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 75566) disconnected after 102 successful data collections (ENDs).
2022-10-31 21:54:46: netdata ERROR : PLUGINSD[ebpf] : (0412@libnetdata/popen/pop:netdata_pclose ): child pid 75566 exited with code 1.
2022-10-31 21:54:46: netdata ERROR : PLUGINSD[ebpf] : (0091@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 75566) exited with error code 1, but has given useful output in the past (771 times). Waiting a bit before starting it again.
```

### Expected behavior

eBPF not to crash when building with address sanitizer.

### Steps to reproduce

Install Netdata from source using the following arguments (run using address saitizer):
```
sudo CFLAGS="-Og -ggdb -Wall -Wextra -fsanitize=address -static-libasan -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_DEV_MODE=1 -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1 -Wformat-truncation=2 -Wunused-result" ./netdata-installer.sh --dont-wait --disable-telemetry --disable-cloud --disable-ml --disable-go --disable-lto --use-system-protobuf
```

### Installation method

from source

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-cloud' '--disable-ml' '--disable-lto' '--without-bundled-protobuf' 'CFLAGS=-Og -ggdb -Wall -Wextra -fsanitize=address -static-libasan -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_DEV_MODE=1 -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1 -Wformat-truncation=2 -Wunused-result' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
@thiagoftsm, hey 👋  Was this issue addressed by one of your many PRs?

**Comment by thiagoftsm** [comment]
Probably the current that is now blocked will also fix this.
