### ISSUE TITLE
[Bug]: execute netdata -W createdataset=10 core dumped

### ISSUE THREAD

**Issue by wk333** [netdata/netdata#14421]
### Bug description

execute `netdata -W createdataset=10` 

generate_dbengine_dataset()  running...
Initializing localhost with hostname 'dbengine-dataset' Segmentation fault core dumped

### Expected behavior

no error

### Steps to reproduce

1.install netdata-1.37.1
2.execute netdata -W createdataset=10
3.core dumped
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux openEuler 5.10.0-60.18.0.50.oe2203.aarch64 #1 SMP Wed Mar 30 02:43:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
/etc/openEuler-release:openEuler release 22.03 LTS
/etc/os-release:NAME="openEuler"
/etc/os-release:VERSION="22.03 LTS"
/etc/os-release:ID="openEuler"
/etc/os-release:VERSION_ID="22.03"
/etc/os-release:PRETTY_NAME="openEuler 22.03 LTS"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:
/etc/system-release:openEuler release 22.03 LTS

fedora37 Server Edition same erre
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--build=aarch64-openEuler-linux-gnu' '--host=aarch64-openEuler-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-plugin-freeipmi' '--enable-plugin-cups' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=aarch64-openEuler-linux-gnu' 'host_alias=aarch64-openEuler-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection' 'LDFLAGS=-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld' 'CXXFLAGS=-O2 -g -pi
```

**Comment by ilyam8** [comment]
Coredump

```c
Core was generated by `/opt/netdata/usr/sbin/netdata -W createdataset=10'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/1399506' in core file too small.
#0  dict_item_find_and_acquire (dict=dict@entry=0x0, name=name@entry=0x55751f6b514b "dbengine-dataset", name_len=name_len@entry=-1)
    at libnetdata/dictionary/dictionary.c:1738
1738	    if(unlikely(is_dictionary_destroyed(dict))) {
(gdb) bt
#0  dict_item_find_and_acquire (dict=dict@entry=0x0, name=name@entry=0x55751f6b514b "dbengine-dataset", name_len=name_len@entry=-1)
    at libnetdata/dictionary/dictionary.c:1738
#1  0x000055751f41347c in dictionary_get_and_acquire_item_advanced (dict=dict@entry=0x0, name=name@entry=0x55751f6b514b "dbengine-dataset", name_len=name_len@entry=-1)
    at libnetdata/dictionary/dictionary.c:2198
#2  0x000055751f413496 in dictionary_get_advanced (dict=0x0, name=name@entry=0x55751f6b514b "dbengine-dataset", name_len=name_len@entry=-1)
    at libnetdata/dictionary/dictionary.c:2204
#3  0x000055751f562bf9 in rrdhost_find_by_guid (guid=0x55751f6b514b "dbengine-dataset") at database/rrdhost.c:73
#4  rrdhost_find_or_create (hostname=hostname@entry=0x55751f6b514b "dbengine-dataset", registry_hostname=registry_hostname@entry=0x55751f6b514b "dbengine-dataset",
    guid=guid@entry=0x55751f6b514b "dbengine-dataset", os=0x55751f6bae87 "linux", timezone=0x0, abbrev_timezone=0x0, utc_offset=0, tags=0x55751f6ea085 "",
    program_name=0x55751f6abbb6 "netdata", program_version=0x55751f6b9798 "v1.37.0-251-ga136acf0f", update_every=1, history=3600, mode=RRD_MEMORY_MODE_DBENGINE,
    health_enabled=1, rrdpush_enabled=0, rrdpush_destination=0x0, rrdpush_api_key=0x0, rrdpush_send_charts_matching=0x0, rrdpush_enable_replication=true,
    rrdpush_seconds_to_replicate=86400, rrdpush_replication_step=600, system_info=0x0, archived=false) at database/rrdhost.c:682
#5  0x000055751f402286 in dbengine_rrdhost_find_or_create (name=name@entry=0x55751f6b514b "dbengine-dataset") at daemon/unit_test.c:1779
#6  0x000055751f407108 in generate_dbengine_dataset (history_seconds=10) at daemon/unit_test.c:2295
#7  0x000055751f3fd48c in main (argc=3, argv=0x7ffe6ebaf4b8) at daemon/main.c:1526
```
