### ISSUE TITLE
[Bug]: buggy / ancient netdata agents, make the parent enter an endless loop

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#14433]
### Bug description

```
Thread 84 (Thread 0x7f01de1fe640 (LWP 1201) "RCVR[pi1,[10.11"):
#0  0x000055691e94871b in rrddim_store_metric (rd=0x556923f00410, point_end_time_ut=212179652895000000, n=nan(0x8000000000000), flags=SN_FLAG_NONE) at database/rrdset.c:1221
#1  0x000055691e948e0e in rrdset_done_interpolate (st=0x5569218c6350, rda_base=0x556932982030, rda_slots=2, update_every_ut=5000000, last_stored_ut=212179652890000000, next_store_ut=212179652895000000, last_collect_ut=212179652890000000, now_collect_ut=223242122277631722, store_this_entry=1 '\001', has_reset_value=1) at database/rrdset.c:1426
#2  0x000055691e949f5d in rrdset_timed_done (st=0x5569218c6350, now=..., pending_rrdset_next=false) at database/rrdset.c:1859
#3  0x000055691e91de94 in pluginsd_end (words=0x7f01de1ef750, num_words=1, user=0x7f01de1f3460) at collectors/plugins.d/pluginsd_parser.c:203
#4  0x000055691ea8caaa in parser_action (parser=0x5569441131a0, input=0x7f01de1f3560 "END") at parser/parser.c:346
#5  0x000055691ea73f9b in streaming_parser (rpt=0x55692517c010, cd=0x7f01de1f71e0, fd=49, ssl=0x0) at streaming/receiver.c:408
#6  0x000055691ea758f8 in rrdpush_receive (rpt=0x55692517c010) at streaming/receiver.c:821
#7  0x000055691ea75c46 in rrdpush_receiver_thread (ptr=0x55692517c010) at streaming/receiver.c:880
#8  0x000055691e757162 in thread_start (ptr=0x556925fe4110) at libnetdata/threads/threads.c:206
#9  0x00007f02185ebfef in start_thread (arg=0x7f01de1fe640) at pthread_create.c:463
#10 0x00007f02181b700f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

Check the timestamps. This is 1 core always generating empty points.

### Expected behavior

1. not consume 100% cpu when the child clock jumps (instead of looping forever, rely on the db for the gap).
2. detect such situation and reset the clock of the child to current time

### Steps to reproduce

1. You need a buggy version of netdata. I used 1.19 for this test.
2. Probably a buggy system clock on the child system is also needed.
3. A current-master parent
4. Wait a couple of days (while streaming is on), and it will happen.

### Installation method

kickstart.sh

### System info

```shell
Linux box 5.15.25-gentoo-dist #1 SMP Wed Feb 23 14:32:41 -00 2022 x86_64 Intel(R) Celeron(R) CPU J1900 @ 1.99GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
```

### Netdata build info

```shell
Version: netdata v1.37.0-252-g9729196eb
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=root' '--with-bundled-protobuf' 'CFLAGS=-O0 -g -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -Wformat-truncation=2 -Wunused-result' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by vobruba-martin** [comment]
I guess this is a cause of #14119 . For me this issue appears in a few hours, not days. I had to stop streaming from those servers.

**Comment by ktsaou** [comment]
We just merged PR https://github.com/netdata/netdata/pull/14431 that solved the issue for this case. The problem was that when there was a huge gap in data collection (a plugin stopped collecting a metric for days), the parent was looping quite a lot to fill the gap with NULLs. Now it relies on the db (dbengine) to do it, which flushes the page and creates a gap indirectly, with the absence of metrics.
