### ISSUE TITLE
[Feat]: defunct plugins

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#15108]
### Problem

Sometimes we see Netdata plugins staying defunct forever.

This is a problem for many reasons. The biggest reason is that people that rely on plugins to actually collect metrics and trigger alerts when something is wrong, will never receive these alerts and they won't be able to check past metrics to see what was wrong.

### Description

We need to find a way to make sure that plugins work as expected, and if they don't, they are automatically restarted.

### Importance

blocker

### Value proposition

The most important thing is to understand why Netdata plugins go defunct.

When a process becomes defunct, it means that the process has finished its execution, but its entry still remains in the process table.

A process becomes defunct when it terminates, but its parent process (Netdata in our case) has not yet retrieved its exit status using the wait() system call. The exit status of a process contains information about its termination, such as whether it exited normally or encountered an error.

In normal circumstances, when a child process terminates, the parent process receives a SIGCHLD signal indicating that one of its child processes has exited. The parent process should then call the wait() system call to retrieve the exit status of the terminated child process and remove its entry from the process table. Until the parent process retrieves the exit status, the child process remains in a defunct state.

Defunct processes do not consume system resources other than their entry in the process table. However, if Netdata does not catch its signal, it thinks that the plugin is collecting data, which is wrong and leads to data loss.

As a workaround or as an additional check, Netdata should automatically kill and restart any plugin that is not collecting metrics.

I suggest a configuration option in `[plugins]` that will set the frequency Netdata will check each of each plugins is sending metrics or not.

When a plugin is found not sending metrics, Netdata should kill it, close its stdin/out, catch any signals related to it and restart it.

**Comment by ktsaou** [comment]
Examples:

```
2161672 ?        SNsl 21861:39 /opt/netdata/usr/sbin/netdata -P /run/netdata/netdata.pid -D
2161677 ?        SNl    0:16  \_ /opt/netdata/usr/sbin/netdata --special-spawn-server
2162086 ?        SNl   32:25  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
2162089 ?        SNl   16:25  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
2162091 ?        ZN     0:06  \_ [debugfs.plugin] <defunct>
2162092 ?        SNl    0:41  \_ /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
4038902 ?        SN     0:01  \_ bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

Another:

```
2340394 ?        SNsl 21468:13 /opt/netdata/usr/sbin/netdata -P /run/netdata/netdata.pid -D
2340398 ?        SNl    0:17  \_ /opt/netdata/usr/sbin/netdata --special-spawn-server
2340773 ?        SNl    0:43  \_ /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
2340777 ?        SNl   31:21  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
2340780 ?        SNl   13:19  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
2340781 ?        ZN     0:06  \_ [debugfs.plugin] <defunct>
 325792 ?        SN     0:03  \_ bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

Another:

```
1498875 ?        SNsl  47:11 /opt/netdata/usr/sbin/netdata -P /run/netdata/netdata.pid -D
1498878 ?        SNl    0:00  \_ /opt/netdata/usr/sbin/netdata --special-spawn-server
1500192 ?        SN     0:06  \_ /opt/netdata/usr/libexec/netdata/plugins.d/debugfs.plugin 1
1500198 ?        SNl    2:28  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
1500201 ?        ZN     0:10  \_ [bash] <defunct>
1500204 ?        ZN     5:30  \_ [freeipmi.plugin] <defunct>
1500208 ?        SNl    6:58  \_ /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
1500211 ?        SNl   49:22  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
```

**Comment by ktsaou** [comment]
For the last case (defunct bash and freeipmi), Netdata pluginsd thread for freeipmi is stuck here:

```
gdb) bt
#0  __GI___libc_read (nbytes=4096, buf=0x55a715f99e70, fd=207) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=207, buf=0x55a715f99e70, nbytes=4096) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007fed098414da in _IO_new_file_underflow (fp=0x55a715f4efb0) at libioP.h:948
#3  0x00007fed09842742 in __GI__IO_default_uflow (fp=0x55a715f4efb0) at libioP.h:948
#4  0x00007fed0983569c in __GI__IO_getline_info (fp=fp@entry=0x55a715f4efb0, buf=buf@entry=0x7febaa433da0 "END", n=n@entry=15359, delim=delim@entry=10, extract_delim=extract_delim@entry=1, eof=eof@entry=0x0) at iogetline.c:60
#5  0x00007fed09835798 in __GI__IO_getline (fp=fp@entry=0x55a715f4efb0, buf=buf@entry=0x7febaa433da0 "END", n=n@entry=15359, delim=delim@entry=10, extract_delim=extract_delim@entry=1) at iogetline.c:34
#6  0x00007fed09834696 in _IO_fgets (buf=0x7febaa433da0 "END", n=15360, fp=0x55a715f4efb0) at iofgets.c:53
#7  0x000055a71386e423 in parser_next ()
#8  0x000055a71399cba6 in pluginsd_process ()
#9  0x000055a7139925b5 in pluginsd_worker_thread ()
#10 0x000055a713878ea3 in netdata_thread_init ()
#11 0x00007fed09cccea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007fed098bfa2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
