### ISSUE TITLE
[Bug]: Netdata crashes with `default memory mode = save` in `stream.conf`

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#15714]
### Bug description

Reported in https://github.com/netdata/helmchart/issues/376#issuecomment-1662405579

Coredump

```c
#0  update_metric_handle_from_rrddim (rd=0x294e22060f51df31, mh=0x55623e4ce8d0) at database/ram/rrddim_mem.c:37
#1  rrddim_collect_init (db_metric_handle=0x55623e4ce8d0, update_every=60, smg=0x55623e794170) at database/ram/rrddim_mem.c:142
#2  0x000055623d315278 in storage_metric_store_init (smg=<optimized out>, update_every=<optimized out>, metric_handle=<optimized out>, id=<optimized out>)
    at database/storage_engine.h:57
#3  rrddim_insert_callback (item=<optimized out>, rrddim=0x55623fef5100, constructor_data=0x7f3194a19070) at database/rrddim.c:285
#4  0x000055623d18fdd7 in dictionary_execute_insert_callback (dict=dict@entry=0x55623e5d3d20, item=item@entry=0x55623fece500,
    constructor_data=constructor_data@entry=0x7f3194a19070) at libnetdata/dictionary/dictionary.c:559
#5  0x000055623d1919fd in dict_item_create_with_hooks (master_item=<optimized out>, constructor_data=<optimized out>, value_len=408,
    value=<optimized out>, name_len=<optimized out>, name=0x55623d76b799 "enabled", dict=0x55623e5d3d20) at libnetdata/dictionary/dictionary.c:1366
#6  dict_item_add_or_reset_value_and_acquire (dict=dict@entry=0x55623e5d3d20, name=name@entry=0x55623d76b799 "enabled", name_len=<optimized out>,
    name_len@entry=-1, value=value@entry=0x0, value_len=408, constructor_data=constructor_data@entry=0x7f3194a19070, master_item=<optimized out>)
    at libnetdata/dictionary/dictionary.c:1633
#7  0x000055623d19228f in dictionary_set_and_acquire_item_advanced (dict=dict@entry=0x55623e5d3d20, name=name@entry=0x55623d76b799 "enabled",
    name_len=name_len@entry=-1, value=value@entry=0x0, value_len=<optimized out>, constructor_data=constructor_data@entry=0x7f3194a19070)
    at libnetdata/dictionary/dictionary.c:2124
#8  0x000055623d1922d4 in dictionary_set_advanced (dict=0x55623e5d3d20, name=name@entry=0x55623d76b799 "enabled", name_len=name_len@entry=-1,
    value=value@entry=0x0, value_len=<optimized out>, constructor_data=constructor_data@entry=0x7f3194a19070) at libnetdata/dictionary/dictionary.c:2131
#9  0x000055623d315b4e in rrddim_add (st=0x55623fe997a0, id=0x55623d76b799 "enabled", name=<optimized out>, multiplier=<optimized out>,
    divisor=<optimized out>, algorithm=<optimized out>) at database/rrddim.c:632
#10 0x000055623d212aa2 in ml_update_dimensions_chart (host=0x55623e5437c0, mls=...) at ml/ad_charts.cc:37
#11 0x000055623d2dca3e in ml_host_detect_once (host=0x55623e5437c0) at ml/ml.cc:1045
#12 ml_detect_main (arg=<optimized out>) at ml/ml.cc:1142
#13 0x000055623d1b0ab0 in netdata_thread_init (ptr=<optimized out>) at libnetdata/threads/threads.c:262
#14 0x00007f31d5ca8044 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#15 0x00007f31d5d285fc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### Expected behavior

Netdata doesn't crash

### Steps to reproduce

1. Setup parent-child setup
2. Set `default memory mode = save` in parent's `stream.conf`

### Installation method

kickstart.sh

### System info

```shell
Debian12
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.41.0-266-gf7ebe06a0
    Installation Type __________________________________________ : custom
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ :  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb' 'LDFLAGS='
Default Directories:
    User Configurations ________________________________________ : /opt/netdata/etc/netdata
    Stock Configurations _______________________________________ : /opt/netdata/usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /opt/netdata/var/cache/netdata
    Permanent Databases ________________________________________ : /opt/netdata/var/lib/netdata
    Plugins ____________________________________________________ : /opt/netdata/usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /opt/netdata/usr/share/netdata/web
    Log Files __________________________________________________ : /opt/netdata/var/log/netdata
    Lock Files _________________________________________________ : /opt/netdata/var/lib/netdata/lock
    Home _______________________________________________________ : /opt/netdata/var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.1.0-10-amd64
    Operating System ___________________________________________ : Debian GNU/Linux
    Operating System ID ________________________________________ : debian
    Operating System ID Like ___________________________________ : unknown
    Operating System Version ___________________________________ : 12 (bookworm)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 16
    CPU Frequency ______________________________________________ : 1999000000
    CPU Architecture ___________________________________________ : 33703305216
    RAM Bytes __________________________________________________ : 214748364800
    Disk Capacity ______________________________________________ : x86_64
    Virtualization Technology __________________________________ : kvm
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (lz4)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (bundled)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : YES
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

**Comment by stelfrag** [comment]
Fixed by [#15723](https://github.com/netdata/netdata/pull/15723)
