### ISSUE TITLE
[Bug]: HP SSA collector is failing to parse `ssacli` output for unassigned drives

### ISSUE THREAD

**Issue by nadalizadeh** [netdata/netdata#15792]
### Bug description

hpssa collector fails when parsing `ssacli` output that includes `unassigned` drives:

```
bash-4.2$ ./python.d.plugin hpssa debug trace
2023-08-10 22:46:55: python.d INFO: plugin[main] : using python v3
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : looking for '/etc/netdata/python.d.conf'
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : looking for '/usr/lib/netdata/conf.d/python.d.conf'
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : [hpssa] loaded module source : '/usr/libexec/netdata/python.d/hpssa.chart.py'
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : [hpssa] looking for 'hpssa.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : [hpssa] loading '/etc/netdata/python.d/hpssa.conf'
2023-08-10 22:46:55: python.d DEBUG: plugin[main] : [hpssa] '/etc/netdata/python.d/hpssa.conf' is loaded
2023-08-10 22:46:55: python.d INFO: plugin[main] : [hpssa] built 1 job(s) configs
2023-08-10 22:46:55: python.d DEBUG: hpssa[hpssa] : Executing command '/bin/sudo -n -l /opt/hp/hpssacli/bld/hpssacli'
2023-08-10 22:46:55: python.d INFO: hpssa[hpssa] : Command: ['/bin/sudo', '-n', '/opt/hp/hpssacli/bld/hpssacli', 'ctrl', 'all', 'show', 'config', 'detail']
2023-08-10 22:46:55: python.d DEBUG: hpssa[hpssa] : Executing command '/bin/sudo -n /opt/hp/hpssacli/bld/hpssacli ctrl all show config detail'
2023-08-10 22:46:56: python.d ERROR: hpssa[hpssa] : Cannot parse line: unassigned
2023-08-10 22:46:56: python.d ERROR: hpssa[hpssa] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 307, in get_adapters
    adapters = HPSSA(self._get_raw_data(command=self.cmd)).adapters
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 121, in __init__
    self.parse()
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 152, in parse
    self.adapters.append(self.parse_adapter(**match.groupdict()))
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 208, in parse_adapter
    raise HPSSAException('Cannot parse line: {}'.format(line))
pythond_hpssa.HPSSAException: Cannot parse line: unassigned

2023-08-10 22:46:56: python.d INFO: hpssa[hpssa] : Discovered adapters: []
2023-08-10 22:46:56: python.d ERROR: hpssa[hpssa] : No adapters discovered
2023-08-10 22:46:56: python.d INFO: plugin[main] : hpssa[hpssa] : check failed
2023-08-10 22:46:56: python.d INFO: plugin[main] : no jobs to serve
2023-08-10 22:46:56: python.d INFO: plugin[main] : exiting from main...
```

Example data that triggers the error:

```
Smart Array P420i in Slot 0 (Embedded)
   Bus Interface: PCI
   Slot: 0
   Serial Number: 5001438024F9CF80
   Cache Serial Number: PBKUA0BRH4A2MU
   Controller Status: OK
   Hardware Revision: B
   Firmware Version: 3.54
   Rebuild Priority: Medium
   Expand Priority: Medium
   Surface Scan Delay: 15 secs
   Surface Scan Mode: Idle
   Parallel Surface Scan Supported: No
   Queue Depth: Automatic
   Monitor and Performance Delay: 60  min
   Elevator Sort: Enabled
   Degraded Performance Optimization: Disabled
   Inconsistency Repair Policy: Disabled
   Wait for Cache Room: Disabled
   Surface Analysis Inconsistency Notification: Disabled
   Post Prompt Timeout: 0 secs
   Cache Board Present: True
   Cache Status: OK
   Cache Ratio: 100% Read / 0% Write
   Drive Write Cache: Disabled
   Total Cache Size: 512 MB
   Total Cache Memory Available: 304 MB
   No-Battery Write Cache: Disabled
   Battery/Capacitor Count: 0
   SATA NCQ Supported: True
   Spare Activation Mode: Activate on physical drive failure (default)
   Controller Temperature (C): 51
   Cache Module Temperature (C): 31
   Number of Ports: 2 Internal only
   Driver Name: hpsa
   Driver Version: 3.4.20
   Driver Supports HPE SSD Smart Path: True
   PCI Address (Domain:Bus:Device.Function): 0000:02:00.0
   Host Serial Number: JPT23081XF
   Sanitize Erase Supported: False
   Primary Boot Volume: logicaldrive 1 (600508B1001C090397463ECD222390C5)
   Secondary Boot Volume: None


   Port Name: 1I
         Port ID: 0
         Port Connection Number: 0
         SAS Address: 5001438024F9CF80
         Port Location: Internal

   Port Name: 2I
         Port ID: 1
         Port Connection Number: 1
         SAS Address: 5001438024F9CF84
         Port Location: Internal

   Internal Drive Cage at Port 1I, Box 1, OK
      Power Supply Status: Not Redundant
      Drive Bays: 4
      Port: 1I
      Box: 1
      Location: Internal

   Physical Drives
      physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SAS, 300 GB, OK)
      physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SAS, 300 GB, OK)
      physicaldrive 1I:1:3 (port 1I:box 1:bay 3, Solid State SATA, 480.1 GB, OK)
      physicaldrive 1I:1:4 (port 1I:box 1:bay 4, Solid State SATA, 480.1 GB, OK)


   Internal Drive Cage at Port 2I, Box 1, OK
      Power Supply Status: Not Redundant
      Drive Bays: 4
      Port: 2I
      Box: 1
      Location: Internal

   Physical Drives
      physicaldrive 2I:1:5 (port 2I:box 1:bay 5, Solid State SATA, 480.1 GB, OK)
      physicaldrive 2I:1:6 (port 2I:box 1:bay 6, Solid State SATA, 480.1 GB, OK)
      physicaldrive 2I:1:7 (port 2I:box 1:bay 7, SAS, 1 TB, OK)
      physicaldrive 2I:1:8 (port 2I:box 1:bay 8, SAS, 1 TB, OK)

   Array: A
      Interface Type: SAS
      Unused Space: 0  MB (0.0%)
      Used Space: 558.7 GB (100.0%)
      Status: OK
      Array Type: Data 


      Logical Drive: 1
         Size: 279.4 GB
         Fault Tolerance: 1
         Heads: 255
         Sectors Per Track: 32
         Cylinders: 65535
         Strip Size: 256 KB
         Full Stripe Size: 256 KB
         Status: OK
         Caching:  Enabled
         Unique Identifier: 600508B1001C090397463ECD222390C5
         Disk Name: /dev/sda 
         Mount Points: /boot 1024 MB Partition Number 2
         OS Status: LOCKED
         Logical Drive Label: AA8DE7775001438024F9CF80 FA2B
         Mirror Group 1:
            physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SAS, 300 GB, OK)
         Mirror Group 2:
            physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SAS, 300 GB, OK)
         Drive Type: Data
         LD Acceleration Method: Controller Cache

      physicaldrive 1I:1:1
         Port: 1I
         Box: 1
         Bay: 1
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 300 GB
         Drive exposed to OS: False
         Native Block Size: 512
         Rotational Speed: 10500
         Firmware Revision: HPD5
         Serial Number: S4235XBA0000E721P6EX
         Model: HP      EG0300JFCKA
         Current Temperature (C): 34
         Maximum Temperature (C): 49
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         Drive Authentication Status: OK
         Carrier Application Version: 11
         Carrier Bootloader Version: 6
         Sanitize Erase Supported: True
         Sanitize Estimated Max Erase Time: 1 hour(s)12 minute(s)
         Unrestricted Sanitize Supported: False

      physicaldrive 1I:1:2
         Port: 1I
         Box: 1
         Bay: 2
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 300 GB
         Drive exposed to OS: False
         Native Block Size: 512
         Rotational Speed: 10500
         Firmware Revision: HPD3
         Serial Number: W0K0T2XW
         Model: HP      EG000300JWEBF
         Current Temperature (C): 31
         Maximum Temperature (C): 48
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         Drive Authentication Status: OK
         Carrier Application Version: 11
         Carrier Bootloader Version: 6
         Sanitize Erase Supported: True
         Sanitize Estimated Max Erase Time: 0 hour(s)58 minute(s)
         Unrestricted Sanitize Supported: True


   Array: B
      Interface Type: SAS
      Unused Space: 0  MB (0.0%)
      Used Space: 1.8 TB (100.0%)
      Status: OK
      Array Type: Data 


      Logical Drive: 2
         Size: 931.5 GB
         Fault Tolerance: 1
         Heads: 255
         Sectors Per Track: 32
         Cylinders: 65535
         Strip Size: 256 KB
         Full Stripe Size: 256 KB
         Status: OK
         Caching:  Enabled
         Unique Identifier: 600508B1001CC423359CCBDA99241738
         Disk Name: /dev/sdb 
         Mount Points: /home/bigdisk 931.5 GB Partition Number 2
         OS Status: LOCKED
         Logical Drive Label: 0626A4875001438024F9CF80 5843
         Mirror Group 1:
            physicaldrive 2I:1:7 (port 2I:box 1:bay 7, SAS, 1 TB, OK)
         Mirror Group 2:
            physicaldrive 2I:1:8 (port 2I:box 1:bay 8, SAS, 1 TB, OK)
         Drive Type: Data
         LD Acceleration Method: Controller Cache

      physicaldrive 2I:1:7
         Port: 2I
         Box: 1
         Bay: 7
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 1 TB
         Drive exposed to OS: False
         Native Block Size: 512
         Rotational Speed: 7200
         Firmware Revision: HPD1
         Serial Number: S4701YDK0000K5490QZ8
         Model: HP      MM1000JFJTH
         Current Temperature (C): 27
         Maximum Temperature (C): 50
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         Drive Authentication Status: OK
         Carrier Application Version: 11
         Carrier Bootloader Version: 6
         Sanitize Erase Supported: True
         Sanitize Estimated Max Erase Time: 3 hour(s)0 minute(s)
         Unrestricted Sanitize Supported: False

      physicaldrive 2I:1:8
         Port: 2I
         Box: 1
         Bay: 8
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 1 TB
         Drive exposed to OS: False
         Native Block Size: 512
         Rotational Speed: 7200
         Firmware Revision: HPD1
         Serial Number: S4718ZQA0000K7250N7E
         Model: HP      MM1000JFJTH
         Current Temperature (C): 24
         Maximum Temperature (C): 48
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         Drive Authentication Status: OK
         Carrier Application Version: 11
         Carrier Bootloader Version: 6
         Sanitize Erase Supported: True
         Sanitize Estimated Max Erase Time: 3 hour(s)0 minute(s)
         Unrestricted Sanitize Supported: False


   unassigned

      physicaldrive 1I:1:3
         Port: 1I
         Box: 1
         Bay: 3
         Status: OK
         Drive Type: Unassigned Drive
         Interface Type: Solid State SATA
         Size: 480.1 GB
         Drive exposed to OS: False
         Native Block Size: 4096
         Firmware Revision: 4IYVHPG2
         Serial Number: PHYS744501CY480BGN
         Model: ATA     VK000480GWJPE
         SATA NCQ Capable: True
         SATA NCQ Enabled: True
         Current Temperature (C): 21
         Maximum Temperature (C): 44
         Usage remaining: 99.96%
         Power On Hours: 7749
         Estimated Life Remaining based on workload to date: 806864 days
         SSD Smart Trip Wearout: False
         PHY Count: 1
         PHY Transfer Rate: 6.0Gbps
         Drive Authentication Status: OK
         Carrier Application Version: 11
         Carrier Bootloader Version: 6
         Sanitize Erase Supported: True
         Sanitize Estimated Max Erase Time: 0 minute(s) 46 second(s)
         Unrestricted Sanitize Supported: True
```

### Expected behavior

No parsing error

### Steps to reproduce

1. Use HP system with smart array configured with drives that are not assigned to an array

### Installation method

kickstart.sh

### System info

```shell
Linux percity6.tod 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.41.0-318-nightly
    Installation Type __________________________________________ : kickstart-build
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ :  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 3.10.0-1160.6.1.el7.x86_64
    Operating System ___________________________________________ : CentOS Linux
    Operating System ID ________________________________________ : centos
    Operating System ID Like ___________________________________ : rhel fedora
    Operating System Version ___________________________________ : 7 (Core)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 40
    CPU Frequency ______________________________________________ : 2200000000
    CPU Architecture ___________________________________________ : 67342548992
    RAM Bytes __________________________________________________ : 1300137777152
    Disk Capacity ______________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : NO (none)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : NO
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (bundled)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

**Comment by ilyam8** [comment]
Hi, @nadalizadeh. Should be fixed in #15793.

**Comment by nadalizadeh** [comment]
The patch works like a charm, thanks

**Comment by ilyam8** [comment]
@nadalizadeh I checked the [sample output shared in 2019](https://github.com/netdata/netdata/pull/7181#issuecomment-545700797), it was `Unassigned`, e.g.

```
   Unassigned

      physicaldrive 1I:1:1
         Port: 1I
         Box: 1
         Bay: 1
         Status: OK
         Drive Type: Unassigned Drive
         Interface Type: SATA
         Size: 250 GB
         Drive exposed to OS: False
```


For some reason they decided to change it.
