### ISSUE TITLE
[Bug]: Netdata crashes on a RPi host in MQTT

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#16117]
### Bug description

Updated RPi to debian12 and Netdata in a crash loop 🤷 There is a problem with internet connection on that RPi (not sure if it has something to do with the problem, just sharing).

Coredump:

```c
Program terminated with signal SIGBUS, Bus error.
#0  0x0040db68 in mqtt_ng_get_stats (client=0x2b68d40, stats=0xdba4e7b0, stats@entry=0xdba4e7a8) at mqtt_websockets/src/mqtt_ng.c:2190
2190	        stats->tx_bytes_queued += frag->len - frag->sent;
[Current thread is 1 (Thread 0xdba4f100 (LWP 31621))]
(gdb) bt
#0  0x0040db68 in mqtt_ng_get_stats (client=0x2b68d40, stats=0xdba4e7b0, stats@entry=0xdba4e7a8) at mqtt_websockets/src/mqtt_ng.c:2190
#1  0x00408980 in mqtt_wss_get_stats (client=0x2b08b88) at mqtt_websockets/src/mqtt_wss_client.c:1124
#2  0x003151d4 in aclk_stats_main_thread (ptr=0x0) at aclk/aclk_stats.c:424
#3  0x00080608 in netdata_thread_init (ptr=0x0) at libnetdata/threads/threads.c:277
#4  0xf76a18e0 in start_thread (arg=0xdba4f100) at pthread_create.c:442
#5  0xf7720a0c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:74 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

```c
#0  mqtt_ng_next_to_send (client=0x15a94c8) at mqtt_websockets/src/mqtt_ng.c:1923
#1  try_send_all (client=client@entry=0x15a94c8) at mqtt_websockets/src/mqtt_ng.c:1985
#2  0x004127cc in mqtt_ng_sync (client=0x15a94c8) at mqtt_websockets/src/mqtt_ng.c:2154
#3  0x0040c514 in handle_mqtt_internal (client=0x1549310) at mqtt_websockets/src/mqtt_wss_client.c:848
#4  mqtt_wss_service (client=client@entry=0x1549310, timeout_ms=<optimized out>, timeout_ms@entry=1000) at mqtt_websockets/src/mqtt_wss_client.c:1007
#5  0x00318134 in handle_connection (client=0x1549310) at aclk/aclk.c:332
#6  aclk_main (ptr=0x1549310) at aclk/aclk.c:856
#7  0x00080988 in netdata_thread_init (ptr=0x0) at libnetdata/threads/threads.c:277
#8  0xf74218e0 in start_thread (arg=0xe2134100) at pthread_create.c:442
#9  0xf74a0a0c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:74 from /lib/arm-linux-gnueabihf/libc.so.6
```
### Expected behavior

No crash.

### Steps to reproduce

Not sure, Netdata crashes on multiple RPi hosts. @stelfrag @underhood I can provide access.

### Installation method

kickstart.sh

### System info

```shell
Linux rpi4b-1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="12"
/etc/os-release:VERSION="12 (bookworm)"
/etc/os-release:VERSION_CODENAME=bookworm
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.42.0-244-g366eac56a
    Installation Type __________________________________________ : custom
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ :  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -g' 'LDFLAGS='
Default Directories:
    User Configurations ________________________________________ : /opt/netdata/etc/netdata
    Stock Configurations _______________________________________ : /opt/netdata/usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /opt/netdata/var/cache/netdata
    Permanent Databases ________________________________________ : /opt/netdata/var/lib/netdata
    Plugins ____________________________________________________ : /opt/netdata/usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /opt/netdata/usr/share/netdata/web
    Log Files __________________________________________________ : /opt/netdata/var/log/netdata
    Lock Files _________________________________________________ : /opt/netdata/var/lib/netdata/lock
    Home _______________________________________________________ : /opt/netdata/var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.1.21-v8+
    Operating System ___________________________________________ : Raspbian GNU/Linux
    Operating System ID ________________________________________ : raspbian
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 12 (bookworm)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 4
    CPU Frequency ______________________________________________ : 1500000000
    CPU Architecture ___________________________________________ : 8007626752
    RAM Bytes __________________________________________________ : 62209916928
    Disk Capacity ______________________________________________ : aarch64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (lz4)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : NO
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (bundled)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

**Comment by underhood** [comment]
@ilyam8 just to ensure I have correct picture. Netdata was running OK on this system before upgrade to deb 12?

**Comment by ilyam8** [comment]
Likely a duplicate of #14696
