### ISSUE TITLE
[Bug]: Mobile App keeps crashing after login

### ISSUE THREAD

**Issue by poqdavid** [netdata/netdata#16722]
### Bug description

Once you login into the app it just keeps crashing on the startup

### Expected behavior

it should load normally

### Steps to reproduce

1. Enter email and press login
2. Open the link from the email on the phone
3. Start app
...

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

```log
time: 1704302661698
msg: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
stacktrace: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at cloud.netdata.android.ui.home.fragment.ChooseSpaceFragment.observeGetSilencingRules$lambda-7(ChooseSpaceFragment.kt:327)
	at cloud.netdata.android.ui.home.fragment.ChooseSpaceFragment.$r8$lambda$ZD_pTJmwHN3rD2T-nNTOYp5g5v4(Unknown Source:0)
	at cloud.netdata.android.ui.home.fragment.ChooseSpaceFragment$$ExternalSyntheticLambda1.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

**Comment by poqdavid** [comment]
Sorry I posted this here because I couldn't find a place for the app

**Comment by sashwathn** [comment]
@poqdavid : Thanks for reporting the issue. We are working on a fix.

**Comment by ilyam8** [comment]
@sashwathn If we are going to use netdata/netdata for bugs/feature requests for the mobile app, we need to create separate bug reports/feature request templates.
