### ISSUE TITLE
[Bug]: HP SSA Collector panics on drive cage information

### ISSUE THREAD

**Issue by Metric-Void** [netdata/netdata#17293]
### Bug description

```
netdata@REDACTED:/usr/libexec/netdata/plugins.d$ ./python.d.plugin hpssa debug trace
2024-03-31 19:50:10: python.d INFO: plugin[main] : using python v3
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : looking for '/etc/netdata/python.d.conf'
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : looking for '/usr/lib/netdata/conf.d/python.d.conf'
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2024-03-31 19:50:10: python.d WARNING: plugin[main] : 'pythond-jobs-statuses.json' was not found
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : [hpssa] loaded module source : '/usr/libexec/netdata/python.d/hpssa.chart.py'
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : [hpssa] looking for 'hpssa.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : [hpssa] loading '/etc/netdata/python.d/hpssa.conf'
2024-03-31 19:50:10: python.d DEBUG: plugin[main] : [hpssa] '/etc/netdata/python.d/hpssa.conf' is loaded
2024-03-31 19:50:10: python.d INFO: plugin[main] : [hpssa] built 1 job(s) configs
2024-03-31 19:50:10: python.d DEBUG: hpssa[hpssa] : Executing command '/usr/bin/sudo -n -l /usr/sbin/ssacli'
2024-03-31 19:50:10: python.d INFO: hpssa[hpssa] : Command: ['/usr/bin/sudo', '-n', '/usr/sbin/ssacli', 'ctrl', 'all', 'show', 'config', 'detail']
2024-03-31 19:50:10: python.d DEBUG: hpssa[hpssa] : Executing command '/usr/bin/sudo -n /usr/sbin/ssacli ctrl all show config detail'
2024-03-31 19:50:11: python.d ERROR: hpssa[hpssa] : Cannot parse line: Internal Drive Cage at Port 1I, Box 1 (Index 0), OK
2024-03-31 19:50:11: python.d ERROR: hpssa[hpssa] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 307, in get_adapters
    adapters = HPSSA(self._get_raw_data(command=self.cmd)).adapters
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 121, in __init__
    self.parse()
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 152, in parse
    self.adapters.append(self.parse_adapter(**match.groupdict()))
  File "/usr/libexec/netdata/python.d/hpssa.chart.py", line 208, in parse_adapter
    raise HPSSAException('Cannot parse line: {}'.format(line))
pythond_hpssa.HPSSAException: Cannot parse line: Internal Drive Cage at Port 1I, Box 1 (Index 0), OK

2024-03-31 19:50:11: python.d INFO: hpssa[hpssa] : Discovered adapters: []
2024-03-31 19:50:11: python.d ERROR: hpssa[hpssa] : No adapters discovered
2024-03-31 19:50:11: python.d INFO: plugin[main] : hpssa[hpssa] : check failed
2024-03-31 19:50:11: python.d INFO: plugin[main] : no jobs to serve
2024-03-31 19:50:11: python.d INFO: plugin[main] : exiting from main...
```

HP SSA Output:
```
netdata@REDACTED:/usr/libexec/netdata/plugins.d$ sudo ssacli ctrl all show config detail

Smart Array P410i in Slot 0 (Embedded)
   Bus Interface: PCI
   Slot: 0
   Serial Number: REDACTED
   Controller Status: OK
   Hardware Revision: C
   Firmware Version: 3.00
   Firmware Supports Online Firmware Activation: False
   Rebuild Priority: Medium
   Surface Scan Delay: 3 secs
   Surface Scan Mode: Idle
   Parallel Surface Scan Supported: No
   Elevator Sort: Enabled
   Wait for Cache Room: Disabled
   Surface Analysis Inconsistency Notification: Disabled
   Post Prompt Timeout: 15 secs
   Cache Board Present: False
   Drive Write Cache: Disabled
   Total Cache Size: 0.0
   SATA NCQ Supported: True
   Number of Ports: 2 Internal only
   Encryption: Not Set
   Driver Name: hpsa
   Driver Version: 3.4.20
   WWN Port: REDACTED
   Driver Supports SSD Smart Path: True
   PCI Address (Domain:Bus:Device.Function): 0000:03:00.0
   Port Max Phy Rate Limiting Supported: False
   Host Serial Number: USE023N2K5
   Sanitize Erase Supported: False
   Primary Boot Volume: None
   Secondary Boot Volume: None
   SPDM Supports Get Slot Certificate Chain: no
   SPDM Supports Get Controller Info       : no
   SPDM Supports Get Slot Info             : no
   SPDM Supports Set Import Certificate    : no
   SPDM Supports Set Invalidate Slot       : no
   Surface Scan Completion Supported: False
   Persistent Event Log Policy Change Supported: False
   UEFI Health Reporting Mode Supported: False




   Internal Drive Cage at Port 1I, Box 1 (Index 0), OK

      Drive Bays: 4
      Port: 1I
      Box: 1
      Box Index: 0
      Location: Internal

   Physical Drives
      None attached



   Internal Drive Cage at Port 2I, Box 1 (Index 1), OK

      Drive Bays: 4
      Port: 2I
      Box: 1
      Box Index: 1
      Location: Internal

   Physical Drives
      physicaldrive 2I:1:5 (port 2I:box 1:bay 5, SAS HDD, 300 GB, OK)
      physicaldrive 2I:1:6 (port 2I:box 1:bay 6, SAS HDD, 300 GB, OK)
      physicaldrive 2I:1:7 (port 2I:box 1:bay 7, SAS HDD, 300 GB, OK)
      physicaldrive 2I:1:8 (port 2I:box 1:bay 8, SAS HDD, 300 GB, Predictive Failure)


   Port Name: 1I
         Port ID: 0
         Port Connection Number: 0
         SAS Address: REDACTED
         Port Location: Internal
         Port Phy Count: 4

   Port Name: 2I
         Port ID: 1
         Port Connection Number: 1
         SAS Address: REDACTED
         Port Location: Internal
         Port Phy Count: 4

   Array: A
      Interface Type: SAS
      Unused Space: 0 MB (0.00%)
      Used Space: 1.09 TB (100.00%)
      Status: OK
      Array Type: Data
      Smart Path: disable


      Logical Drive: 1
         Size: 558.73 GB
         Fault Tolerance: 1+0
         Heads: 255
         Sectors Per Track: 32
         Cylinders: 65535
         Strip Size: 128 KB
         Full Stripe Size: 256 KB
         Status: OK
         Unrecoverable Media Errors: None
         Caching:  Disabled
         Last Surface Scan Completed: False
         Unique Identifier: REDACTED
         Disk Name: /dev/sda
         Mount Points: 2.0 GiB Partition   2 /boot
         Disk Partition Information
            Partition   2: Basic, 2.0 GiB, /boot
         Logical Drive Label: REDACTED
         Mirror Group 1:
            physicaldrive 2I:1:5 (port 2I:box 1:bay 5, SAS HDD, 300 GB, OK)
            physicaldrive 2I:1:6 (port 2I:box 1:bay 6, SAS HDD, 300 GB, OK)
         Mirror Group 2:
            physicaldrive 2I:1:7 (port 2I:box 1:bay 7, SAS HDD, 300 GB, OK)
            physicaldrive 2I:1:8 (port 2I:box 1:bay 8, SAS HDD, 300 GB, Predictive Failure)
         Drive Type: Data
         LD Acceleration Method: All disabled


      physicaldrive 2I:1:5
         Port: 2I
         Box: 1
         Bay: 5
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 300 GB
         Drive exposed to OS: False
         Logical/Physical Block Size: 512/512
         Rotational Speed: 10000
         Firmware Revision: HPD5
         Serial Number: REDACTED
         WWID: REDACTED
         Model: HP      EG0300FBLSE
         Current Temperature (C): 27
         Maximum Temperature (C): 39
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         PHY Physical Link Rate: Unknown, Unknown
         PHY Maximum Link Rate: Unknown, Unknown
         Sanitize Erase Supported: False
         Shingled Magnetic Recording Support: None
         Multi-Actuator Drive: False

      physicaldrive 2I:1:6
         Port: 2I
         Box: 1
         Bay: 6
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 300 GB
         Drive exposed to OS: False
         Logical/Physical Block Size: 512/512
         Rotational Speed: 10000
         Firmware Revision: HPD5
         Serial Number: REDACTED
         WWID: REDACTED
         Model: HP      EG0300FBLSE
         Current Temperature (C): 26
         Maximum Temperature (C): 39
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         PHY Physical Link Rate: Unknown, Unknown
         PHY Maximum Link Rate: Unknown, Unknown
         Sanitize Erase Supported: False
         Shingled Magnetic Recording Support: None
         Multi-Actuator Drive: False

      physicaldrive 2I:1:7
         Port: 2I
         Box: 1
         Bay: 7
         Status: OK
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 300 GB
         Drive exposed to OS: False
         Logical/Physical Block Size: 512/512
         Rotational Speed: 10500
         Firmware Revision: HPD9
         Serial Number: REDACTED
         WWID: REDACTED
         Model: HP      EG0300FCVBF
         Current Temperature (C): 28
         Maximum Temperature (C): 39
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         PHY Physical Link Rate: Unknown, Unknown
         PHY Maximum Link Rate: Unknown, Unknown
         Sanitize Erase Supported: False
         Shingled Magnetic Recording Support: None
         Multi-Actuator Drive: False

      physicaldrive 2I:1:8
         Port: 2I
         Box: 1
         Bay: 8
         Status: Predictive Failure
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 300 GB
         Drive exposed to OS: False
         Logical/Physical Block Size: 512/512
         Rotational Speed: 10000
         Firmware Revision: HPD5
         Serial Number: REDACTED
         WWID: REDACTED
         Model: HP      EG0300FBLSE
         Current Temperature (C): 29
         Maximum Temperature (C): 42
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         PHY Physical Link Rate: Unknown, Unknown
         PHY Maximum Link Rate: Unknown, Unknown
         Sanitize Erase Supported: False
         Shingled Magnetic Recording Support: None
         Multi-Actuator Drive: False
```

### Expected behavior

`ssacli` data should be collected.

### Steps to reproduce

1. Install netdata on an HP system with an HP RAID adapter
2. Enable hpssa

### Installation method

kickstart.sh

### System info

```shell
Linux REDACTED 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.45.1
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ :
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /var/lib/netdata/www
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.15.0-43-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.1 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 8
    CPU Frequency ______________________________________________ : 2666000000
    RAM Bytes __________________________________________________ : 25193992192
    Disk Capacity ______________________________________________ : 599932844032
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : YES
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : YES
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

**Comment by Metric-Void** [comment]
Some additional digging on a similar machine seems to indicate `(Index 0)` to be the cause. An `ssacli` output without `(Index 0)` was read without problems.
