### ISSUE TITLE
Traceback issues and exception handling

### ISSUE THREAD

**Issue by mirceachira** [netdata/netdata#3056]
Hello,
It seems as if netdata disables python's exception handling, am I missing something? Is this the expected behaviour?
While debugging my custom chart I noticed that the traceback is weird?
```        
def _get_data(self):
            ...
            try:
                response_bytes = urllib.request.urlopen(url).read()
            except URLError:
                self.alert('URLError on port {}, url {}'.format(port, url))
                continue
 
```
Traceback when running ./python.d.plugin 1 debug trace my_costum_chart:
```
2017-11-23 12:16:20: python.d CRITICAL: scrapy: scrapy: URLError on port 5028, url http://localhost:5028/crawler/stats
2017-11-23 12:16:20: python.d CRITICAL: scrapy: scrapy: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/scrapy.chart.py", line 1234, in _get_data
    url, self.json_data, timeout=0.001
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by l2isbad** [comment]
[trace flag](https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L377-L378)

[add_traceback function](https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/loggers.py#L52-L65)

is decorator for 
https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/loggers.py#L175-L183

**Comment by l2isbad** [comment]
I answered the question. @mirceachira if something is not clear feel free to reopen
