### ISSUE TITLE
Ceph - No JSON object could be decoded

### ISSUE THREAD

**Issue by garyx** [netdata/netdata#3563]
I'm trying to enable ceph monitoring with the new setup but I am hitting a snag. I have added and made sure the netdata user can read the config/keyfile. Made sure rados is installed. The netdata user can query the ceph cluster just fine and does return data with "--format json"

But I get this error below and I am not sure from what. Am I missing something that needs to be installed. 

Running ceph version 10.2.9 

netdata 1.9.0-679-g186d1628_rolling

```
2018-03-20 15:43:05: python.d INFO: plugin: main: Using python 2
2018-03-20 15:43:05: python.d DEBUG: plugin: main: module load source: 'ceph' => [OK]
2018-03-20 15:43:05: python.d DEBUG: plugin: main: module load config: 'ceph' => [OK]
2018-03-20 15:43:05: python.d DEBUG: plugin: main: job initialization: 'ceph ceph' => ['OK']
2018-03-20 15:43:05: python.d DEBUG: plugin: main: module status: 'ceph' => [OK] (jobs: 1)
**2018-03-20 15:43:05: python.d ERROR: ceph: ceph: check() unhandled exception: No JSON object could be decoded**
2018-03-20 15:43:05: python.d INFO: ceph: ceph: check() => [FAILED]
2018-03-20 15:43:05: python.d INFO: plugin: main: FINISHED
```

**Comment by ktsaou** [comment]
@lets00 please check this.

**Comment by cjd9023** [comment]
2018-03-27 10:34:30: python.d INFO: bind_rndc: bind_rndc: check() => [FAILED]
2018-03-27 10:34:30: python.d ERROR: ceph: ceph: check() unhandled exception: No JSON object could be decoded

v1.9.0-657-gf78f947_rolling
ceph 10.2.10

**Comment by lets00** [comment]
Hi @garyx ,
Thank you for the comment. I'll see in this Friday(27/03). Probably, there is an error in JSON parser that I not saw.

**Comment by lets00** [comment]
Hi @garyx and @cjd9023 , sorry for late.
I recreate my environment and I did not found this error. This error maybe has happening in JSON module.
Let's go to the tests:
**First tests:**

Can you run this commands:
```
$ sudo su -s /bin/bash netdata
$ ceph df --format json
$ ceph osd df --format json
$ ceph osd perf --format json
$ ceph osd pool stats --format json
``` 
If any command fails (show error in output), maybe this is the source of problem and I can try to fix it.

**Second test:**
Please, try to run this command:

```
$ sudo su -s /bin/bash netdata
$ python
>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
>>> cluster.connect()
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
```
This command must return some like this:
```
{u'pools': [{u'stats': {u'objects': 10, u'bytes_used': 1048576000, u'max_avail': 24173815808, u'percent_used': 1.43, u'kb_used': 1024000}, u'name': u'asdf', u'id': 4}], u'stats': {u'total_used_bytes': 7628685312, u'total_bytes': 85475639296, u'total_avail_bytes': 77846953984}}
```

If this is working ok, You can test this commands:
```
>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
>>> cluster.connect()
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd perf', 'format': 'json'}), '')[1])
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd pool stats', 'format': 'json'}), '')[1])
```

**Comment by ktsaou** [comment]
Closing due to inactivity.
Feel free to post if the issue remains.

**Comment by briancline** [comment]
I am seeing this issue as well. Netdata was successfully gathering Ceph information directly after I installed it, however after updating `update_every` in restarting the netdata service, it no longer works. I see this in the error log:

```
2018-06-19 23:46:19: python.d ERROR: ceph: ceph: check() unhandled exception: No JSON object could be decoded
2018-06-19 23:46:19: python.d INFO: ceph: ceph: check() => [FAILED]
```

Running the above commands from @lets00, I get good JSON data back for each of them. At first, it seemed that my decreasing `update_every` was the problem, but just to be certain netdata could execute these statements, I copied the above Python statements (both blocks) into a single .py file, ran it, and noticed sometimes I got an error, other times not. This JSON error was actually happening intermittently:

```
# for ii in {1..10}; do time sudo -u netdata python ceph.py; done

real	0m0.207s
user	0m0.068s
sys	0m0.084s

real	0m0.144s
user	0m0.072s
sys	0m0.032s
Traceback (most recent call last):
  File "ceph.py", line 9, in <module>
    json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

real	0m0.140s
user	0m0.076s
sys	0m0.028s

real	0m0.276s
user	0m0.072s
sys	0m0.100s
Traceback (most recent call last):
  File "ceph.py", line 9, in <module>
    json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

real	0m0.168s
user	0m0.072s
sys	0m0.040s

real	0m0.230s
user	0m0.088s
sys	0m0.028s
Traceback (most recent call last):
  File "ceph.py", line 9, in <module>
    json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

real	0m0.173s
user	0m0.076s
sys	0m0.032s

real	0m0.174s
user	0m0.060s
sys	0m0.060s

real	0m0.221s
user	0m0.084s
sys	0m0.048s
Traceback (most recent call last):
  File "ceph.py", line 9, in <module>
    json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

real	0m0.165s
user	0m0.084s
sys	0m0.032s
```

Apparently, Ceph is intermittently sending back bad JSON with `nan` and `-nan` values, which isn't really valid (they sort of are in JavaScript, but typically it's `NaN` as `nan` is considered undefined -- or at least in v8). Here is a snippet of the bad section of JSON:
```
        {
            "id": 5,
            "name": "osd.5",
            "type": "osd",
            "type_id": 0,
            "crush_weight": 0.000992,
            "depth": 2,
            "reweight": 0.0,
            "kb": 0,
            "kb_used": 0,
            "kb_avail": 0,
            "utilization": -nan,
            "var": -nan,
            "pgs": 0
        },
```

Two things to note:
* If you are in the middle of upgrading your cluster, or you may have varying ceph monitor versions for other reasons, that _could_ cause similar-looking issues.
* In my case, the root cause was my crush map still containing an old, long-defunct osd even though it had been completely drained -- I probably just forgot to remove it altogether. After instructing ceph to remove the osd, I get consistently good JSON.

Hopefully this helps any other poor soul who sees this behavior and starts googling.

**Comment by lets00** [comment]
Good observation @briancline. In this weekend, I will see if I can add some except case based on your observation.

**Comment by cakrit** [comment]
@ilyam8 please check this one out, it was closed and we missed some updates.

**Comment by ilyam8** [comment]
@lets00 i am a little bit out of the loop on this, can you help?

**Comment by ilyam8** [comment]
i added `high priority` because the bug is pretty old and still not fixed. This is wrong.

**Comment by ilyam8** [comment]
@cjd9023 
@briancline 

> In my case, the root cause was that my crush map still contained an old, long-defunct osd even though it had been completely drained -- I probably just forgot to remove it altogether. After instructing ceph to remove the osd, I get consistently good JSON.

So should we fix that `nan` thing adding replace as @cjd9023 did

> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1].replace('-nan','"-nan"'))

Or we should warn a user that something is wrong?

**Comment by cakrit** [comment]
Better do the replacement. The JSON needs to be valid no matter what.

**Comment by ilyam8** [comment]
I mean maybe replacement will shadow some problem. This assumption based on

> In my case, the root cause was that my crush map still contained an old, long-defunct osd even though it had been completely drained -- I probably just forgot to remove it altogether. After instructing ceph to remove the osd, I get consistently good JSON.

But i am not sure, not a ceph user

**Comment by cjd9023** [comment]
my cluster has 360 osds(36 servers )，but it's so normal one of servers got down with hardware issue,afster 5 minutes or more, so it's become  360 osds:  350 up 350 in;  may be it take 1 days or more to fix hardware problem.
in this state , follow command run fail with error
 json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])

**Comment by ilyam8** [comment]
@cjd9023 

i see you proposed solution and it works, right

> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1].replace('-nan','"-nan"'))

are you willing to make a PR?

**Comment by cjd9023** [comment]
/opt/netdata/netdata-plugins/python.d/ceph.chart.py
i chage this function with one line:

before:

314     def _get_osd_df(self):
315         """
316         Get ceph osd df output
317         :return: ceph osd df --format json
318         """
319         return json.loads(self.cluster.mon_command(json.dumps({
320             'prefix': 'osd df',
321             'format': 'json'
322         }), '')[1]

after:

314     def _get_osd_df(self):
315         """
316         Get ceph osd df output
317         :return: ceph osd df --format json
318         """
319         return json.loads(self.cluster.mon_command(json.dumps({
320             'prefix': 'osd df',
321             'format': 'json'
322         }), '')[1].replace('-nan','"-nan"'))

it's work for my cluster, but i'm not sure it can fix ............ u know!

**Comment by ilyam8** [comment]
```python
Help on built-in function mon_command:

mon_command(...)
    Rados.mon_command(self, cmd, inbuf, timeout=0, target=None)
    
    mon_command[_target](cmd, inbuf, outbuf, outbuflen, outs, outslen)
    returns (int ret, string outbuf, string outs)
(END)

```

2nd parameter in return is `string, `.replace('-nan','"-nan"')` should be safe. I will do a PR.
