### ISSUE TITLE
Issues loading module's snmp config

### ISSUE THREAD

**Issue by lordc1ph3r** [netdata/netdata#3905]
Hello, I just installed Netdata, and it is working perfectly; I want to connect a switch so it can monitor it through SNMP.
This is the error I get after running `/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp`

`2018-06-28 17:15:57: node.d.plugin: ERROR: Cannot load module's snmp config from /usr/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf exception: SyntaxError: Unexpected token c in JSON at position 307, using internal defaults.
DISABLE`

I tried the same code but added "debug" at the end and got this:

`2018-06-28 17:43:35: node.d.plugin: DEBUG: DEBUG enabled
2018-06-28 17:43:35: node.d.plugin: DEBUG: loading module /usr/libexec/netdata/plugins.d/../node.d/snmp.node.js
2018-06-28 17:43:35: node.d.plugin: DEBUG: loaded
2018-06-28 17:43:35: node.d.plugin: DEBUG: loaded module snmp from /usr/libexec/netdata/plugins.d/../node.d/snmp.node.js
2018-06-28 17:43:35: node.d.plugin: DEBUG: loading module's snmp config /usr/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf
2018-06-28 17:43:35: node.d.plugin: ERROR: Cannot load module's snmp config from /usr/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf exception: SyntaxError: Unexpected token c in JSON at position 307, using internal defaults.
2018-06-28 17:43:35: node.d.plugin: DEBUG: SyntaxError: Unexpected token c in JSON at position 307
    at JSON.parse (<anonymous>)
    at findModules (/usr/libexec/netdata/plugins.d/node.d.plugin:233:35)
    at Object.<anonymous> (/usr/libexec/netdata/plugins.d/node.d.plugin:271:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
2018-06-28 17:43:35: node.d.plugin: DEBUG: Configuring module snmp
2018-06-28 17:43:35: node.d.plugin: DEBUG: snmp: configuring (update_every: 1)...
2018-06-28 17:43:35: node.d.plugin: DEBUG: snmp: configured, reporting 0 eligible services.
2018-06-28 17:43:35: node.d.plugin: DEBUG: snmp: configuration finish callback called from configure().
2018-06-28 17:43:35: node.d.plugin: DEBUG: Configured module snmp
2018-06-28 17:43:35: node.d.plugin: DEBUG: Configuring module snmp reports 0 eligible services.
2018-06-28 17:43:35: node.d.plugin: DEBUG: started, services: []`

What could be the problem?

**Comment by cakrit** [comment]
Hi @lordc1ph3r and apologies for the delayed response. Do you still face this issue?
