### ISSUE TITLE
RabbitMQ Plugin Error with HTTPS

### ISSUE THREAD

**Issue by tomobrien** [netdata/netdata#4471]
##### Bug report summary

/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace rabbitmq
2018-10-23 20:05:54: python.d INFO: plugin: main: Using python 2
2018-10-23 20:05:54: python.d DEBUG: plugin: main: module load source: 'rabbitmq' => [OK]
2018-10-23 20:05:54: python.d DEBUG: plugin: main: module load config: 'rabbitmq' => [OK]
2018-10-23 20:05:54: python.d DEBUG: plugin: main: job initialization: 'rabbitmq localrabbit' => ['OK']
2018-10-23 20:05:54: python.d DEBUG: plugin: main: module status: 'rabbitmq' => [OK] (jobs: 1)
2018-10-23 20:05:54: python.d ERROR: rabbitmq: localrabbit: Url: https://127.0.0.1:13355/api/nodes. Error: [Errno 2] No such file or directory
2018-10-23 20:05:54: python.d ERROR: rabbitmq: localrabbit: Url: https://127.0.0.1:13355/api/overview. Error: [Errno 2] No such file or directory
2018-10-23 20:05:54: python.d ERROR: rabbitmq: localrabbit: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 78, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 101, in _get_raw_data_with_status
    redirect=redirect)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 246, in ssl_wrap_socket
    raise SSLError(e)
SSLError: [Errno 2] No such file or directory

2018-10-23 20:05:54: python.d ERROR: rabbitmq: localrabbit: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 78, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 101, in _get_raw_data_with_status
    redirect=redirect)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 246, in ssl_wrap_socket
    raise SSLError(e)
SSLError: [Errno 2] No such file or directory

##### OS / Environment
netdata-1.10
Scientific Linux release 7.1 

##### Component Name
rabbitmq

##### Steps To Reproduce
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace rabbitmq

/etc/netdata/python.d/rabbitmq.conf
```
localrabbit:
    host: 'localhost'
    port: '13355'
    scheme: 'https'
    user: 'someuser'
    pass: 'somepassword'
```

##### Expected behavior
I would expect it to connect to RabbitMQ and collect metrics.

Thank you for any and all help.

**Comment by paulfantom** [comment]
Are you using self-signed SSL/TLS certificate? Have you tried adding `tls_verify: false` to `rabbitmq.conf` like:
```
localrabbit:
    host: 'localhost'
    port: '13355'
    scheme: 'https'
    user: 'someuser'
    pass: 'somepassword'
    tls_verify: false
```
?

**Comment by l2isbad** [comment]
Hm, `tls_verify: false` is default.

I checked and it works for me.

What i did:
1. install `rabbitmq` 
2. enabl management plugin
3. generate certs, add
```
   {listener, [{port,     15672},
               {ip,       "127.0.0.1"},
               {ssl,      true},
               {ssl_opts, [{cacertfile, "/opt/cacert.pem"},
                           {certfile,   "/opt/cert.pem"},
                           {keyfile,    "/opt/key.pem"}]}]}

``` 
to the `rabbitmq.conig`
4. restart `netdata.service`

all works

**Comment by tomobrien** [comment]
First, thank you both for your help!

So, with some stracing here's what I found:

[pid 39787] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = -1 ENOENT (No such file or directory)

I had tried setting an environment variable to where the rabbit CA root is with

export REQUESTS_CA_BUNDLE=/etc/rabbitmq/cert/my_CA_Root.crt

Once I copied /etc/rabbitmq/cert/my_CA_Root.crt to /etc/ssl/certs/ca-certificates.crt it worked.  Do you folks know how I might override that in the /etc/netdata/python.d/rabbitmq.conf or elsewhere?

**Comment by tomobrien** [comment]
So just putting the ca root in /etc/ssl/certs/ with mode 644 solves it all for me.  I can adjust permissions as needed.   Thank you for your help again.
