### ISSUE TITLE
smartd_log check() unhandled exception: 'list' object has no attribute 'clear'

### ISSUE THREAD

**Issue by ScrumpyJack** [netdata/netdata#4583]
##### Bug report summary

When running debug for smard_log, the following error occurs

```
# /usr/bin/python /opt/netdata/plugins.d/python.d.plugin 1 debug trace smartd_log
2018-11-08 13:36:21: python.d INFO: plugin: main: Using python 2
2018-11-08 13:36:21: python.d DEBUG: plugin: main: loading '/usr/local/etc/netdata/python.d.conf'
2018-11-08 13:36:21: python.d ERROR: plugin: main: cannot load '/usr/local/etc/netdata/python.d.conf': [Errno 2] No such file or directory: '/usr/local/etc/netdata/python.d.conf'. Will try stock version.
2018-11-08 13:36:21: python.d DEBUG: plugin: main: loading '/opt/netdata/lib/netdata/conf.d/python.d.conf'
2018-11-08 13:36:21: python.d ERROR: plugin: main: cannot load '/opt/netdata/lib/netdata/conf.d/python.d.conf': [Errno 2] No such file or directory: '/opt/netdata/lib/netdata/conf.d/python.d.conf'
2018-11-08 13:36:21: python.d DEBUG: plugin: main: module load source: 'smartd_log' => [OK]
2018-11-08 13:36:21: python.d DEBUG: plugin: main: loading '/usr/local/etc/netdata/python.d/smartd_log.conf'
2018-11-08 13:36:21: python.d ERROR: plugin: main: cannot load '/usr/local/etc/netdata/python.d/smartd_log.conf' : [Errno 2] No such file or directory: '/usr/local/etc/netdata/python.d/smartd_log.conf'. Will try stock version.
2018-11-08 13:36:21: python.d DEBUG: plugin: main: loading '/opt/netdata/lib/netdata/conf.d/python.d/smartd_log.conf'
2018-11-08 13:36:21: python.d ERROR: plugin: main: cannot load '/opt/netdata/lib/netdata/conf.d/python.d/smartd_log.conf': [Errno 2] No such file or directory: '/opt/netdata/lib/netdata/conf.d/python.d/smartd_log.conf'
2018-11-08 13:36:21: python.d DEBUG: plugin: main: job initialization: 'smartd_log smartd_log' => ['OK']
2018-11-08 13:36:21: python.d DEBUG: plugin: main: module status: 'smartd_log' => [OK] (jobs: 1)
2018-11-08 13:36:21: python.d DEBUG: smartd_log: smartd_log: scanning /var/log/smartd
2018-11-08 13:36:21: python.d ERROR: smartd_log: smartd_log: check() unhandled exception: 'list' object has no attribute 'clear'
2018-11-08 13:36:21: python.d ERROR: smartd_log: smartd_log: Traceback (most recent call last):
  File "/opt/netdata/plugins.d/python.d.plugin", line 317, in check_job
    check_ok = bool(job.check())
  File "/opt/netdata/python.d/smartd_log.chart.py", line 592, in check
    return self.scan() > 0
  File "/opt/netdata/python.d/smartd_log.chart.py", line 641, in scan
    disk = self.create_disk_from_file(full_name, current_time)
  File "/opt/netdata/python.d/smartd_log.chart.py", line 682, in create_disk_from_file
    disk.populate_attrs()
  File "/opt/netdata/python.d/smartd_log.chart.py", line 504, in on_call
    return method(*args)
  File "/opt/netdata/python.d/smartd_log.chart.py", line 554, in populate_attrs
    self.attrs.clear()
AttributeError: 'list' object has no attribute 'clear'

2018-11-08 13:36:21: python.d INFO: smartd_log: smartd_log: check() => [FAILED]
2018-11-08 13:36:21: python.d INFO: plugin: main: FINISHED
```

##### OS / Environment

64Bit Linux, CentOS 6.

netdata built from source, pulled 7 Nov, default configs
Smart logs set to /var/log/smartd/

Any ideas?

**Comment by l2isbad** [comment]
Ops, i will have it fixed ASAP

**Comment by l2isbad** [comment]
@ScrumpyJack
fixed
sorry for this

**Comment by ScrumpyJack** [comment]
thank you. awesome!

**Comment by l2isbad** [comment]
we haven't added any alarms btw
if you can suggest some alarm please do
