### ISSUE TITLE
nvidia_smi module bug

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4892]
```
2018-12-01 22:49:21: python.d ERROR: nvidia_smi: nvidia_smi: update() unhandled exception: could not convert string to float: N/A
```

It passes the check though:
`2018-12-01 22:48:50: python.d INFO: nvidia_smi: nvidia_smi: check() => [OK]`

Netdata version (latest at the time of writing):
```
Your netdata version: 1.11.1-60-gd8e317b7
Your netdata commit: d8e317b
```

Please don't hesitate to ask if you need me to provide more information or help testing changes.

_Originally posted by @Svenskunganka in https://github.com/netdata/netdata/pull/4589#issuecomment-443462220_

**Comment by ilyam8** [comment]
@Svenskunganka

https://github.com/netdata/netdata/blob/d8e317b7ad3b59676cefa4dae42c2d093a08c6f3/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L275-L277

please  replace ^^ with
```python
    @handle_attr_error
    def power_draw(self):
        v = self.root.find('power_readings').find('power_draw').text
        self.error('POWER_DRAW:', v)
        return float(v.split()[0]) * 100
```

and run plugin in debug mode

`python.d.plugin debug trace nvidia_smi`

**Comment by Svenskunganka** [comment]
Here's the output of: `/usr/libexec/netdata/plugins.d/python.d.plugin debug trace nvidia_smi`

```bash
2018-12-01 23:31:31: python.d INFO: plugin: main: Using python 2
2018-12-01 23:31:31: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d.conf'
2018-12-01 23:31:31: python.d DEBUG: plugin: main: module load source: 'nvidia_smi' => [OK]
2018-12-01 23:31:31: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d/nvidia_smi.conf'
2018-12-01 23:31:31: python.d ERROR: plugin: main: cannot load '/etc/netdata/python.d/nvidia_smi.conf' : [Errno 2] No such file or directory: '/etc/netdata/python.d/nvidia_smi.conf'. Will try stock version.
2018-12-01 23:31:31: python.d DEBUG: plugin: main: loading '/usr/lib/netdata/conf.d/python.d/nvidia_smi.conf'
2018-12-01 23:31:31: python.d DEBUG: plugin: main: job initialization: 'nvidia_smi nvidia_smi' => ['OK']
2018-12-01 23:31:31: python.d DEBUG: plugin: main: module status: 'nvidia_smi' => [OK] (jobs: 1)
2018-12-01 23:31:31: python.d INFO: nvidia_smi: nvidia_smi: check() => [OK]
CHART netdata.runtime_nvidia_smi '' 'Execution time for nvidia_smi' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2018-12-01 23:31:31: python.d DEBUG: nvidia_smi: nvidia_smi: create() => [OK] (charts: 9)
2018-12-01 23:31:31: python.d DEBUG: nvidia_smi: nvidia_smi: started, update frequency: 1, retries: 60
2018-12-01 23:31:31: python.d ERROR: nvidia_smi: nvidia_smi: no element found: line 1, column 0
2018-12-01 23:31:31: python.d ERROR: nvidia_smi: nvidia_smi: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/nvidia_smi.chart.py", line 353, in parse_xml
    return et.fromstring(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0

2018-12-01 23:31:31: python.d DEBUG: nvidia_smi: nvidia_smi: get_data() returned no data
2018-12-01 23:31:31: python.d DEBUG: nvidia_smi: nvidia_smi: update => [FAILED] (elapsed time: -, retries left: 59)
CHART nvidia_smi.gpu0_pci_bandwidth '' 'PCI Express Bandwidth Utilization' 'KB/s' 'gpu0 GeForce GTX 960M' 'nvidia_smi.pci_bandwidth' area 60000 1 '' 'python.d.plugin' 'nvidia_smi'
DIMENSION 'gpu0_rx_util' 'rx' absolute 1 1 ''
DIMENSION 'gpu0_tx_util' 'tx' absolute 1 -1 ''

BEGIN nvidia_smi.gpu0_pci_bandwidth 0
SET 'gpu0_rx_util' = 0
SET 'gpu0_tx_util' = 0
END

2018-12-01 23:31:32: python.d ERROR: nvidia_smi: nvidia_smi: update() unhandled exception: invalid literal for int() with base 10: 'N/A'
2018-12-01 23:31:32: python.d ERROR: nvidia_smi: nvidia_smi: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 196, in run
    updated = self.update(interval=since)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 243, in update
    ok = chart.update(data, interval)
  File "/usr/libexec/netdata/python.d/python_modules/bases/charts.py", line 233, in update
    value = dim.get_value(data)
  File "/usr/libexec/netdata/python.d/python_modules/bases/charts.py", line 329, in get_value
    return int(data[self.id])
ValueError: invalid literal for int() with base 10: 'N/A'

2018-12-01 23:31:32: python.d DEBUG: nvidia_smi: nvidia_smi: update => [FAILED] (elapsed time: -, retries left: 58)
BEGIN nvidia_smi.gpu0_pci_bandwidth 0
SET 'gpu0_rx_util' = 0
SET 'gpu0_tx_util' = 0
END
```
And then it keeps on repeating the same messages.

The PCI-e bandwidth has showed up though

**Comment by Svenskunganka** [comment]
There's a lot of `N/A` in the output of `nvidia-smi -a` as well:

```bash
==============NVSMI LOG==============

Timestamp                           : Sat Dec  1 23:45:21 2018
Driver Version                      : 410.72
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 960M
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-101b1cf0-fdf7-b374-a62c-76b25134fcf2
    Minor Number                    : 0
    VBIOS Version                   : 82.07.73.00.06
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x139B10DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x86711043
        GPU Link Info
            PCIe Generation
                Max                 : 2
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 4x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : N/A
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : N/A
            HW Power Brake Slowdown : N/A
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 2004 MiB
        Used                        : 0 MiB
        Free                        : 2004 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 1 MiB
        Free                        : 255 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 36 C
        GPU Shutdown Temp           : 101 C
        GPU Slowdown Temp           : 96 C
        GPU Max Operating Temp      : 92 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 135 MHz
        SM                          : 135 MHz
        Memory                      : 405 MHz
        Video                       : 405 MHz
    Applications Clocks
        Graphics                    : 1097 MHz
        Memory                      : 2505 MHz
    Default Applications Clocks
        Graphics                    : 1097 MHz
        Memory                      : 2505 MHz
    Max Clocks
        Graphics                    : 1202 MHz
        SM                          : 1202 MHz
        Memory                      : 2505 MHz
        Video                       : 1081 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : None
```

**Comment by ilyam8** [comment]
Thats another error, i see no `could not convert string to float`

please add
`self.debug(data)`
before

https://github.com/netdata/netdata/blob/d8e317b7ad3b59676cefa4dae42c2d093a08c6f3/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L324

**Comment by Svenskunganka** [comment]
Seems to be the `gpu0_fan_speed`:

```bash
2018-12-01 23:54:50: python.d DEBUG: nvidia_smi: nvidia_smi: {'gpu0_gpu_util': '0', 'gpu0_memory_util': '0', 'gpu0_fan_speed': 'N/A', 'gpu0_gpu_temp': '37', 'gpu0_graphics_clock': '135', 'gpu0_decoder_util': '0', 'gpu0_mem_clock': '405', 'gpu0_encoder_util': '0', 'gpu0_video_clock': '405', 'gpu0_sm_clock': '135', 'gpu0_fb_memory_usage': '0', 'gpu0_rx_util': '0', 'gpu0_tx_util': '0'}
```

**Comment by ilyam8** [comment]
@Svenskunganka 
please check the [fix](https://github.com/netdata/netdata/pull/4893)

**Comment by Svenskunganka** [comment]
Works perfectly. No errors from `python.d.plugin debug trace nvidia_smi` either. Thank you @ilyam8 for the swift solution!

**Comment by ktsaou** [comment]
merged the fix
