### ISSUE TITLE
debugging modules written for node.d.plugin question

### ISSUE THREAD

**Issue by bitcoiners** [netdata/netdata#4939]
Following instructions from 
https://docs.netdata.cloud/collectors/node.d.plugin/
on Ubuntu 18.04
I am told to run
/usr/libexec/netdata/plugins.d/node.d.plugin debug 1 X Y Z
but such file does not exist
I found this instead 
/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin debug 1 X Y Z
but when I run it as netdata user I get:

````node.d.plugin: ERROR: Cannot read configuration file /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../../../../etc/netdata/node.d.conf: ENOENT: no such file or directory, open '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/../../../../etc/netdata/node.d.conf', using internal defaults.
2018-12-07 17:03:08: node.d.plugin: DEBUG: DEBUG enabled
2018-12-07 17:03:08: node.d.plugin: DEBUG: PARAM: 1
2018-12-07 17:03:08: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-12-07 17:03:08: node.d.plugin: DEBUG: PARAM: X
2018-12-07 17:03:08: node.d.plugin: DEBUG: enabled module X
2018-12-07 17:03:08: node.d.plugin: DEBUG: PARAM: Y
2018-12-07 17:03:08: node.d.plugin: DEBUG: enabled module Y
2018-12-07 17:03:08: node.d.plugin: DEBUG: PARAM: Z
2018-12-07 17:03:08: node.d.plugin: DEBUG: enabled module Z
2018-12-07 17:03:08: node.d.plugin: ERROR: Cannot load any .node.js module from: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../node.d
```

**Comment by cakrit** [comment]
@ilyam8 it looks like either the documentation is wrong, and it can only be executed as root, or the installer [doesn't set the correct ownership/permissions](
https://github.com/netdata/netdata/blob/master/netdata-installer.sh#L696)

Which one is it?

**Comment by bitcoiners** [comment]
I updated error message with missing top part.

**Comment by cakrit** [comment]
@bitcoiners I can tell you that it will definitely work if you run it as root, just need to see if we should change the docs or the installer.

**Comment by bitcoiners** [comment]
I tried running with sudo with same errors

```
sudo /usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin debug 1 X Y Z
[sudo] password for slava: 
2018-12-07 19:56:52: node.d.plugin: ERROR: Cannot read configuration file /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../../../../etc/netdata/node.d.conf: ENOENT: no such file or directory, open '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/../../../../etc/netdata/node.d.conf', using internal defaults.
2018-12-07 19:56:52: node.d.plugin: DEBUG: DEBUG enabled
2018-12-07 19:56:52: node.d.plugin: DEBUG: PARAM: 1
2018-12-07 19:56:52: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-12-07 19:56:52: node.d.plugin: DEBUG: PARAM: X
2018-12-07 19:56:52: node.d.plugin: DEBUG: enabled module X
2018-12-07 19:56:52: node.d.plugin: DEBUG: PARAM: Y
2018-12-07 19:56:52: node.d.plugin: DEBUG: enabled module Y
2018-12-07 19:56:52: node.d.plugin: DEBUG: PARAM: Z
2018-12-07 19:56:52: node.d.plugin: DEBUG: enabled module Z
2018-12-07 19:56:52: node.d.plugin: ERROR: Cannot load any .node.js module from: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../node.d

```

**Comment by cakrit** [comment]
I'd like to see where everything is on your system. 

Please locate your `netdata.conf` and do this:
`sudo grep directory [your path]/netdata.conf | grep -v cache`

Also, this:
`sudo grep process.env.*DIR /usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin`

**Comment by bitcoiners** [comment]
my netdata.conf is in /etc/netdata
sudo grep directory /etc/netdata/netdata.conf | grep -v cache
comes back empty
```

 sudo grep process.env.*DIR /usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin
var NETDATA_PLUGINS_DIR = process.env.NETDATA_PLUGINS_DIR || __dirname;
var NETDATA_CONFIG_DIR = process.env.NETDATA_CONFIG_DIR || __dirname + '/../../../../etc/netdata';
```

**Comment by cakrit** [comment]
This isn't right. What version are you running and how did you install it? It looks like you'll need an update, but let's try to see if we can fix it manually first. 

The DATA_CONFIG_DIR in node.d.plugin is definitely wrong, because it ends up pointing to /usr/etc/netdata and there should be nothing there, even in this older version (please verify). I believe it needs one more ../ so it can go to /etc/netdata. i.e.
```
var NETDATA_CONFIG_DIR = process.env.NETDATA_CONFIG_DIR || __dirname + '/../../../../../etc/netdata';
```
The question is what's there. netdata.conf is not really required, it can be empty, which is probably what you have. To be absolutely certain that you're going to the correct config directory, can you check if you have `/etc/netdata/node.d.conf`? 

If not, please do an ls -l on /etc/netdata so I can see what the directory structure looks like in this installation.

**Comment by bitcoiners** [comment]
I am running netdata 1.9.0
installed with sudo apt install netdata
have /etc/netdata/node.d.conf

```
$ ls -l /etc/netdata
total 88
-rw-r--r-- 1 root root  9449 Jan 27  2018 apps_groups.conf
drwxr-xr-x 2 root root  4096 Oct 13 12:44 charts.d
-rw-r--r-- 1 root root  1829 Jan 27  2018 charts.d.conf
-rw-r--r-- 1 root root  1233 Jan 27  2018 fping.conf
-rw-r--r-- 1 root root 21246 Oct 26 08:20 health_alarm_notify.conf
drwxr-xr-x 2 root root  4096 Oct 13 12:44 health.d
-rw-r--r-- 1 root root    57 Jan 27  2018 health_email_recipients.conf
-rw-r--r-- 1 root root   547 Nov 29 15:54 netdata.conf
drwxr-xr-x 2 root root  4096 Oct 13 12:44 node.d
-rw-r--r-- 1 root root  1351 Dec  7 17:02 node.d.conf
drwxr-xr-x 2 root root  4096 Oct 13 12:44 python.d
-rw-r--r-- 1 root root  1410 Jan 27  2018 python.d.conf
drwxr-xr-x 2 root root  4096 Oct 13 12:44 statsd.d
-rw-r--r-- 1 root root  6135 Jan 27  2018 stream.conf
```

updated node.d.plugin 
set
var NETDATA_CONFIG_DIR = process.env.NETDATA_CONFIG_DIR || __dirname + '../../../../../etc/netdata';
now getting:
```
sudo /usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin debug 1 X Y Z
2018-12-07 21:08:23: node.d.plugin: DEBUG: DEBUG enabled
2018-12-07 21:08:23: node.d.plugin: DEBUG: PARAM: 1
2018-12-07 21:08:23: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-12-07 21:08:23: node.d.plugin: DEBUG: PARAM: X
2018-12-07 21:08:23: node.d.plugin: DEBUG: enabled module X
2018-12-07 21:08:23: node.d.plugin: DEBUG: PARAM: Y
2018-12-07 21:08:23: node.d.plugin: DEBUG: enabled module Y
2018-12-07 21:08:23: node.d.plugin: DEBUG: PARAM: Z
2018-12-07 21:08:23: node.d.plugin: DEBUG: enabled module Z
2018-12-07 21:08:23: node.d.plugin: ERROR: Cannot load any .node.js module from: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../node.d

```

**Comment by bitcoiners** [comment]
running 
```
$ sudo /usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin debug 1 nodeos
2018-12-07 21:35:39: node.d.plugin: DEBUG: DEBUG enabled
2018-12-07 21:35:39: node.d.plugin: DEBUG: PARAM: 1
2018-12-07 21:35:39: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-12-07 21:35:39: node.d.plugin: DEBUG: PARAM: nodeos
2018-12-07 21:35:39: node.d.plugin: DEBUG: enabled module nodeos
2018-12-07 21:35:39: node.d.plugin: DEBUG: loading module /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../node.d/nodeos.node.js
2018-12-07 21:35:39: node.d.plugin: ERROR: Cannot load module: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../node.d/nodeos.node.js exception: ReferenceError: netdata is not defined
2018-12-07 21:35:39: node.d.plugin: DEBUG: ReferenceError: netdata is not defined
    at Object.<anonymous> (/home/user/dev/netdata/dashboards/nodeos.node.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at findModules (/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin:215:57)
    at Object.<anonymous> (/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin:271:4)
2018-12-07 21:35:39: node.d.plugin: ERROR: Cannot load any .node.js module from: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../node.d

```

my /usr/lib/x86_64-linux-gnu/netdata//node.d/nodeos.node.js

```
// the processor is needed only
// if you need a custom processor
// other than http
netdata.processors.nodeos = {
    name: 'nodeos',

    process: function(service, callback) {

        /* do data collection here */

        callback(data);
    }
};

// this is the module definition
var nodeos = {
    processResponse: function(service, data) {

        /* send information to the netdata server here */

    },

    configure: function(config) {
        var eligible_services = 0;

        if(typeof(config.servers) === 'undefined' || config.servers.length === 0) {

            /*
             * create a service using internal defaults;
             * this is used for auto-detecting the settings
             * if possible
             */

            netdata.service({
                name: 'a name for this service',
                update_every: this.update_every,
                module: this,
                processor: netdata.processors.nodeos,
                // any other information your processor needs
            }).execute(this.processResponse);

            eligible_services++;
        }
        else {

            /*
             * create a service for each server in the
             * configuration file
             */

            var len = config.servers.length;
            while(len--) {
                var server = config.servers[len];

                netdata.service({
                    name: server.name,
                    update_every: server.update_every,
                    module: this,
                    processor: netdata.processors.nodeos,
                    // any other information your processor needs
                }).execute(this.processResponse);

                eligible_services++;
            }
        }

        return eligible_services;
    },

    update: function(service, callback) {

        /*
         * this function is called when each service
         * created by the configure function, needs to
         * collect updated values.
         *
         * You normally will not need to change it.
         */

        service.execute(function(service, data) {
            nodeos.processResponse(service, data);
            callback();
        });
    },
};

module.exports = nodeos;

```

**Comment by cakrit** [comment]
Please tell me your OS. 1.9 is very old, I will contact the maintainers.
Better uninstall it and try the [one line installation]( https://docs.netdata.cloud/installer/#one-line-installation). If it doesn't work, on your system, the worst case is that you'll need to do the [manual installation](https://docs.netdata.cloud/installer/#install-netdata-on-linux-manually)

**Comment by bitcoiners** [comment]
I am running ubuntu 18.04

**Comment by bitcoiners** [comment]
ok. I uninstalled netdata .deb and installed with one line installation.
now running 
$ sudo /usr/libexec/netdata/plugins.d/node.d.plugin debug 1 nodeos
I get error:
```
$ sudo /usr/libexec/netdata/plugins.d/node.d.plugin debug 1 nodeos
2018-12-07 21:55:57: node.d.plugin: DEBUG: DEBUG enabled
2018-12-07 21:55:57: node.d.plugin: DEBUG: PARAM: 1
2018-12-07 21:55:57: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-12-07 21:55:57: node.d.plugin: DEBUG: PARAM: nodeos
2018-12-07 21:55:57: node.d.plugin: DEBUG: enabled module nodeos
2018-12-07 21:55:57: node.d.plugin: DEBUG: loading module /usr/libexec/netdata/plugins.d/../node.d/nodeos.node.js
2018-12-07 21:55:57: node.d.plugin: ERROR: Cannot load module: /usr/libexec/netdata/plugins.d/../node.d/nodeos.node.js exception: ReferenceError: netdata is not defined
2018-12-07 21:55:57: node.d.plugin: DEBUG: ReferenceError: netdata is not defined
    at Object.<anonymous> (/usr/libexec/netdata/node.d/nodeos.node.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at findModules (/usr/libexec/netdata/plugins.d/node.d.plugin:231:57)
    at Object.<anonymous> (/usr/libexec/netdata/plugins.d/node.d.plugin:280:4)
2018-12-07 21:55:57: node.d.plugin: ERROR: Cannot load any .node.js module from: /usr/libexec/netdata/plugins.d/../node.d

```

my module is /usr/libexec/netdata/node.d/nodeos.node.js

```
// the processor is needed only
// if you need a custom processor
// other than http
netdata.processors.nodeos = {
    name: 'nodeos',

    process: function(service, callback) {

        /* do data collection here */

        callback(data);
    }
};

// this is the module definition
var nodeos = {
    processResponse: function(service, data) {

        /* send information to the netdata server here */

    },

    configure: function(config) {
        var eligible_services = 0;

        if(typeof(config.servers) === 'undefined' || config.servers.length === 0) {

            /*
             * create a service using internal defaults;
             * this is used for auto-detecting the settings
             * if possible
             */

            netdata.service({
                name: 'a name for this service',
                update_every: this.update_every,
                module: this,
                processor: netdata.processors.nodeos,
                // any other information your processor needs
            }).execute(this.processResponse);

            eligible_services++;
        }
        else {

            /*
             * create a service for each server in the
             * configuration file
             */

            var len = config.servers.length;
            while(len--) {
                var server = config.servers[len];

                netdata.service({
                    name: server.name,
                    update_every: server.update_every,
                    module: this,
                    processor: netdata.processors.nodeos,
                    // any other information your processor needs
                }).execute(this.processResponse);

                eligible_services++;
            }
        }

        return eligible_services;
    },

    update: function(service, callback) {

        /*
         * this function is called when each service
         * created by the configure function, needs to
         * collect updated values.
         *
         * You normally will not need to change it.
         */

        service.execute(function(service, data) {
            nodeos.processResponse(service, data);
            callback();
        });
    },
};

module.exports = nodeos;
```

**Comment by ilyam8** [comment]
@bitcoiners if you write your custom module in `python` it will be much easier to help you

**Comment by bitcoiners** [comment]
Unfortunately I do not use python, prefer javascript. 
However this module is just a basic template right now, copied from https://docs.netdata.cloud/collectors/node.d.plugin/

**Comment by ilyam8** [comment]
i see

> 2018-12-07 21:55:57: node.d.plugin: DEBUG: ReferenceError: netdata is not defined

i checked another `node.d` modules

They have `var netdata = require("netdata");` at the top

**Comment by bitcoiners** [comment]
ok. I added
var netdata = require('netdata');
at the top and now getting this error:

```
$ sudo /usr/libexec/netdata/plugins.d/node.d.plugin debug 1 nodeos
2018-12-07 22:28:55: node.d.plugin: DEBUG: DEBUG enabled
2018-12-07 22:28:55: node.d.plugin: DEBUG: PARAM: 1
2018-12-07 22:28:55: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-12-07 22:28:55: node.d.plugin: DEBUG: PARAM: nodeos
2018-12-07 22:28:55: node.d.plugin: DEBUG: enabled module nodeos
2018-12-07 22:28:55: node.d.plugin: DEBUG: loading module /usr/libexec/netdata/plugins.d/../node.d/nodeos.node.js
2018-12-07 22:28:55: node.d.plugin: ERROR: Cannot load module: /usr/libexec/netdata/plugins.d/../node.d/nodeos.node.js exception: Error: Cannot find module 'netdata'
2018-12-07 22:28:55: node.d.plugin: DEBUG: Error: Cannot find module 'netdata'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/slava/dev/netdata/dashboards/nodeos.node.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2018-12-07 22:28:55: node.d.plugin: ERROR: Cannot load any .node.js module from: /usr/libexec/netdata/plugins.d/../node.d

```

**Comment by cakrit** [comment]
Don't you see `/usr/libexec/netdata/node.d/node_modules/netdata.js`? Can you check the permissions on it?

Can you also send a sample of your nodeos.conf? I'm trying to execute locally, but I had to add garbage for your variable `data`. Still, the script didn't complain about module netdata.

**Comment by bitcoiners** [comment]
ll /usr/libexec/netdata/node.d/node_modules/netdata.js
-rw-r--r-- 1 root root 25878 Dec  7 21:52 /usr/libexec/netdata/node.d/node_modules/netdata.js

cat /etc/netdata/node.d/nodeos.conf
{
    "enable_autodetect": false,
    "update_every": 5,
    "servers": [ { /* server 1 */ }, { /* server 2 */ } ]
}
