### ISSUE TITLE
smartd_log: check() unhandled exception: list index out of range

### ISSUE THREAD

**Issue by kevlar1818** [netdata/netdata#5079]
##### Bug report summary
I noticed the smartd_log plugin stopped showing up in my dashboard, so I looked in /var/log/netdata/error.log:

```
python.d ERROR: smartd_log: smartd_log: check() unhandled exception: list index out of range
python.d INFO: smartd_log: smartd_log: check() => [FAILED]
```

##### OS / Environment
Arch Linux
(installed with `pacman -S netdata` and started with `systemctl start netdata`)

##### Component Name
smartd_log Python plugin

##### Steps To Reproduce
- Install netdata and smartmontools
- Configure smartd to log output to `/var/log/smartd/` as recommended in the netdata documentation.
- Start smartd
- Notice smartd logging CSVs to `/var/log/smartd/`
- Start netdata
- Notice no smartd_log item in the netdata dashboard
- `grep smartd /var/log/netdata/error.log` to view related errors
- Notice the lines mentioned in the summary above

##### Expected behavior
The smartd_log plugin should work when properly configured as documented.

**Comment by ilyam8** [comment]
Hi @kevlar1818 

> installed with pacman -S netdata and started with systemctl start netdata

What's your `netdata` version?

**Comment by ilyam8** [comment]
@kevlar1818 

please run plugin in debug mode as `netdata` user

 * `sudo su -s /bin/bash netdata`
 * `/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin smartd_log debug trace`

**Comment by kevlar1818** [comment]
netdata version (from Web UI): `v1.11.1_rolling`

My CSVs look like this:
`ADATA_SU650-<alphanumeric characters here>.ata.csv`

I don't have that exact path, but I found `python.d.plugin` and ran it like so (as the `netdata` user):
```
$ /usr/lib/netdata/plugins.d/python.d.plugin smartd_log debug trace
2018-12-30 14:11:41: python.d INFO: plugin: main: Using python 3
2018-12-30 14:11:41: python.d DEBUG: plugin: main: loading '/usr/local/etc/netdata/python.d.conf'
2018-12-30 14:11:41: python.d ERROR: plugin: main: cannot load '/usr/local/etc/netdata/python.d.conf': [Errno 2] No such file or directory: '/usr/local/etc/netdata/python.d.conf'. Will try stock version.
2018-12-30 14:11:41: python.d DEBUG: plugin: main: loading '/usr/local/lib/netdata/conf.d/python.d.conf'
2018-12-30 14:11:41: python.d ERROR: plugin: main: cannot load '/usr/local/lib/netdata/conf.d/python.d.conf': [Errno 2] No such file or directory: '/usr/local/lib/netdata/conf.d/python.d.conf'
2018-12-30 14:11:41: python.d DEBUG: plugin: main: module load source: 'smartd_log' => [OK]
2018-12-30 14:11:41: python.d DEBUG: plugin: main: loading '/usr/local/etc/netdata/python.d/smartd_log.conf'
2018-12-30 14:11:41: python.d ERROR: plugin: main: cannot load '/usr/local/etc/netdata/python.d/smartd_log.conf' : [Errno 2] No such file or directory: '/usr/local/etc/netdata/python.d/smartd_log.conf'. Will try stock version.
2018-12-30 14:11:41: python.d DEBUG: plugin: main: loading '/usr/local/lib/netdata/conf.d/python.d/smartd_log.conf'
2018-12-30 14:11:41: python.d ERROR: plugin: main: cannot load '/usr/local/lib/netdata/conf.d/python.d/smartd_log.conf': [Errno 2] No such file or directory: '/usr/local/lib/netdata/conf.d/python.d/smartd_log.conf'
2018-12-30 14:11:41: python.d DEBUG: plugin: main: job initialization: 'smartd_log smartd_log' => ['OK']
2018-12-30 14:11:41: python.d DEBUG: plugin: main: module status: 'smartd_log' => [OK] (jobs: 1)
2018-12-30 14:11:41: python.d DEBUG: smartd_log: smartd_log: scanning /var/log/smartd
2018-12-30 14:11:41: python.d DEBUG: smartd_log: smartd_log: added Hitachi_HDS723030ALA640-MK0331YHGSSZ8A.ata.csv
2018-12-30 14:11:41: python.d DEBUG: smartd_log: smartd_log: skipping Hitachi_HDS723030ALA640-MK0331YHGT2XTA.ata.csv.1.gz: not a csv file
2018-12-30 14:11:41: python.d ERROR: smartd_log: smartd_log: check() unhandled exception: list index out of range
2018-12-30 14:11:41: python.d ERROR: smartd_log: smartd_log: Traceback (most recent call last):
  File "/usr/lib/netdata/plugins.d/python.d.plugin", line 317, in check_job
    check_ok = bool(job.check())
  File "/usr/lib/netdata/python.d/smartd_log.chart.py", line 592, in check
    return self.scan() > 0
  File "/usr/lib/netdata/python.d/smartd_log.chart.py", line 641, in scan
    disk = self.create_disk_from_file(full_name, current_time)
  File "/usr/lib/netdata/python.d/smartd_log.chart.py", line 649, in create_disk_from_file
    name = os.path.basename(full_name).split('.')[-3]
IndexError: list index out of range

2018-12-30 14:11:41: python.d INFO: smartd_log: smartd_log: check() => [FAILED]
2018-12-30 14:11:41: python.d INFO: plugin: main: FINISHED
```

**Comment by kevlar1818** [comment]
@ilyam8 Thanks for pointing out how to debug these plugsin!
