### ISSUE TITLE
postgresql : invalid connection option "autodetection_retry"

### ISSUE THREAD

**Issue by Jaxmetalmax** [netdata/netdata#5615]
##### Bug report summary
Error on connecting to database with postgresql plugin, the error log shows this:

> 2019-03-12 10:06:32: python.d INFO: plugin[main] : using python v2
2019-03-12 10:06:32: python.d INFO: plugin[main] : starting setup
2019-03-12 10:06:32: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-03-12 10:06:32: python.d INFO: plugin[main] : config found, loading config '/usr/lib/netdata/conf.d/python.d.conf'
2019-03-12 10:06:32: python.d INFO: plugin[main] : config successfully loaded
2019-03-12 10:06:32: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-03-12 10:06:32: python.d INFO: plugin[checker] : starting...
2019-03-12 10:06:32: python.d INFO: plugin[checker] : postgres : checking
2019-03-12 10:06:32: python.d INFO: plugin[checker] : postgres : source successfully loaded
2019-03-12 10:06:32: python.d INFO: plugin[checker] : postgres : found config file '/etc/netdata/python.d/postgres.conf'
2019-03-12 10:06:32: python.d INFO: plugin[checker] : postgres : created 2 job(s) from the config
2019-03-12 10:06:32: python.d ERROR: postgres[tcp] : invalid connection option "autodetection_retry"
>
> 2019-03-12 10:06:32: python.d ERROR: postgres[tcp] : Traceback (most recent call last):
>   File "/usr/libexec/netdata/python.d/postgres.chart.py", line 827, in connect
>     self.conn = psycopg2.connect(**params)
>   File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, async=async)
> OperationalError: invalid connection option "autodetection_retry"
> 
> 
> 2019-03-12 10:06:32: python.d ERROR: postgres[tcp] : failed to connect to {'autodetection_retry': 0, 'database': 'postgres', 'host': 'localhost', 'user': 'postgres', 'password': '*****', 'port': 5432}
> 2019-03-12 10:06:32: python.d INFO: plugin[checker] : postgres[tcp] : check failed, skipping the job
> 2019-03-12 10:06:32: python.d ERROR: postgres[tcpipv4] : invalid connection option "autodetection_retry"
> .
> .
> .

##### Steps To Reproduce

enable postgres plugin, this is part of my configuration file, I just edited the connections params, nothing else:

```
#socket:
#    name     : 'local'
#    user     : 'postgres'
#    database : 'postgres'

tcp:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    password : 'mypass'
    host     : 'localhost'
    port     : 5432

tcpipv4:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    password : 'mypass'
    host     : '127.0.0.1'
    port     : 5432
```

I have correct params on pg_hba.conf, in the error log it seems that when connecting to database the parameter "autodetection_retry" is sent as a connection parameter but params dict in **/usr/libexec/netdata/python.d/postgres.chart.py** has no autedection_retry param

```
try:
            params = dict(
                host=None,
                port=DEFAULT_PORT,
                database=None,
                user=DEFAULT_USER,
                password=None,
                connect_timeout=DEFAULT_CONNECT_TIMEOUT,
                options='-c statement_timeout={0}'.format(self.statement_timeout),
            )
            params.update(self.configuration)

            self.conn = psycopg2.connect(**params)
```

**Comment by ilyam8** [comment]
@Jaxmetalmax 	thx for reporting!
