### ISSUE TITLE
CouchDB collector exception

### ISSUE THREAD

**Issue by TimSylvester** [netdata/netdata#5830]
##### Bug report summary
CouchDB monitoring stops sometimes.  Instead of reporting no metrics on an unexpected response, the collector stops with an exception, requiring a netdata restart to recover.

netdata/error.log includes:

```
...
2019-04-10 12:34:06: python.d INFO: boinc: boinc: check() => [FAILED]
2019-04-10 12:34:06: python.d INFO: ceph: ceph: check() => [FAILED]
Exception in thread Thread-80:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/libexec/netdata/python.d/couchdb.chart.py", line 322, in _get_overview_stats
    to_netdata = self._fetch_data(raw_data=data, metrics=stats)
  File "/usr/libexec/netdata/python.d/couchdb.chart.py", line 369, in _fetch_data
    value = value[m]
TypeError: list indices must be integers, not str
2019-04-10 12:34:07: apps.plugin ERROR : MAIN : heartbeat missed 3994171 monotonic microseconds
```

##### OS / Environment
Ubuntu 18.04.2 LTS / 4.15.0-1035-aws / x86_64
CouchDB 2.3.1

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-rc0-42-gbee48fd3

##### Component Name
collectors/python.d.plugin/couchdb/couchdb.chart.py

##### Steps To Reproduce
Unknown.  Appears to depend on unexpected data being returned from couchdb _stats or _system requests, i.e., an array rather than an object/dictionary.

##### Expected behavior
Gaps in the chart instead of stopping collection.

**Comment by ilyam8** [comment]
@TimSylvester thx for reporting! 👍
