### ISSUE TITLE
netdata/daemon: Service down with multiple "too many open files" occurring on DB engine

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6265]
##### Bug report summary
As discussed we need to investigate the root cause of netdata crash on one of our demo servers due to maximum open files limit.

- Netdata should not crash when max file descriptors are reached.

- Netdata should allocate a FD budget for dbengine and inform the user of the typical requirements. The user should be able to configure the service FD budget depending on her needs such as the amount of streaming slaves connected to this master.

- Netdata should not allow a new streaming slave to connect to this master if the FD budget has run out.

- In the unlikely event of descriptors running out dbengine will continue writing on the same data and journal files until the problem is resolved. The error condition will be recorded with specific statistics and a new alarm will be generated.

CC: @cakrit @ktsaou 
##### OS / Environment
Any

##### Netdata version (ouput of `netdata -V`)
Latest

##### Component Name
netdata/database

##### Steps To Reproduce
Run netdata on a system with very low max file connections setting to get a reproduction

##### Expected behavior
Netdata should not crash when max open file limits are reached

**Comment by paulkatsoulakis** [comment]
We had a fresh use case this time.
Even though we increased the max file descriptors for the service, there was a new crash raised.

logs indicating the max FD change:
```
xxxxx netdata # grep "allowed file descriptors" error.log.1
2019-06-11 20:18:36: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1024, max = 4096
2019-06-11 21:10:52: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 65536, max = 65536
2019-06-11 21:50:58: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 131072, max = 131072
```

logs around the time of the new crash:
```
xxxxxx netdata # cat error.log
2019-06-12 06:40:20: netdata INFO  : MAIN : Deleting data file "datafile-1-0000000001.ndf".
2019-06-12 06:40:20: netdata INFO  : MAIN : Deleted data file "datafile-1-0000000001.ndf".
2019-06-12 06:40:20: netdata INFO  : MAIN : Reclaimed 17813504 bytes of disk space.
2019-06-12 06:40:23: netdata INFO  : MAIN : Creating new data and journal files.
2019-06-12 06:40:38: netdata ERROR : PLUGIN[cgroups] : heartbeat missed 1016850 monotonic microseconds
2019-06-12 06:44:37: netdata ERROR : STREAM_RECEIVER[plamo6,[10.0.3.210]:53480] : read failed (errno 104, Connection reset by peer)
2019-06-12 06:44:37: netdata ERROR : STREAM_RECEIVER[plamo6,[10.0.3.210]:53480] : STREAM plamo6 [receive from [10.0.3.210]:53480]: disconnected (completed 280509 updates).
2019-06-12 06:44:37: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53480] : STREAM plamo6 [receive from [10.0.3.210]:53480]: receive thread ended (task id 67754)
2019-06-12 06:44:37: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53480] : thread with task id 67754 finished
2019-06-12 06:45:27: netdata INFO  : WEB_SERVER[static2] : clients wants to STREAM metrics.
2019-06-12 06:45:27: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : thread created with task id 77459
2019-06-12 06:45:27: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : STREAM plamo6 [10.0.3.210]:53538: receive thread created (task id 77459)
2019-06-12 06:45:27: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : STREAM plamo6 [receive from [10.0.3.210]:53538]: initializing communication...
2019-06-12 06:45:27: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : STREAM plamo6 [receive from [10.0.3.210]:53538]: receiving metrics...
2019-06-12 06:51:24: tc-qos-helper.sh: WARNING: Cannot find file '/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2019-06-12 06:51:24: tc-qos-helper.sh: WARNING: Cannot find file '/etc/netdata/tc-qos-helper.conf'.
2019-06-12 06:52:00: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: client slot 18 (fd 1076) from localhost port 37934 is idle for more than 3600 seconds - closing it. 
2019-06-12 06:57:21: netdata INFO  : MAIN : Deleting data file "datafile-1-0000000001.ndf".
2019-06-12 06:57:21: netdata INFO  : MAIN : Deleted data file "datafile-1-0000000001.ndf".
2019-06-12 06:57:21: netdata INFO  : MAIN : Reclaimed 17764352 bytes of disk space.
2019-06-12 06:57:22: netdata INFO  : MAIN : Deleting data file "datafile-1-0000000001.ndf".
2019-06-12 06:57:22: netdata INFO  : MAIN : Deleted data file "datafile-1-0000000001.ndf".
2019-06-12 06:57:22: netdata INFO  : MAIN : Reclaimed 17719296 bytes of disk space.
2019-06-12 06:57:42: netdata ERROR : PLUGIN[cgroups] : heartbeat missed 1012156 monotonic microseconds
2019-06-12 07:06:40: netdata ERROR : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : read failed (errno 104, Connection reset by peer)
2019-06-12 07:06:40: netdata ERROR : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : STREAM plamo6 [receive from [10.0.3.210]:53538]: disconnected (completed 237114 updates).
2019-06-12 07:06:40: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : STREAM plamo6 [receive from [10.0.3.210]:53538]: receive thread ended (task id 77459)
2019-06-12 07:06:40: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53538] : thread with task id 77459 finished
2019-06-12 07:07:28: netdata INFO  : WEB_SERVER[static4] : clients wants to STREAM metrics.
2019-06-12 07:07:28: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : thread created with task id 86976
2019-06-12 07:07:28: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : STREAM plamo6 [10.0.3.210]:53584: receive thread created (task id 86976)
2019-06-12 07:07:28: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : STREAM plamo6 [receive from [10.0.3.210]:53584]: initializing communication...
2019-06-12 07:07:28: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : STREAM plamo6 [receive from [10.0.3.210]:53584]: receiving metrics...
2019-06-12 07:14:38: netdata INFO  : MAIN : Deleting data file "datafile-1-0000000521.ndf".
2019-06-12 07:14:38: netdata INFO  : MAIN : Deleted data file "datafile-1-0000000521.ndf".
2019-06-12 07:14:38: netdata INFO  : MAIN : Reclaimed 19218432 bytes of disk space.
2019-06-12 07:14:44: netdata INFO  : MAIN : Creating new data and journal files.
2019-06-12 07:14:46: netdata ERROR : PLUGIN[cgroups] : heartbeat missed 980121 monotonic microseconds
2019-06-12 07:28:17: netdata ERROR : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : read failed (errno 104, Connection reset by peer)
2019-06-12 07:28:17: netdata ERROR : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : STREAM plamo6 [receive from [10.0.3.210]:53584]: disconnected (completed 239394 updates).
2019-06-12 07:28:17: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : STREAM plamo6 [receive from [10.0.3.210]:53584]: receive thread ended (task id 86976)
2019-06-12 07:28:17: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53584] : thread with task id 86976 finished
2019-06-12 07:30:18: netdata INFO  : WEB_SERVER[static2] : clients wants to STREAM metrics.
2019-06-12 07:30:18: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53628] : thread created with task id 96144
2019-06-12 07:30:18: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53628] : STREAM plamo6 [10.0.3.210]:53628: receive thread created (task id 96144)
2019-06-12 07:30:18: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53628] : STREAM plamo6 [receive from [10.0.3.210]:53628]: initializing communication...
2019-06-12 07:30:18: netdata INFO  : STREAM_RECEIVER[plamo6,[10.0.3.210]:53628] : STREAM plamo6 [receive from [10.0.3.210]:53628]: receiving metrics...
2019-06-12 07:31:24: netdata INFO  : MAIN : Deleting data file "datafile-1-0000000023.ndf".
2019-06-12 07:31:24: netdata FATAL : MAIN :uv_fs_ftruncate: bad file descriptor # : Bad file descriptor

2019-06-12 07:31:24: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:MAIN' '0067@database/e:destroy_data_fi/9'
2019-06-12 07:31:24: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2019-06-12 07:31:24: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'
2019-06-12 07:31:25: netdata INFO  : MAIN : EXIT: cleaning up the database...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database [30 hosts(s)]...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'stackscale.my-netdata.io'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'centos6'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'opensuse422'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'gentoo'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'oracle6'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpine36'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpine33'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpineedge'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'debiansid'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpine35'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpine32'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'ubuntu1604'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'ubuntu1404'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'fedora25'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'debian8'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'ubuntu1710'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'plamo6'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'centos7'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'debian9'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'fedora26'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'ubuntu1610'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'opensuse423'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'ubuntu1204'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpine34'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'oracle7'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'fedora24'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'debian10'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'arch'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'alpine31'...
2019-06-12 07:31:25: netdata INFO  : MAIN : Cleaning up database of host 'ubuntu1704'...
2019-06-12 07:31:25: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
xxxxxxxx netdata # 
```

**Comment by mfundul** [comment]
Libuv 1.9.1-3 of debian 9 crashes when there are no available file descriptors:
```
Thread 50 "netdata" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdd234700 (LWP 10237)]
uv__async_send (wa=0x1c0) at src/unix/async.c:155
155     src/unix/async.c: No such file or directory.
(gdb) bt
#0  uv__async_send (wa=0x1c0) at src/unix/async.c:155
#1  0x00007ffff6d97404 in uv_async_send (handle=<optimized out>) at src/unix/async.c:66
#2  0x00007ffff6d94d10 in worker (arg=arg@entry=0x0) at src/threadpool.c:101
#3  0x00007ffff6da29f7 in uv__thread_start (arg=<optimized out>) at src/unix/thread.c:52
#4  0x00007ffff67134a4 in start_thread (arg=0x7fffdd234700) at pthread_create.c:456
#5  0x00007ffff6455d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```
