### ISSUE TITLE
Rabbitmq plugin has error

### ISSUE THREAD

**Issue by mahamafzar** [netdata/netdata#7018]
##### RabbitMQ

Debug Message:
```
2019-10-08 13:55:35: python.d INFO: plugin[main] : using python v2
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : [rabbitmq] looking for 'rabbitmq.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : [rabbitmq] loading '/etc/netdata/python.d/rabbitmq.conf'
2019-10-08 13:55:35: python.d DEBUG: plugin[main] : [rabbitmq] '/etc/netdata/python.d/rabbitmq.conf' is loaded
2019-10-08 13:55:35: python.d INFO: plugin[main] : [rabbitmq] built 1 job(s) configs
2019-10-08 13:55:35: python.d DEBUG: rabbitmq[local] : urllib3 version: 1.21.1
2019-10-08 13:55:35: python.d ERROR: rabbitmq[local] : _get_data() returned no data or type is not <dict>
2019-10-08 13:55:35: python.d ERROR: rabbitmq[local] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2019-10-08 13:55:35: python.d INFO: plugin[main] : rabbitmq[local] : check failed
2019-10-08 13:55:35: python.d INFO: plugin[main] : no jobs to serve
2019-10-08 13:55:35: python.d INFO: plugin[main] : exiting from main...

```

**Comment by ilyam8** [comment]
Hi @mahamafzar 

This error is not related to the problem

> 2019-10-08 13:55:35: python.d ERROR: rabbitmq[local] : _get_data() returned no data or type is not <dict>


module does 3 requests (node_name extracted durin `api/overview` call):

 - `api/overview`
 - `api/nodes/<node_name>`
 - `api/vhosts`


get data code

https://github.com/netdata/netdata/blob/d75c125e59c42fe17a85563a47ecb40cc3cd2b38/collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py#L185-L206

could you change it to 

```python
    def _get_data(self):
        data = dict()

        stats = self.get_overview_stats()
        if stats is None:
            return None

        self.debug("overview: {0}".format(stats))
        data.update(stats)

        stats = self.get_nodes_stats()
        if stats is None:
            return None

        self.debug("node: {0}".format(stats))
        data.update(stats)

        stats = self.get_vhosts_stats()
        if stats is None:
            return None

        self.debug("vhosts: {0}".format(stats))
        data.update(stats)

        return data or None
```

and run module in debug mode again

**Comment by mahamafzar** [comment]
It seems that it works.
‌But still no data on charts
```
2019-10-08 14:53:59: python.d INFO: plugin[main] : using python v2
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : [rabbitmq] looking for 'rabbitmq.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : [rabbitmq] loading '/etc/netdata/python.d/rabbitmq.conf'
2019-10-08 14:53:59: python.d DEBUG: plugin[main] : [rabbitmq] '/etc/netdata/python.d/rabbitmq.conf' is loaded
2019-10-08 14:53:59: python.d INFO: plugin[main] : [rabbitmq] built 1 job(s) configs
2019-10-08 14:53:59: python.d DEBUG: rabbitmq[remote] : urllib3 version: 1.21.1
2019-10-08 14:53:59: python.d DEBUG: rabbitmq[remote] : overview: {'object_totals_channels': 22, 'object_totals_consumers': 22, 'object_totals_queues': 48, 'queue_totals_messages_unacknowledged': 0, 'object_totals_exchanges': 27, 'queue_totals_messages_ready': 0, 'object_totals_connections': 8}
2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : node: {'proc_used': 661, 'fd_used': 42, 'mem_used': 120823808, 'disk_free': 220417155072, 'run_queue': 1, 'sockets_used': 8}
2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : vhosts: {}
2019-10-08 14:54:00: python.d INFO: plugin[main] : rabbitmq[remote] : check success
CHART netdata.runtime_rabbitmq_remote '' 'Execution time for rabbitmq_remote' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : started, update frequency: 1
2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : overview: {'object_totals_channels': 22, 'object_totals_consumers': 22, 'object_totals_queues': 48, 'queue_totals_messages_unacknowledged': 0, 'object_totals_exchanges': 27, 'queue_totals_messages_ready': 0, 'object_totals_connections': 8}
2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : node: {'proc_used': 661, 'fd_used': 42, 'mem_used': 120823808, 'disk_free': 220417155072, 'run_queue': 1, 'sockets_used': 8}
2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : vhosts: {}
CHART rabbitmq_remote.erlang_processes '' 'Erlang Processes' 'processes' 'overview' 'rabbitmq.processes' line 60005 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'proc_used' 'used' absolute 1 1 ' '

BEGIN rabbitmq_remote.erlang_processes 0
SET 'proc_used' = 661
END

CHART rabbitmq_remote.file_descriptors '' 'File Descriptors' 'descriptors' 'overview' 'rabbitmq.file_descriptors' line 60003 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'fd_used' 'used' absolute 1 1 ' '

BEGIN rabbitmq_remote.file_descriptors 0
SET 'fd_used' = 42
END

CHART rabbitmq_remote.queued_messages '' 'Queued Messages' 'messages' 'overview' 'rabbitmq.queued_messages' stacked 60000 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'queue_totals_messages_ready' 'ready' absolute 1 1 ' '
DIMENSION 'queue_totals_messages_unacknowledged' 'unacknowledged' absolute 1 1 ' '

BEGIN rabbitmq_remote.queued_messages 0
SET 'queue_totals_messages_ready' = 0
SET 'queue_totals_messages_unacknowledged' = 0
END

CHART rabbitmq_remote.socket_descriptors '' 'Socket Descriptors' 'descriptors' 'overview' 'rabbitmq.sockets' line 60004 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'sockets_used' 'used' absolute 1 1 ' '

BEGIN rabbitmq_remote.socket_descriptors 0
SET 'sockets_used' = 8
END

CHART rabbitmq_remote.memory '' 'Memory' 'MiB' 'overview' 'rabbitmq.memory' area 60007 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'mem_used' 'used' absolute 1 1048576 ' '

BEGIN rabbitmq_remote.memory 0
SET 'mem_used' = 120823808
END

CHART rabbitmq_remote.global_counts '' 'Global Counts' 'counts' 'overview' 'rabbitmq.global_counts' line 60002 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'object_totals_channels' 'channels' absolute 1 1 ' '
DIMENSION 'object_totals_consumers' 'consumers' absolute 1 1 ' '
DIMENSION 'object_totals_connections' 'connections' absolute 1 1 ' '
DIMENSION 'object_totals_queues' 'queues' absolute 1 1 ' '
DIMENSION 'object_totals_exchanges' 'exchanges' absolute 1 1 ' '

BEGIN rabbitmq_remote.global_counts 0
SET 'object_totals_channels' = 22
SET 'object_totals_consumers' = 22
SET 'object_totals_connections' = 8
SET 'object_totals_queues' = 48
SET 'object_totals_exchanges' = 27
END

CHART rabbitmq_remote.disk_space '' 'Disk Space' 'GiB' 'overview' 'rabbitmq.disk_space' area 60008 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'disk_free' 'free' absolute 1 1073741824 ' '

BEGIN rabbitmq_remote.disk_space 0
SET 'disk_free' = 220417155072
END

CHART rabbitmq_remote.erlang_run_queue '' 'Erlang Run Queue' 'processes' 'overview' 'rabbitmq.erlang_run_queue' line 60006 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'run_queue' 'length' absolute 1 1 ' '

BEGIN rabbitmq_remote.erlang_run_queue 0
SET 'run_queue' = 1
END

BEGIN netdata.runtime_rabbitmq_remote 0
SET run_time = 38
END

2019-10-08 14:54:00: python.d DEBUG: rabbitmq[remote] : update => [OK] (elapsed time: 38, failed retries in a row: 0)
```

**Comment by OdysLam** [comment]
Hey @ilyam8,

I created a plugin based on the elasticsearch example but I get the same error, while elasticsearch runs as intended.

```
netdata@odyslam02:/usr/libexec/netdata/plugins.d$ /usr/libexec/netdata/plugins.d/python.d.plugin edgex debug trace
2019-11-24 16:52:21: python.d INFO: plugin[main] : using python v2
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : [edgex] looking for 'edgex.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : [edgex] loading '/etc/netdata/python.d/edgex.conf'
2019-11-24 16:52:21: python.d DEBUG: plugin[main] : [edgex] '/etc/netdata/python.d/edgex.conf' is loaded
2019-11-24 16:52:21: python.d INFO: plugin[main] : [edgex] built 1 job(s) configs
2019-11-24 16:52:21: python.d DEBUG: edgex[edgex_throughput] : urllib3 version: 1.21.1
2019-11-24 16:52:21: python.d ERROR: edgex[edgex_throughput] : URL is not defined or type is not <str>
2019-11-24 16:52:21: python.d ERROR: edgex[edgex_throughput] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2019-11-24 16:52:21: python.d INFO: plugin[main] : edgex[edgex_throughput] : check failed
2019-11-24 16:52:21: python.d INFO: plugin[main] : no jobs to serve
2019-11-24 16:52:21: python.d INFO: plugin[main] : exiting from main...
```

I use the debug functionality of python.d to test my plugin, after placing both the executable and the configuration at the appropriate directories.

Thanks for your time.

**Comment by ilyam8** [comment]
Hi

> 2019-11-24 16:52:21: python.d ERROR: edgex[edgex_throughput] : URL is not defined or type is not <str>


There is the check in default `check` method, you need to set `url` attribute or redefine `check`


> https://github.com/netdata/netdata/blob/4e22b01094f40448b1a28f9490e75b0d22886597/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py#L157-L164

**Comment by OdysLam** [comment]
Hey @ilyam8,

It just occurred to me that it might be related. Still, why does this results to an import error at Queue?

On a relevant note, do you have a specific styling guide for python code? (e.g to create a dictionary, you use dict() instead of {} )

**Comment by ilyam8** [comment]
> It just occurred to me that it might be related. Still, why does this results to an import error at Queue?



It is ok, there is always an import error for py2

https://github.com/netdata/netdata/blob/4e22b01094f40448b1a28f9490e75b0d22886597/collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py#L12-L15

You see it because of `trace` flag

**Comment by OdysLam** [comment]
Now everything makes sense again.

Thanks for your time :)

**Comment by ilyam8** [comment]
> use dict() instead of {}

Probably because of syntax highlighting, i prefer `str()` over `""` and dict() over `{}` sometimes, but it is not so important 😄
