### ISSUE TITLE
python: Unbound Collector unhandled exception

### ISSUE THREAD

**Issue by mkoubar** [netdata/netdata#7111]
python.d WARNING: plugin[main] : unbound[unbound] : unhandled exception on init : AttributeError("'NoneType' object has no attribute 'get'",), skipping the job

**Comment by ilyam8** [comment]
hi @mkg20001 

please do and share the output


> ./python.d.plugin debug trace unbound

**Comment by mkoubar** [comment]
root@develser02:~# /usr/libexec/netdata/plugins.d/python.d.plugin unbound debug trace 1
2019-10-16 13:13:08: python.d INFO: plugin[main] : using python v2
2019-10-16 13:13:08: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-16 13:13:08: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-16 13:13:08: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-16 13:13:08: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-16 13:13:08: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-16 13:13:08: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-16 13:13:09: python.d DEBUG: plugin[main] : [unbound] looking for 'unbound.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-16 13:13:09: python.d DEBUG: plugin[main] : [unbound] loading '/usr/lib/netdata/conf.d/python.d/unbound.conf'
2019-10-16 13:13:09: python.d DEBUG: plugin[main] : [unbound] '/usr/lib/netdata/conf.d/python.d/unbound.conf' is loaded
2019-10-16 13:13:09: python.d INFO: plugin[main] : [unbound] built 1 job(s) configs
2019-10-16 13:13:09: python.d DEBUG: unbound[unbound] : No unix socket specified. Trying TCP/IP socket.
2019-10-16 13:13:09: python.d DEBUG: unbound[unbound] : No host specified. Using: "localhost"
2019-10-16 13:13:09: python.d DEBUG: unbound[unbound] : No port specified. Using: "None"
2019-10-16 13:13:09: python.d DEBUG: unbound[unbound] : No valid TLS client certificate configuration found.
2019-10-16 13:13:09: python.d DEBUG: unbound[unbound] : No request specified. Using: "UBCT1 stats
"
2019-10-16 13:13:09: python.d DEBUG: unbound[unbound] : Unbound config: /etc/unbound/unbound.conf
2019-10-16 13:13:09: python.d WARNING: plugin[main] : unbound[unbound] : unhandled exception on init : AttributeError("'NoneType' object has no attribute 'get'",), skipping the job
2019-10-16 13:13:09: python.d INFO: plugin[main] : no jobs to serve
2019-10-16 13:13:09: python.d INFO: plugin[main] : exiting from main...

**Comment by ilyam8** [comment]
@mkoubar 

could you change this line

https://github.com/netdata/netdata/blob/05fd62ba5b8ed628310627311e284932cc96fa5f/collectors/python.d.plugin/unbound/unbound.chart.py#L216

to

```python
if conf.get('remote-control'):
```

and see if it fixes the problem

**Comment by mkoubar** [comment]
2019-10-16 13:27:47: python.d INFO: plugin[main] : using python v2
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : [unbound] looking for 'unbound.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : [unbound] loading '/usr/lib/netdata/conf.d/python.d/unbound.conf'
2019-10-16 13:27:47: python.d DEBUG: plugin[main] : [unbound] '/usr/lib/netdata/conf.d/python.d/unbound.conf' is loaded
2019-10-16 13:27:47: python.d INFO: plugin[main] : [unbound] built 1 job(s) configs
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : No unix socket specified. Trying TCP/IP socket.
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : No request specified. Using: "UBCT1 stats
"
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Unbound config: /etc/unbound/unbound.conf
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Extended stats: True
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Per-thread stats: True
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Connecting to: 127.0.0.1:8953
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Using key: /etc/unbound/unbound_control.key
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Using certificate: /etc/unbound/unbound_control.pem
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Creating socket to "127.0.0.1", port 8953
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Encapsulating socket with TLS
2019-10-16 13:27:47: python.d INFO: plugin[main] : unbound[local] : check failed
2019-10-16 13:27:47: python.d INFO: plugin[main] : no jobs to serve
2019-10-16 13:27:47: python.d INFO: plugin[main] : exiting from main...

**Comment by ilyam8** [comment]
ok, that is the problem part

https://github.com/netdata/netdata/blob/05fd62ba5b8ed628310627311e284932cc96fa5f/collectors/python.d.plugin/unbound/unbound.chart.py#L216-L222


if config is not loaded or there is no `remote-control` section w/ `control-use-cert` option set to yes we use default values

https://github.com/netdata/netdata/blob/05fd62ba5b8ed628310627311e284932cc96fa5f/collectors/python.d.plugin/unbound/unbound.chart.py#L225-L230


See
https://github.com/netdata/netdata/issues/4350

Same output

**Comment by ilyam8** [comment]
> 2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Using key: /etc/unbound/unbound_control.key
2019-10-16 13:27:47: python.d DEBUG: unbound[local] : Using certificate: /etc/unbound/unbound_control.pem

do you have these key/cert?

**Comment by mkoubar** [comment]
sure

**Comment by mkoubar** [comment]
remote-control:
control-enable: yes
control-interface: 127.0.0.1
control-port: 8953
server-key-file: "/etc/unbound/unbound_server.key"
server-cert-file: "/etc/unbound/unbound_server.pem"
control-key-file: "/etc/unbound/unbound_control.key"
control-cert-file: "/etc/unbound/unbound_control.pem"

**Comment by ilyam8** [comment]
See 

https://github.com/netdata/netdata/issues/4350#issuecomment-448315232

> Reason for that is, that netdata always use TLS to access control port 8953. However to access that port it needs access to /etc/unbound/unbound_control.* . By default this file has mod 644, so netdata process cant access it - > cant connect to 8953. If i make these files readable for netdata user, it start to work.

> https://github.com/netdata/netdata/issues/4350#issuecomment-535508814


> The key and cert used by the unbound-control aren't accessible from the outside of the root account and group.
> To fix it, I make them belong to the group netdata:
> chown root:netdata /etc/unbound/unbound_control.*
> After that, netdata can access the key and do the request to unbound to gather the data.

**Comment by ilyam8** [comment]
it should be

```yaml
  remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  control-port: 8953
  server-key-file: "/etc/unbound/unbound_server.key"
  server-cert-file: "/etc/unbound/unbound_server.pem"
  control-key-file: "/etc/unbound/unbound_control.key"
  control-cert-file: "/etc/unbound/unbound_control.pem"
```

do you have spaces in the config?

**Comment by mkoubar** [comment]
root@develser02:/etc/unbound# ls -l
total 32
-rwxrwxrwx 1 root    root    1687 Oct 16 13:48 unbound.conf
drwxr-xr-x 2 root    root    4096 Oct  9 09:48 unbound.conf.d
-rwxr-xr-x 1 root    root    1868 Oct 16 04:48 unbound.conf.run
-rw-r--r-- 1 root    netdata 2459 Oct  9 09:48 unbound_control.key
-rw-r--r-- 1 root    netdata 1330 Oct  9 10:26 unbound_control.pem
-rw-r--r-- 1 unbound unbound    5 Oct 16 13:05 unbound.pid
-rwxrwxrwx 1 root    root    2455 Oct  9 09:48 unbound_server.key
-rwxrwxrwx 1 root    root    1318 Oct  9 10:26 unbound_server.pem
root@develser02:/etc/unbound#

**Comment by mkoubar** [comment]
i tried all the issues on #4350 (comment) before

**Comment by mkoubar** [comment]
no space in config

**Comment by ilyam8** [comment]
> no space in config

this is wrong then, should be like in my [post](https://github.com/netdata/netdata/issues/7111#issuecomment-542644858)

**Comment by mkoubar** [comment]
if only spaces are added then I am getting :
root@develser02:~# /usr/libexec/netdata/plugins.d/python.d.plugin unbound debug trace 1
2019-10-16 14:03:35: python.d INFO: plugin[main] : using python v2
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : [unbound] looking for 'unbound.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : [unbound] loading '/usr/lib/netdata/conf.d/python.d/unbound.conf'
2019-10-16 14:03:35: python.d DEBUG: plugin[main] : [unbound] '/usr/lib/netdata/conf.d/python.d/unbound.conf' is loaded
2019-10-16 14:03:35: python.d INFO: plugin[main] : [unbound] built 1 job(s) configs
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : No unix socket specified. Trying TCP/IP socket.
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : No request specified. Using: "UBCT1 stats
"
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : Unbound config: /etc/unbound/unbound.conf
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : Extended stats: True
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : Per-thread stats: True
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : Using unix socket: 127.0.0.1
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : attempting DGRAM unix socket "127.0.0.1"
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : set socket connect timeout to: 2.0
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : Failed to connect DGRAM unix socket "127.0.0.1": [Errno 2] No such file or directory
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : attempting STREAM unix socket "127.0.0.1"
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : set socket connect timeout to: 2.0
2019-10-16 14:03:35: python.d DEBUG: unbound[local] : Failed to connect STREAM unix socket "127.0.0.1": [Errno 2] No such file or directory
2019-10-16 14:03:35: python.d INFO: plugin[main] : unbound[local] : check failed
2019-10-16 14:03:35: python.d INFO: plugin[main] : no jobs to serve
2019-10-16 14:03:35: python.d INFO: plugin[main] : exiting from main...

**Comment by ilyam8** [comment]
@Ferroin please take a look, i think either configuration is not valid or unbound code

```yaml
remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  control-port: 8953
  server-key-file: "/etc/unbound/unbound_server.key"
  server-cert-file: "/etc/unbound/unbound_server.pem"
  control-key-file: "/etc/unbound/unbound_control.key"
  control-cert-file: "/etc/unbound/unbound_control.pem"
```

https://github.com/netdata/netdata/blob/05fd62ba5b8ed628310627311e284932cc96fa5f/collectors/python.d.plugin/unbound/unbound.chart.py#L216-L222

Since there is no `control-use-cert` it uses `control-interface` (127.0.0.1) as unix_socket which invalid.

**Comment by mkoubar** [comment]
@ilyam8  @Ferroin 
Version 1.9.4
BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
root@develser02:~#
root@develser02:~#
root@develser02:~# unbound-control stats_noreset
thread0.num.queries=297
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=59
thread0.num.cachemiss=238
thread0.num.prefetch=0
thread0.num.zero_ttl=0
thread0.num.recursivereplies=238
thread0.requestlist.avg=0.470588
thread0.requestlist.max=3
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=0
thread0.requestlist.current.user=0
thread0.recursion.time.avg=0.151034
thread0.recursion.time.median=0.0812646
thread0.tcpusage=0
thread1.num.queries=295
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=48
thread1.num.cachemiss=247
thread1.num.prefetch=0
thread1.num.zero_ttl=0
thread1.num.recursivereplies=247
thread1.requestlist.avg=0.408907
thread1.requestlist.max=2
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=0
thread1.requestlist.current.user=0
thread1.recursion.time.avg=0.114882
thread1.recursion.time.median=0.0714342
thread1.tcpusage=0
thread2.num.queries=300
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=60
thread2.num.cachemiss=240
thread2.num.prefetch=2
thread2.num.zero_ttl=0
thread2.num.recursivereplies=240
thread2.requestlist.avg=0.326446
thread2.requestlist.max=2
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=0
thread2.requestlist.current.user=0
thread2.recursion.time.avg=0.162937
thread2.recursion.time.median=0.0679191
thread2.tcpusage=0
thread3.num.queries=357
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=68
thread3.num.cachemiss=289
thread3.num.prefetch=1
thread3.num.zero_ttl=0
thread3.num.recursivereplies=289
thread3.requestlist.avg=0.489655
thread3.requestlist.max=3
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=0
thread3.requestlist.current.user=0
thread3.recursion.time.avg=0.140225
thread3.recursion.time.median=0.0857429
thread3.tcpusage=0
total.num.queries=1249
total.num.queries_ip_ratelimited=0
total.num.cachehits=235
total.num.cachemiss=1014
total.num.prefetch=3
total.num.zero_ttl=0
total.num.recursivereplies=1014
total.requestlist.avg=0.426745
total.requestlist.max=3
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=0
total.requestlist.current.user=0
total.recursion.time.avg=0.141964
total.recursion.time.median=0.0765902
total.tcpusage=0
time.now=1571224641.754156
time.up=4320.530325
time.elapsed=4320.530325
mem.cache.rrset=135717
mem.cache.message=127389
mem.mod.iterator=16588
mem.mod.validator=0
mem.mod.respip=0
mem.streamwait=0
histogram.000000.000000.to.000000.000001=102
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=0
histogram.000000.000016.to.000000.000032=0
histogram.000000.000032.to.000000.000064=0
histogram.000000.000064.to.000000.000128=0
histogram.000000.000128.to.000000.000256=0
histogram.000000.000256.to.000000.000512=0
histogram.000000.000512.to.000000.001024=0
histogram.000000.001024.to.000000.002048=0
histogram.000000.002048.to.000000.004096=1
histogram.000000.004096.to.000000.008192=3
histogram.000000.008192.to.000000.016384=1
histogram.000000.016384.to.000000.032768=14
histogram.000000.032768.to.000000.065536=349
histogram.000000.065536.to.000000.131072=215
histogram.000000.131072.to.000000.262144=223
histogram.000000.262144.to.000000.524288=65
histogram.000000.524288.to.000001.000000=32
histogram.000001.000000.to.000002.000000=6
histogram.000002.000000.to.000004.000000=3
histogram.000004.000000.to.000008.000000=0
histogram.000008.000000.to.000016.000000=0
histogram.000016.000000.to.000032.000000=0
histogram.000032.000000.to.000064.000000=0
histogram.000064.000000.to.000128.000000=0
histogram.000128.000000.to.000256.000000=0
histogram.000256.000000.to.000512.000000=0
histogram.000512.000000.to.001024.000000=0
histogram.001024.000000.to.002048.000000=0
histogram.002048.000000.to.004096.000000=0
histogram.004096.000000.to.008192.000000=0
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.A=1050
num.query.type.TXT=14
num.query.type.AAAA=185
num.query.class.IN=1249
num.query.opcode.QUERY=1249
num.query.tcp=0
num.query.tcpout=0
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=0
num.query.flags.TC=0
num.query.flags.RD=1249
num.query.flags.RA=0
num.query.flags.Z=0
num.query.flags.AD=1
num.query.flags.CD=0
num.query.edns.present=58
num.query.edns.DO=0
num.answer.rcode.NOERROR=1052
num.answer.rcode.FORMERR=0
num.answer.rcode.SERVFAIL=157
num.answer.rcode.NXDOMAIN=40
num.answer.rcode.NOTIMPL=0
num.answer.rcode.REFUSED=0
num.answer.rcode.nodata=24
num.query.ratelimited=0
num.answer.secure=0
num.answer.bogus=0
num.rrset.bogus=0
num.query.aggressive.NOERROR=0
num.query.aggressive.NXDOMAIN=0
unwanted.queries=0
unwanted.replies=0
msg.cache.count=221
rrset.cache.count=244
infra.cache.count=4
key.cache.count=0
num.query.authzone.up=0
num.query.authzone.down=0
root@develser02:~#

**Comment by ilyam8** [comment]
@mkoubar 

could you test #7112 ?

please install my branch and 

> ./python.d.plugin debug trace unbound

**Comment by mkoubar** [comment]
@ilyam8 I guess there is an issue with the compiled unbound on that server. I tried all the same steps back on another one with  the same conf files on both ( unbound and python ) it seems working fine 
I need to check back the issue with the compiled server. :)

**Comment by ilyam8** [comment]
Ok, anyway there is a problem

> python.d WARNING: plugin[main] : unbound[unbound] : unhandled exception on init : AttributeError("'NoneType' object has no attribute 'get'",), skipping the job

i will fix it in the PR


I plan to add some changes to the PR, when it is ready i will ask you to test it.

**Comment by mkoubar** [comment]
@ilyam8 thanks and great job

**Comment by mkoubar** [comment]
@ilyam8  after checking i found that when compiling unbound 1.9.4 on differnet distro debian and centos both have the same issue :
2019-10-17 02:49:41: python.d INFO: plugin[main] : using python v2
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : [unbound] looking for 'unbound.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : [unbound] loading '/usr/lib/netdata/conf.d/python.d/unbound.conf'
2019-10-17 02:49:41: python.d DEBUG: plugin[main] : [unbound] '/usr/lib/netdata/conf.d/python.d/unbound.conf' is loaded
2019-10-17 02:49:41: python.d INFO: plugin[main] : [unbound] built 1 job(s) configs
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : No unix socket specified. Trying TCP/IP socket.
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : No request specified. Using: "UBCT1 stats
"
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Unbound config: /etc/unbound/unbound.conf
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Extended stats: True
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Per-thread stats: True
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Connecting to: 127.0.0.1:8953
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Using key: /etc/unbound/unbound_control.key
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Using certificate: /etc/unbound/unbound_control.pem
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Creating socket to "127.0.0.1", port 8953
2019-10-17 02:49:41: python.d DEBUG: unbound[local] : Encapsulating socket with TLS
2019-10-17 02:49:41: python.d INFO: plugin[main] : unbound[local] : check failed
2019-10-17 02:49:41: python.d INFO: plugin[main] : no jobs to serve
2019-10-17 02:49:41: python.d INFO: plugin[main] : exiting from main...

**Comment by ilyam8** [comment]
@mkoubar 

could you install #7112 ?

 - git clone https://github.com/ilyam8/netdata --branch=unbound_fix netdata_unbound_fix
 - cd netdata_unbound_fix
 - sudo ./netdata-installer.sh

**Comment by mkoubar** [comment]
ok i will check and inform you 👍

**Comment by mkoubar** [comment]
@ilyam8 

2019-10-17 09:36:40: python.d INFO: plugin[main] : using python v2
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : [unbound] looking for 'unbound.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : [unbound] loading '/usr/lib/netdata/conf.d/python.d/unbound.conf'
2019-10-17 09:36:40: python.d DEBUG: plugin[main] : [unbound] '/usr/lib/netdata/conf.d/python.d/unbound.conf' is loaded
2019-10-17 09:36:40: python.d INFO: plugin[main] : [unbound] built 1 job(s) configs
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : No unix socket specified. Trying TCP/IP socket.
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : No request specified. Using: "UBCT1 stats
"
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Loading Unbound config: /etc/unbound/unbound.conf
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Extended stats: True
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Per-thread stats: True
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Connecting to: 127.0.0.1:8953
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Using key: /etc/unbound/unbound_control.key
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Using certificate: /etc/unbound/unbound_control.pem
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Creating socket to "127.0.0.1", port 8953
2019-10-17 09:36:40: python.d DEBUG: unbound[local] : Encapsulating socket with TLS
2019-10-17 09:36:40: python.d ERROR: unbound[local] : unhandled exception during connect : AttributeError("'module' object has no attribute 'PROTOCOL_TLS'",)
2019-10-17 09:36:40: python.d ERROR: unbound[local] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 170, in _connect
    if self._connect2socket(res):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 84, in _connect2socket
    self.key, self.cert, ssl.CERT_NONE, ssl.PROTOCOL_TLS
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'

2019-10-17 09:36:40: python.d INFO: plugin[main] : unbound[local] : check failed
2019-10-17 09:36:40: python.d INFO: plugin[main] : no jobs to serve
2019-10-17 09:36:40: python.d INFO: plugin[main] : exiting from main...

**Comment by mkoubar** [comment]
perfect  you can close the issue, Great :))
