### ISSUE TITLE
mysql_local.slave_running: chart not found

### ISSUE THREAD

**Issue by arabiran** [netdata/netdata#7648]
mysql_local.slave_running: chart not found on url "/api/v1/chart?
I want to monitor Slave Status but get this error
But all other chart is work.

**Comment by ilyam8** [comment]
Hi @arabiran. Replication charts are:

https://github.com/netdata/netdata/blob/ef0be0c5064b1614a13fa26e8f5f5a8bfd253698/collectors/python.d.plugin/mysql/mysql.chart.py#L569-L581

**Comment by arabiran** [comment]
Hi @ilyam8 
I Did not understand what you mean.
please let me know how to set or how to use.
this is my setting.
 <div style="width: 15%; display: inline-block;">
        <div data-netdata="mysql_local.slave_behind"
            data-chart-library="easypiechart"
            data-after="-60"
             data-points="60"

Please advise me

**Comment by ilyam8** [comment]
@arabiran probably i am missing something

> [/api/v1/chart](https://registry.my-netdata.io/swagger/#/default/get_chart)

Required query parameter is `chart id`

> The id of the chart as returned by the /charts call.


Example:

> /api/v1/chart?chart=system.cpu

I see no `slave_running` chart in the [mysql collector](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mysql/mysql.chart.py).

___

> mysql_local.slave_running: chart not found on url "/api/v1/chart?


Where did you get the error? Are you building custom dashboard? Do you see replication charts on the netdata's dashboard? (see `slave` subsection of the mysql job).

**Comment by arabiran** [comment]
@ilyam8 
Yes i building custom dashboard. But everyting in Ok Just some chart no working.

i get error in my custom dashboard.
mysql_local.slave_behind: chart not found on url "/api/v1/chart?chart=mysql_local.slave_behind"
and i see slave_running in /usr/libexec/netdata/python.d/mysql.chart.py .
![Git-Screenshot from 2020-01-01 16-40-13](https://user-images.githubusercontent.com/43862608/71641710-99d81780-2cb5-11ea-802f-516237d6983a.png)

**Comment by ilyam8** [comment]
`slave_running` is the func

https://github.com/netdata/netdata/blob/ef0be0c5064b1614a13fa26e8f5f5a8bfd253698/collectors/python.d.plugin/mysql/mysql.chart.py#L155-L156

> Are you building custom dashboard? Do you see replication charts on the netdata's dashboard? (see slave subsection of the mysql job).

You didnt answer ^^

To get replication metrics you need:
 - have replication configured
 - grant additional permissions to the user, see

https://github.com/netdata/netdata/blob/ef0be0c5064b1614a13fa26e8f5f5a8bfd253698/collectors/python.d.plugin/mysql/mysql.conf#L102-L106

**Comment by arabiran** [comment]
# If you need to monitor mysql replication too, use this instead: 
 # 
 # > create user 'netdata'@'localhost'; 
 # > grant replication client on *.* to 'netdata'@'localhost'; 
 # > flush privileges; 

I Did but still no working 
Chart is not found: mysql_local.Max_used_connections
Chart is not found: mysql_local.slave_behind
i am so thnaks for your Replay @ilyam8

**Comment by arabiran** [comment]
@ilyam8 
/usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
2020-01-01 18:31:39: python.d INFO: plugin[main] : using python v2
2020-01-01 18:31:39: python.d INFO: plugin[main] : starting setup
2020-01-01 18:31:39: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-01-01 18:31:39: python.d INFO: plugin[main] : config found, loading config '/usr/lib/netdata/conf.d/python.d.conf'
2020-01-01 18:31:39: python.d INFO: plugin[main] : config successfully loaded
2020-01-01 18:31:39: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2020-01-01 18:31:39: python.d INFO: plugin[checker] : starting...
2020-01-01 18:31:39: python.d INFO: plugin[checker] : mysql : checking
2020-01-01 18:31:39: python.d INFO: plugin[checker] : mysql : source successfully loaded
2020-01-01 18:31:39: python.d INFO: plugin[checker] : mysql : found config file '/etc/netdata/python.d/mysql.conf'
Process ModuleChecker-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 204, in run
    while self.run_once():
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 218, in run_once
    result = self.do_task(task)
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 269, in do_task
    jobs = module.create_jobs()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 405, in create_jobs
    return [Job(self.source.Service, self.name, conf) for conf in jobs_conf or self.gather_jobs_configs()]
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 381, in gather_jobs_configs
    job_names = [v for v in self.config if isinstance(self.config[v], dict)]
TypeError: string indices must be integers, not str

**Comment by ilyam8** [comment]
@arabiran please update netdata to the latest version

**Comment by arabiran** [comment]
I use mysql 5.5 
Is it problem? for netdata to show replication status?

**Comment by ilyam8** [comment]
I mean update netdata not mysql.

**Comment by arabiran** [comment]
Hi Mr @ilyam8 
netdata v1.19.0-519-nightly
mysql  Ver 14.14 Distrib 5.5.8

1- create user 'netdata'@'localhost'; 
2- grant replication client on *.* to 'netdata'@'localhost'; 
3- flush privileges; 

/usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
2020-02-17 10:27:40: python.d INFO: plugin[main] : using python v2
2020-02-17 10:27:40: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-02-17 10:27:40: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2020-02-17 10:27:40: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2020-02-17 10:27:40: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-02-17 10:27:40: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2020-02-17 10:27:40: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-02-17 10:27:40: python.d WARNING: plugin[main] : [mysql] error on loading source : SyntaxError('invalid syntax', ('/usr/lib/python2.6/site-packages/pymysql/connections.py', 79, 19, '    FIELD_TYPE.BIT,\n')), skipping it
2020-02-17 10:27:40: python.d INFO: plugin[main] : no jobs to run

Still chart=mysql_local.slave_running  resulte Chart is not found: mysql_local.slave_running

but Other mysql chart is work nice

**Comment by arabiran** [comment]
resolve my problem 
my replication is not started and I start replication and chart is ok

Thank's
