### ISSUE TITLE
Cannot add order dynamically to plugin: 'Service' object has no attribute 'order'

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7913]
##### Question summary
I'm writing a plugin to connect to my open nebula server and I want my `order` and `definitions` get updated every  time the script runs so I have something like this in my code:
```
from bases.FrameworkServices.ExecutableService import SimpleService

import pyone


ORDER = [
]

CHARTS = {
   
}


class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.url = self.configuration.get('url')
        self.username = self.configuration.get('user')
        self.password = self.configuration.get('pass')

    @staticmethod
    def check(): return True

    def _read_vms_from_opennebula(self):
        session = self.username + ":" + self.password
        one = pyone.OneServer(self.url, session=session)
        vms = {}
        hostpool = one.hostpool.info()
        for host in hostpool.HOST:
            self.order.append(host.NAME)
           # Code to generate definitions`
# Rest of the code...
```
But when I run it in the debug mode I get this error:
```
2020-01-29 21:55:03: python.d ERROR: one[local] : update() unhandled exception: 'Service' object has no attribute 'order'
2020-01-29 21:55:03: python.d ERROR: one[local] : Traceback (most recent call last):
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 190, in run
    updated = self.update(interval=since)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 215, in update
    data = self.get_data()
  File "/opt/netdata/usr/libexec/netdata/python.d/one.chart.py", line 246, in get_data
    vms = self._read_vms_from_opennebula()
  File "/opt/netdata/usr/libexec/netdata/python.d/one.chart.py", line 226, in _read_vms_from_opennebula
    self.order.append(host.NAME)
AttributeError: 'Service' object has no attribute 'order'
```
Is there any way to solve my problem?

##### OS / Environment
Ubuntu 18
netdata v1.19.0
##### Component Name
plugin.d
##### Expected results
Generate dynamic definitions and order

**Comment by ilyam8** [comment]
Hi @yasharne 
There is no `order` and `definition` in runtime, there is only `charts`. 

SimpleServie deletes `order` and `definition` in `create` (called once, right after `check`)

see

https://github.com/netdata/netdata/blob/ee0f3c0fd856778085738a287d38afbb100c0a76/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py#L129-L171


charts

> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/charts.py


___

something like this, not working example, it is just to show you the idea

```python
class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        ...
        self.collected_hosts = set()


    def _read_vms_from_opennebula(self):
        session = self.username + ":" + self.password
        one = pyone.OneServer(self.url, session=session)
        vms = {}
        hostpool = one.hostpool.info()
        for host in hostpool.HOST:
            if host in self.collected_hosts:
                continue
            self.collected_hosts.add(host)
            self.add_hosts_charts(host)

    def add_hosts_charts(self):
        ...
```

check rabbitmq module, it add vhosts charts in runtime

https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
