### ISSUE TITLE
Does UrlService allow for API queries?

### ISSUE THREAD

**Issue by snub-fighter** [netdata/netdata#7967]
I have my own query that functions and Im trying to utilize the UrlService instead if possible to just grab the API information.  Is this supposed to work?

```python

from bases.FrameworkServices.UrlService import UrlService

ORDER = [
    'connections',
    'requests',
    'connection_status',
    'connect_rate',
]

CHARTS = {
    'connections': {
        'options': [None, 'Active Connections', 'connections', 'active connections',
                    'nginx.connections', 'line'],
        'lines': [
            ['active']
        ]
    },
    'requests': {
        'options': [None, 'Requests', 'requests/s', 'requests', 'nginx.requests', 'line'],
        'lines': [
            ['requests', None, 'incremental']
        ]
    },
    'connection_status': {
        'options': [None, 'Active Connections by Status', 'connections', 'status',
                    'nginx.connection_status', 'line'],
        'lines': [
            ['reading'],
            ['writing'],
            ['waiting', 'idle']
        ]
    },
    'connect_rate': {
        'options': [None, 'Connections Rate', 'connections/s', 'connections rate',
                    'nginx.connect_rate', 'line'],
        'lines': [
            ['accepts', 'accepted', 'incremental'],
            ['handled', None, 'incremental']
        ]
    }
}


class Service(UrlService):
    def __init__(self, configuration=None, name=None):
        UrlService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.url = self.configuration.get('url', 'http://localhost:19999/api/v1/data?chart=apps.cpu')

    def _get_data(self):
        """
        Format data received from http request
        :return: dict
        """
        try:
            raw = self._get_raw_data().split(" ")
            print(raw)
            # return {'active': int(raw[2]),
            #         'requests': int(raw[9]),
            #         'reading': int(raw[11]),
            #         'writing': int(raw[13]),
            #         'waiting': int(raw[15]),
            #         'accepts': int(raw[7]),
            #         'handled': int(raw[8])}
        except (ValueError, AttributeError):
            return None
```

**Comment by ilyam8** [comment]
Hi @snub-fighter 

> Does UrlService allow for API queries?

UrlService does http request and returns response (`_get_raw_data`).

python.d.plugin has debug mode, it will help you during developing, see

> https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module

**Comment by snub-fighter** [comment]
Im really enjoying netdata and I apologize if Im asking simplistic questions.   I used the existing nginx module as a framework for building the above.

I have viewed that and used the debug.  All Im getting is that the http request times out.  I see that it identifies the port for me so I dont have to put in a param (as far as I can tell).  I have tested **independent of netdata** on the same box using python making a query to the API and get the following successful response.  Making a direct query from netdata it fails.  

Could this be related to ?chart=apps.cpu param or that the apps.cpu is constantly updating?

**Custom Python Script**
This script is simply an standard API query and putting the latest results into a dictionary and returning it.  The point here is that Im querying the API from the same box netdata is on so it should not be a security issue but appears to be how I am querying the API from the netdata module.
```
user@cns-usa-west:/usr/libexec/netdata/python.d# python3 csccpu.chart.py 
aggregate_group_value 6.5533 casinocoin 0 free_cpu 93.44669999999999
{'other_cpu_procs': 6.55, 'casinocoin': 0, 'free_cpu': 93.45}
```

**Netdata Error : Snippet**
```
2020-02-05 21:58:49: python.d ERROR: csc_aggregator[csc_aggregator] : Url: http://localhost:19999/api/v1/data?chart=apps.cpu. Error: HTTPConnectionPool(host='localhost', port=19999): Max retries exceeded with url: /api/v1/data?chart=apps.cpu (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=19999): Read timed out. (read timeout=1)",))
2020-02-05 21:58:49: python.d ERROR: csc_aggregator[csc_aggregator] : Traceback (most recent call last):
```
**Netdata Error : Full**

```

netdata@cns-usa-west:/usr/share/netdata$ /usr/libexec/netdata/plugins.d/python.d.plugin csc_aggregator debug trace        
2020-02-05 22:17:13: python.d INFO: plugin[main] : using python v2
2020-02-05 22:17:13: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-02-05 22:17:13: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2020-02-05 22:17:13: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2020-02-05 22:17:13: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-02-05 22:17:13: python.d WARNING: plugin[main] : 'pythond-jobs-statuses.json' was not found
2020-02-05 22:17:13: python.d DEBUG: plugin[main] : [csc_aggregator] looking for 'csc_aggregator.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2020-02-05 22:17:13: python.d WARNING: plugin[main] : [csc_aggregator] 'csc_aggregator.conf' was not found
2020-02-05 22:17:13: python.d INFO: plugin[main] : [csc_aggregator] built 1 job(s) configs
2020-02-05 22:17:13: python.d DEBUG: csc_aggregator[csc_aggregator] : urllib3 version: 1.21.1
2020-02-05 22:17:15: python.d ERROR: csc_aggregator[csc_aggregator] : Url: http://localhost:19999/api/v1/data?chart=apps.cpu. Error: HTTPConnectionPool(host='localhost', port=19999): Max retries exceeded with url: /api/v1/data?chart=apps.cpu (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=19999): Read timed out. (read timeout=1)",))
2020-02-05 22:17:15: python.d ERROR: csc_aggregator[csc_aggregator] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 122, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager, **kwargs)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 151, in _get_raw_data_with_status
    **kwargs
  File "/usr/libexec/netdata/python.d/python_modules/urllib3/request.py", line 67, in request
    **urlopen_kw)
  File "/usr/libexec/netdata/python.d/python_modules/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/libexec/netdata/python.d/python_modules/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/libexec/netdata/python.d/python_modules/urllib3/connectionpool.py", line 679, in urlopen
    **response_kw)
  File "/usr/libexec/netdata/python.d/python_modules/urllib3/connectionpool.py", line 650, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/libexec/netdata/python.d/python_modules/urllib3/util/retry.py", line 389, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='localhost', port=19999): Max retries exceeded with url: /api/v1/data?chart=apps.cpu (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=19999): Read timed out. (read timeout=1)",))

2020-02-05 22:17:15: python.d ERROR: csc_aggregator[csc_aggregator] : _get_data() returned no data or type is not <dict>
2020-02-05 22:17:15: python.d ERROR: csc_aggregator[csc_aggregator] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-02-05 22:17:15: python.d INFO: plugin[main] : csc_aggregator[csc_aggregator] : check failed
2020-02-05 22:17:15: python.d INFO: plugin[main] : no jobs to serve
2020-02-05 22:17:15: python.d INFO: plugin[main] : exiting from main...
```

**Comment by ilyam8** [comment]
> 2020-02-05 22:17:15: python.d ERROR: csc_aggregator[csc_aggregator] : Url: http://localhost:19999/api/v1/data?chart=apps.cpu. Error: HTTPConnectionPool(host='localhost', port=19999): Max retries exceeded with url: /api/v1/data?chart=apps.cpu (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=19999): Read timed out. (read timeout=1)",))

> Read timed out. (read timeout=1)"

try to increase timeout:

- `timeout: N` in the job config
- `self.timeout = N` in the code
