### ISSUE TITLE
Need help configuring new services in Netdata

### ISSUE THREAD

**Issue by HighWatersDev** [netdata/netdata#7975]
##### Question summary
I install Netdata on my server using one-liner installer and it discovers the basic services just fine. However, I try to add new service configuration files under python.d directory but nothing gets discovered and no new dashboards show up for those services. The example would be apache.conf/postgresql.conf. All of the files under /etc/netdata directory owned by root:root even though I ran the installer using non-privileged account.
##### OS / Environment
Linux Red Hat 7.7
##### Component Name
Apache/2.4.6, Postgres/12.1
##### Expected results
I expected those services to be discovered and added to the dashboard after I added .conf files under /etc/netdata/python.d directory.

**Comment by ilyam8** [comment]
Hi @HighWatersDev 

Try to run python.d.plugin in debug mode

https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module

**Comment by HighWatersDev** [comment]
Looks like I uncommented things that were not meant to be uncommented

bash-4.2$ /usr/libexec/netdata/plugins.d/python.d.plugin postgres debug trace
2020-02-04 11:40:34: python.d INFO: plugin[main] : using python v2
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
     64 # Connections can be configured with the following options:
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : [postgres] looking for 'postgres.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2020-02-04 11:40:34: python.d DEBUG: plugin[main] : [postgres] loading '/etc/netdata/python.d/postgres.conf'
2020-02-04 11:40:34: python.d ERROR: plugin[main] : [postgres] error on loading '/etc/netdata/python.d/postgres.conf' : ParserError()
2020-02-04 11:40:34: python.d ERROR: plugin[main] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 244, in load_module_config
    config.load(abs_path)
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 188, in load
    self.config.update(load_config(abs_path) or dict())
  File "/usr/libexec/netdata/python.d/python_modules/bases/loaders.py", line 46, in load_config
    return load_yaml(stream)
  File "/usr/libexec/netdata/python.d/python_modules/bases/loaders.py", line 39, in load_yaml
    return loader.get_single_data()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/constructor.py", line 38, in get_single_data
    node = self.get_single_node()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 40, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/parser.py", line 99, in check_event
    self.current_event = self.state()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/parser.py", line 175, in parse_document_start
    self.peek_token().start_mark)
ParserError: expected '<document start>', but found '<block mapping start>'
  in "/etc/netdata/python.d/postgres.conf", line 110, column 1

When I commented everything back out, I see that it's failing to connect to DB

2020-02-04 11:44:49: python.d ERROR: postgres[tcpipv4] : failed to connect to {'database': 'postgres', 'port': 5432, 'host': '127.0.0.1', 'user': 'postgres', 'connect_timeout': 2, 'password': '*****', 'options': '-c statement_timeout=5000'}
2020-02-04 11:44:49: python.d ERROR: postgres[tcpipv4] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

As expected, this was a user issue.

**Comment by ilyam8** [comment]
> Looks like I uncommented things that were not meant to be uncommented

Yes.

> As expected, this was a user issue.

Is the problem solved?

**Comment by HighWatersDev** [comment]
The issue is resolved. However, if I may suggest making it more distinct in conf files which lines are as guidance and which lines actually need to be uncommented.
Thanks for your help!

**Comment by ilyam8** [comment]
There is an example in the readme

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/postgres#configuration


Description in the config

https://github.com/netdata/netdata/blob/b5dcce7238a325a30223a573eabb73fcd2d927e0/collectors/python.d.plugin/postgres/postgres.conf#L50-L63

List of predefined jobs

https://github.com/netdata/netdata/blob/b5dcce7238a325a30223a573eabb73fcd2d927e0/collectors/python.d.plugin/postgres/postgres.conf#L110-L134

___

> if I may suggest making it more distinct in conf files which lines are as guidance and which lines actually need to be uncommented.

Ofc, what was not clear?
