### ISSUE TITLE
python.d ERROR: mongodb: local: Type: <type 'exceptions.KeyError'>, error: 'mapped'

### ISSUE THREAD

**Issue by diwap** [netdata/netdata#8307]
##### Bug report summary

While trying to monitor mongod using netdata, I got KeyError

##### OS / Environment

```
         Icon name: computer-vm
           Chassis: vm
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.11.6.el7.x86_64
      Architecture: x86-64
```

##### Netdata version

 netdata v1.12.0-rc2-24-ga521498

##### Component Name

python.d.plugin mongodb

##### Steps To Reproduce

1. `sudo su -s /bin/bash netdata`
2. `/usr/libexec/netdata/plugins.d/python.d.plugin mongodb debug trace`

##### Output

```
2020-03-05 04:04:50: python.d INFO: plugin: main: Using python 2
2020-03-05 04:04:50: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d.conf'
2020-03-05 04:04:50: python.d DEBUG: plugin: main: module load source: 'mongodb' => [OK]
2020-03-05 04:04:50: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d/mongodb.conf'
2020-03-05 04:04:50: python.d DEBUG: plugin: main: job initialization: 'mongodb local' => ['OK']
2020-03-05 04:04:50: python.d DEBUG: plugin: main: module status: 'mongodb' => [OK] (jobs: 1)
2020-03-05 04:04:50: python.d ERROR: mongodb: local: Type: <type 'exceptions.KeyError'>, error: 'mapped'
2020-03-05 04:04:50: python.d ERROR: mongodb: local: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/mongodb.chart.py", line 449, in check
    data = self._get_data()
  File "/usr/libexec/netdata/python.d/mongodb.chart.py", line 654, in _get_data
    to_netdata['mapped'])
KeyError: 'mapped'

2020-03-05 04:04:50: python.d INFO: mongodb: local: check() => [FAILED]
```

**Comment by ilyam8** [comment]
Hi @diwap 

`v1.12.0` is ancient, the bug is fixed in latest.

> https://github.com/netdata/netdata/pull/5931

**Comment by diwap** [comment]
Got it
