### ISSUE TITLE
Options "page cache size" & "dbengine disk space" not used?

### ISSUE THREAD

**Issue by Triodes** [netdata/netdata#8548]
### Question summary
In an attempt to make netdata keep metrics for a longer time I decided to set the memory mode to 'dbengine' and the 'page cache size' and 'dbengine disk space' options to 32 and 256 respectively. I restarted netdata and came back a while later only to find that the retention period seemed unchanged. I then downloaded the config file from `http://localhost:19999/netdata.conf` and this was the first part of the result

```config
[global]
        run as user = netdata
        memory mode = dbengine

        # option 'page cache size' is not used.
        page cache size = 64

        # option 'dbengine disk space' is not used.
        dbengine disk space = 512
```

The comments above the 2 options above are interesting as they indicate that these option are either non-existent or not used because of some other configuration. I triple checked the spelling and can find no errors. Does anyone know what I am doing wrong here?

##### OS / Environment
Ubuntu 16.04.6 LTS on GCP

**Comment by mfundul** [comment]
That's strange. Do you maybe have a duplicate `memory mode =` line somewhere? Can you share your `var/log/netdata/error.log`?

**Comment by Triodes** [comment]
```
2020-03-31 12:52:40: netdata INFO : Out-Of-Memory (OOM) score is already set to the wanted value -900
2020-03-31 12:52:40: netdata INFO : netdata started on pid 4580.
2020-03-31 12:52:40: netdata INFO : Host 'mcserver' (at registry as 'mcserver') with guid '345688d0-7083-11ea-8568-42010aa40018' initialized, os 'linux', timezone 'Etc/UTC', tags '', update every 1, memory mode save, history entries 3996, streaming disabled (to '' with api key ''), health enabled, cache_dir '/var/cache/netdata', varlib_dir '/var/lib/netdata', health_log '/var/lib/netdata/health/health-log.db', alarms default handler '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
2020-03-31 12:52:40: netdata INFO : netdata initialization completed. Enjoy real-time performance monitoring!
2020-03-31 12:52:40: netdata INFO : HEALTH thread created with task id 4597
2020-03-31 12:52:40: netdata INFO : PLUGINS.D thread created with task id 4598
2020-03-31 12:52:40: netdata ERROR: PLUGINSD: Cannot open plugins directory '/etc/netdata/custom-plugins.d'. (errno 2, No such file or directory)
2020-03-31 12:52:40: netdata INFO : BACKEND: thread created with task id 4596
2020-03-31 12:52:40: netdata INFO : BACKEND: thread exiting
2020-03-31 12:52:40: netdata INFO : Multi-threaded WEB SERVER thread created with task id 4599
2020-03-31 12:52:40: netdata INFO : Listening on 'tcp:0.0.0.0:19999'
2020-03-31 12:52:40: netdata INFO : STATSD main thread created with task id 4600
2020-03-31 12:52:40: netdata INFO : IDLEJITTER thread created with task id 4595
2020-03-31 12:52:40: netdata INFO : TC thread created with task id 4594
2020-03-31 12:52:40: netdata INFO : CGROUP plugin thread created with task id 4593
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' running on pid 4612
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' running on pid 4613
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin' running on pid 4614
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/apps.plugin' running on pid 4615
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/fping.plugin' running on pid 4617
2020-03-31 12:52:40: netdata INFO : STATSD collector thread No 2 created with task id 4606
2020-03-31 12:52:40: netdata INFO : POLLFD: LISTENER: listening on 'udp:127.0.0.1:8125'
2020-03-31 12:52:40: netdata INFO : POLLFD: LISTENER: listening on 'tcp:127.0.0.1:8125'
2020-03-31 12:52:40: netdata INFO : DISKSPACE thread created with task id 4592
2020-03-31 12:52:40: netdata INFO : PROC Plugin thread created with task id 4591
2020-03-31 12:52:40: apps.plugin INFO : started on pid 4615
2020-03-31 12:52:40: fping.plugin: FATAL: no hosts configured in '/etc/netdata/fping.conf' - nothing to do.
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/fping.plugin' called DISABLE. Disabling it.
2020-03-31 12:52:40: netdata ERROR: PLUGINSD: plugin '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/fping.plugin' disconnected.
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/fping.plugin' on pid 4617 stopped after 0 successful data collections (ENDs).
2020-03-31 12:52:40: netdata ERROR: child pid 4617 exited with code 1. (errno 9, Bad file descriptor)
2020-03-31 12:52:40: netdata ERROR: PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/fping.plugin' exited with error code 1. Disabling it.
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/fping.plugin' thread exiting
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin", line 31, in <module>
    from bases.loaders import ModuleAndConfigLoader
  File "/usr/lib/x86_64-linux-gnu/netdata/python.d/python_modules/bases/loaders.py", line 15, in <module>
    from pyyaml2 import SafeLoader as YamlSafeLoader
ImportError: No module named pyyaml2
2020-03-31 12:52:40: netdata ERROR: PLUGINSD: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin : read failed.
2020-03-31 12:52:40: netdata ERROR: PLUGINSD: plugin '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' disconnected.
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' on pid 4613 stopped after 0 successful data collections (ENDs).
2020-03-31 12:52:40: netdata ERROR: child pid 4613 exited with code 1. (errno 9, Bad file descriptor)
2020-03-31 12:52:40: netdata ERROR: PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' exited with error code 1. Disabling it.
2020-03-31 12:52:40: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' thread exiting
2020-03-31 12:52:40: charts.d: INFO: main: started from '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' with options: 1
2020-03-31 12:52:40: charts.d: INFO: apache: is disabled. Add a line with apache=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:40: charts.d: INFO: cpu_apps: is disabled. Add a line with cpu_apps=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:40: charts.d: INFO: cpufreq: is disabled. Add a line with cpufreq=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:40: charts.d: INFO: example: is disabled. Add a line with example=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: exim: is disabled. Add a line with exim=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: hddtemp: is disabled. Add a line with hddtemp=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: node.d.plugin: ERROR: Cannot load module's stiebeleltron config from /etc/netdata/node.d/stiebeleltron.conf exception: Error: ENOENT: no such file or directory, open '/etc/netdata/node.d/stiebeleltron.conf', using internal defaults.
2020-03-31 12:52:41: charts.d: INFO: load_average: is disabled. Add a line with load_average=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: mem_apps: is disabled. Add a line with mem_apps=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: mysql: is disabled. Add a line with mysql=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: node.d.plugin: ERROR: Cannot load module's snmp config from /etc/netdata/node.d/snmp.conf exception: Error: ENOENT: no such file or directory, open '/etc/netdata/node.d/snmp.conf', using internal defaults.
2020-03-31 12:52:41: node.d.plugin: ERROR: Cannot load module's sma_webbox config from /etc/netdata/node.d/sma_webbox.conf exception: Error: ENOENT: no such file or directory, open '/etc/netdata/node.d/sma_webbox.conf', using internal defaults.
2020-03-31 12:52:41: charts.d: INFO: nginx: is disabled. Add a line with nginx=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: node.d.plugin: ERROR: Cannot load module's named config from /etc/netdata/node.d/named.conf exception: Error: ENOENT: no such file or directory, open '/etc/netdata/node.d/named.conf', using internal defaults.
2020-03-31 12:52:41: charts.d: INFO: phpfpm: is disabled. Add a line with phpfpm=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: postfix: is disabled. Add a line with postfix=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: sensors: is disabled. Add a line with sensors=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: squid: is disabled. Add a line with squid=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: charts.d: INFO: tomcat: is disabled. Add a line with tomcat=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.cpu/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.mem/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: node.d.plugin: ERROR: Cannot load module's fronius config from /etc/netdata/node.d/fronius.conf exception: Error: ENOENT: no such file or directory, open '/etc/netdata/node.d/fronius.conf', using internal defaults.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.vmem/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: node.d.plugin: ERROR: named: local: Failed to make request, message: connect ECONNREFUSED 127.0.0.1:8888
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.threads/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata ERROR: PROCFILE: Cannot open file '/proc/net/ip_vs_stats' (errno 2, No such file or directory)
2020-03-31 12:52:41: netdata ERROR: PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 2, No such file or directory)
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.processes/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfsd' (errno 2, No such file or directory)
2020-03-31 12:52:41: netdata ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfs' (errno 2, No such file or directory)
2020-03-31 12:52:41: netdata ERROR: PROCFILE: Cannot open file '/proc/spl/kstat/zfs/arcstats' (errno 2, No such file or directory)
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.cpu_user/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.cpu_system/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.major_faults/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.minor_faults/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: charts.d: WARNING: ap: command 'iw' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.preads/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: charts.d: ERROR: ap: module's 'ap' check() function reports failure.
2020-03-31 12:52:41: charts.d: WARNING: apcupsd: command 'apcaccess' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.pwrites/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: charts.d: ERROR: apcupsd: module's 'apcupsd' check() function reports failure.
2020-03-31 12:52:41: charts.d: WARNING: nut: command 'upsc' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-03-31 12:52:41: charts.d: ERROR: nut: module's 'nut' check() function reports failure.
2020-03-31 12:52:41: charts.d: WARNING: opensips: command 'opensipsctl' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-03-31 12:52:41: charts.d: ERROR: opensips: module's 'opensips' check() function reports failure.
2020-03-31 12:52:41: charts.d: FATAL: main: No charts to collect data from.
2020-03-31 12:52:41: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' called DISABLE. Disabling it.
2020-03-31 12:52:41: netdata ERROR: PLUGINSD: plugin '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' disconnected.
2020-03-31 12:52:41: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' on pid 4612 stopped after 0 successful data collections (ENDs).
2020-03-31 12:52:41: netdata ERROR: PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' (pid 4612) does not generate useful output but it reports success (exits with 0). Will not start it again - it is disabled.. (errno 9, Bad file descriptor)
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.lreads/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.lwrites/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.files/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.sockets/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : File /var/cache/netdata/apps.pipes/charts.d.plugin.db is too old (last collected 129059 seconds ago, but the database is 3996 seconds). Clearing it.
2020-03-31 12:52:41: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin' called DISABLE. Disabling it.
2020-03-31 12:52:41: netdata ERROR: PLUGINSD: plugin '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin' disconnected.
2020-03-31 12:52:41: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin' on pid 4614 stopped after 0 successful data collections (ENDs).
2020-03-31 12:52:41: netdata ERROR: child pid 4614 killed by signal 15. (errno 9, Bad file descriptor)
2020-03-31 12:52:41: netdata ERROR: PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin' exited with error code -1. Disabling it.
2020-03-31 12:52:41: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/node.d.plugin' thread exiting
2020-03-31 12:52:51: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/charts.d.plugin' thread exiting
2020-03-31 12:52:52: cgroup-name.sh: INFO: cgroup 'init.scope' is called 'init.scope'
2020-03-31 12:52:52: cgroup-name.sh: INFO: cgroup 'system.slice_var-lib-lxcfs.mount' is called 'system.slice_var-lib-lxcfs.mount'
2020-03-31 12:52:52: cgroup-name.sh: INFO: cgroup 'system.slice_lxcfs.service' is called 'system.slice_lxcfs.service'

```

**Comment by Triodes** [comment]
It seems to state using `memory mode save` on line 3

**Comment by mfundul** [comment]
Does netdata actually work? Or does the service crash with a fatal error? It could be that it's been compiled without dbengine support.

**Comment by Triodes** [comment]
It works fine, metric retention is only 1 or 2 hours. I forgot which of the 2 exactly.

**Comment by mfundul** [comment]
From the `error.log` it is `memory mode save, history entries 3996` which is 1 hour.

**Comment by mfundul** [comment]
How did you install netdata?

**Comment by Triodes** [comment]
I forgot, so I looked it up in the history
https://github.com/phusion/netdata-ubuntu-16.04
```
sudo add-apt-repository ppa:phusion.nl/misc
sudo apt update
sudo apt install netdata
```
Totally unsupported backport by an unrelated company it seems 😄

**Comment by mfundul** [comment]
> 
> 
> I forgot, so I looked it up in the history
> https://github.com/phusion/netdata-ubuntu-16.04
> 
> ```
> sudo add-apt-repository ppa:phusion.nl/misc
> sudo apt update
> sudo apt install netdata
> ```
> 
> Totally unsupported backport by an unrelated company it seems 😄
> 
> I accidentally clicked on ubuntu 16 instead of 18 when creating my VM so netdata wasn't in the official repo's.
> Hence the installing from this repo listed above.
> 
> I'm creating another VM at the moment which is ubuntu 18 and see if it does work there. (which i'm guessing it will)
> 
> I'm going to stop trying to fix the ubuntu 16 install. Thanks for the help so far 👍

No worries, for official packages and installation methods look [here](https://docs.netdata.cloud/packaging/installer/). It should work for Ubuntu 16 as well.
