### ISSUE TITLE
elasticsearch plugin cannot get performance charts 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8610]
##### Bug report summary
Elasticsearch plugin sometimes only shows cluster health API:
![image](https://user-images.githubusercontent.com/7656049/78532100-e1fa5f00-77fb-11ea-876e-51618f54d346.png)
and sometimes it shows the other charts but apparently it cannot get the data all the time:
![image](https://user-images.githubusercontent.com/7656049/78532210-153cee00-77fc-11ea-94d3-9c2ef7a63b1f.png)
I tried to debug the plugin and this is the exception I get:
```
2020-04-06 11:07:23: python.d ERROR: elasticsearch[local] : Traceback (most recent call last):
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 122, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager, **kwargs)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 151, in _get_raw_data_with_status
    **kwargs
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3/request.py", line 67, in request
    **urlopen_kw)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3/connectionpool.py", line 679, in urlopen
    **response_kw)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3/connectionpool.py", line 650, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3/util/retry.py", line 389, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: /_cluster/stats (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=1)",))
```
I believe  if I set the timeout to 10 seconds, I will be fine, but I don't see any option to change this value
Netdata update interval is set to 5s
 
##### OS / Environment

```
Linux elastic-01.db.x.y.z 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 
netdata v1.19.0
##### Component Name

python.d

**Comment by ilyam8** [comment]
> MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: /_cluster/stats (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=1)",))

> (read timeout=1)",))


Hi @yasharne. You can change timeout in the config. I think it should be <= `update_every`.

```yaml
local:
 host: '127.0.0.1'
 port: '9200'
 timeout: 3
```

**Comment by yasharne** [comment]
Thanks @ilyam8 , this fixed the problem
