### ISSUE TITLE
apache web log collector doesnt work

### ISSUE THREAD

**Issue by sna-king** [netdata/netdata#8709]
i have installed netdata via docker on my test host. unfortunately web log collector modules(python and go)doesn't work. i have check the path and format and readability of log file and seems fine . so i run the python module in debug mode
```
2020-04-14 08:40:41: python.d INFO: web_log[apache_log] : Collected data: ['code', 'request', 'bytes_sent', 'resp_length', 'resp_time', 'address']
2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache_log] : check success
CHART netdata.runtime_web_log_apache '' 'Execution time for web_log_apache' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1
```

and one other interesting thing(which im not sure about) is that the debug trace showing that the related chart are working and it setting the data to the chart UI .for example :
```

BEGIN web_log_apache.response_time 1000561
SET 'resp_time_min' = 29365
SET 'resp_time_max' = 1720369
SET 'resp_time_avg' = 912180
END
```
i have test the same conf file in other server and it works but still nothing here!

**Comment by ilyam8** [comment]
@sna-king 👋 

Could you provide the whole debug output? I see it is only 4 lines.

**Comment by sna-king** [comment]
> 
> 
> @sna-king 👋
> 
> Could you provide the whole debug output? I see it is only 4 lines.
> 
> I would suggest to use go version.

of course

**Comment by sna-king** [comment]
```
2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[nginx_log2] : check failed
2020-04-14 08:40:41: python.d INFO: web_log[apache_log] : Collected data: ['code', 'request', 'bytes_sent', 'resp_length', 'resp_time', 'address']
2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache_log] : check success
CHART netdata.runtime_web_log_apache '' 'Execution time for web_log_apache' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2020-04-14 08:40:41: python.d DEBUG: web_log[apache_log] : started, update frequency: 1
2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache_log2] : already served by another job, skipping it
2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache_log3] : already served by another job, skipping it
2020-04-14 08:40:41: python.d INFO: web_log[apache_vhosts_log] : Collected data: ['request', 'code', 'bytes_sent', 'address']
2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache_vhosts_log] : check success
CHART netdata.runtime_web_log_apache_vhosts '' 'Execution time for web_log_apache_vhosts' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2020-04-14 08:40:41: python.d DEBUG: web_log[apache_vhosts_log] : started, update frequency: 1
2020-04-14 08:40:41: python.d ERROR: web_log[gunicorn_log] : /var/log/gunicorn/access.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[gunicorn_log] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[gunicorn_log] : check failed
2020-04-14 08:40:41: python.d ERROR: web_log[gunicorn_log2] : /var/log/gunicorn/gunicorn-access.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[gunicorn_log2] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[gunicorn_log2] : check failed
2020-04-14 08:40:41: python.d ERROR: web_log[apache_cache] : /var/log/apache/cache.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[apache_cache] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache_cache] : check failed
2020-04-14 08:40:41: python.d ERROR: web_log[apache2_cache] : /var/log/apache2/cache.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[apache2_cache] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[apache2_cache] : check failed
2020-04-14 08:40:41: python.d ERROR: web_log[httpd_cache] : /var/log/httpd/cache.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[httpd_cache] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[httpd_cache] : check failed
2020-04-14 08:40:41: python.d ERROR: web_log[squid_log1] : /var/log/squid3/access.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[squid_log1] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[squid_log1] : check failed
2020-04-14 08:40:41: python.d ERROR: web_log[squid_log2] : /var/log/squid/access.log not readable or not exist
2020-04-14 08:40:41: python.d ERROR: web_log[squid_log2] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-04-14 08:40:41: python.d INFO: plugin[main] : web_log[squid_log2] : check failed
CHART web_log_apache_vhosts.requests_per_ipproto '' 'Requests Per IP Protocol' 'requests/s' 'ip protocols' 'web_log.requests_per_ipproto' stacked 60007 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'req_ipv4' 'ipv4' incremental 1 1 ' '
DIMENSION 'req_ipv6' 'ipv6' incremental 1 1 ' '

BEGIN web_log_apache_vhosts.requests_per_ipproto 0
SET 'req_ipv4' = 0
SET 'req_ipv6' = 0
END

CHART web_log_apache_vhosts.clients_all '' 'All Time Unique Client IPs' 'unique ips' 'clients' 'web_log.clients_all' stacked 60009 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'unique_tot_ipv4' 'ipv4' absolute 1 1 ' '
DIMENSION 'unique_tot_ipv6' 'ipv6' absolute 1 1 ' '

CHART web_log_apache.requests_per_ipproto '' 'Requests Per IP Protocol' 'requests/s' 'ip protocols' 'web_log.requests_per_ipproto' stacked 60009 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'req_ipv4' 'ipv4' incremental 1 1 ' '
DIMENSION 'req_ipv6' 'ipv6' incremental 1 1 ' '
BEGIN web_log_apache_vhosts.clients_all 0
SET 'unique_tot_ipv4' = 0
SET 'unique_tot_ipv6' = 0
END


BEGIN web_log_apache.requests_per_ipproto 0
SET 'req_ipv4' = 3
SET 'req_ipv6' = 0
END
CHART web_log_apache_vhosts.response_statuses '' 'Response Statuses' 'requests/s' 'responses' 'web_log.response_statuses' stacked 60000 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'successful_requests' 'success' incremental 1 1 ' '
DIMENSION 'server_errors' 'error' incremental 1 1 ' '
DIMENSION 'redirects' 'redirect' incremental 1 1 ' '
DIMENSION 'bad_requests' 'bad' incremental 1 1 ' '
DIMENSION 'other_requests' 'other' incremental 1 1 ' '


BEGIN web_log_apache_vhosts.response_statuses 0
SET 'successful_requests' = 0
SET 'server_errors' = 0
SET 'redirects' = 0
SET 'bad_requests' = 0
SET 'other_requests' = 0
END
CHART web_log_apache.clients_all '' 'All Time Unique Client IPs' 'unique ips' 'clients' 'web_log.clients_all' stacked 60011 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'unique_tot_ipv4' 'ipv4' absolute 1 1 ' '
DIMENSION 'unique_tot_ipv6' 'ipv6' absolute 1 1 ' '

CHART web_log_apache_vhosts.response_codes '' 'Response Codes' 'requests/s' 'responses' 'web_log.response_codes' stacked 60001 1 '' 'python.d.plugin' 'web_log'
DIMENSION '2xx' '2xx' incremental 1 1 ' '
DIMENSION '5xx' '5xx' incremental 1 1 ' '
DIMENSION '3xx' '3xx' incremental 1 1 ' '
DIMENSION '4xx' '4xx' incremental 1 1 ' '
DIMENSION '1xx' '1xx' incremental 1 1 ' '
DIMENSION '0xx' 'other' incremental 1 1 ' '
DIMENSION 'unmatched' 'unmatched' incremental 1 1 ' '


BEGIN web_log_apache.clients_all 0
SET 'unique_tot_ipv4' = 2
SET 'unique_tot_ipv6' = 0
END

BEGIN web_log_apache_vhosts.response_codes 0
SET '2xx' = 0
SET '5xx' = 0
SET '3xx' = 0
SET '4xx' = 0
SET '1xx' = 0
SET '0xx' = 0
SET 'unmatched' = 0
END
CHART web_log_apache.response_statuses '' 'Response Statuses' 'requests/s' 'responses' 'web_log.response_statuses' stacked 60000 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'successful_requests' 'success' incremental 1 1 ' '
DIMENSION 'server_errors' 'error' incremental 1 1 ' '
DIMENSION 'redirects' 'redirect' incremental 1 1 ' '
DIMENSION 'bad_requests' 'bad' incremental 1 1 ' '
DIMENSION 'other_requests' 'other' incremental 1 1 ' '


CHART web_log_apache_vhosts.clients '' 'Current Poll Unique Client IPs' 'unique ips' 'clients' 'web_log.clients' stacked 60008 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'unique_cur_ipv4' 'ipv4' incremental 1 1 ' '
DIMENSION 'unique_cur_ipv6' 'ipv6' incremental 1 1 ' '

BEGIN web_log_apache_vhosts.clients 0
SET 'unique_cur_ipv4' = 0
SET 'unique_cur_ipv6' = 0
END

CHART web_log_apache_vhosts.bandwidth '' 'Bandwidth' 'kilobits/s' 'bandwidth' 'web_log.bandwidth' area 60002 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'resp_length' 'received' incremental 8 1000 ' '
DIMENSION 'bytes_sent' 'sent' incremental -8 1000 ' '

BEGIN web_log_apache_vhosts.bandwidth 0
SET 'resp_length' = 0
SET 'bytes_sent' = 0
END

CHART web_log_apache_vhosts.http_method '' 'Requests Per HTTP Method' 'requests/s' 'http methods' 'web_log.http_method' stacked 60003 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'GET' 'GET' incremental 1 1 ' '

BEGIN web_log_apache.response_statuses 0
SET 'successful_requests' = 3
SET 'server_errors' = 0
SET 'redirects' = 0
SET 'bad_requests' = 0
SET 'other_requests' = 0
END

CHART web_log_apache.response_codes '' 'Response Codes' 'requests/s' 'responses' 'web_log.response_codes' stacked 60001 1 '' 'python.d.plugin' 'web_log'
DIMENSION '2xx' '2xx' incremental 1 1 ' '
DIMENSION '5xx' '5xx' incremental 1 1 ' '
DIMENSION '3xx' '3xx' incremental 1 1 ' '
DIMENSION '4xx' '4xx' incremental 1 1 ' '
DIMENSION '1xx' '1xx' incremental 1 1 ' '
DIMENSION '0xx' 'other' incremental 1 1 ' '
DIMENSION 'unmatched' 'unmatched' incremental 1 1 ' '

BEGIN web_log_apache.response_codes 0
SET '2xx' = 3
SET '5xx' = 0
SET '3xx' = 0
SET '4xx' = 0
SET '1xx' = 0
SET '0xx' = 0
SET 'unmatched' = 0
END

CHART web_log_apache.http_version '' 'Requests Per HTTP Version' 'requests/s' 'http versions' 'web_log.http_version' stacked 60008 1 '' 'python.d.plugin' 'web_log'
DIMENSION '1_1' '1.1' incremental 1 1 ' '

BEGIN web_log_apache.http_version 0
SET '1_1' = 3
END
BEGIN web_log_apache_vhosts.http_method 0
SET 'GET' = 0
END

BEGIN netdata.runtime_web_log_apache_vhosts 0
SET run_time = 6
END


CHART web_log_apache.clients '' 'Current Poll Unique Client IPs' 'unique ips' 'clients' 'web_log.clients' stacked 60010 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'unique_cur_ipv4' 'ipv4' incremental 1 1 ' '
DIMENSION 'unique_cur_ipv6' 'ipv6' incremental 1 1 ' '

2020-04-14 08:40:41: python.d DEBUG: web_log[apache_vhosts_log] : update => [OK] (elapsed time: 6, failed retries in a row: 0)
BEGIN web_log_apache.clients 0
SET 'unique_cur_ipv4' = 2
SET 'unique_cur_ipv6' = 0
END

CHART web_log_apache.detailed_response_codes '' 'Detailed Response Codes ' 'requests/s' 'responses' 'web_log.detailed_response_codes' stacked 60012 1 '' 'python.d.plugin' 'web_log'
DIMENSION '200' '200' incremental 1 1 ' '

BEGIN web_log_apache.detailed_response_codes 0
SET '200' = 3
END

CHART web_log_apache.bandwidth '' 'Bandwidth' 'kilobits/s' 'bandwidth' 'web_log.bandwidth' area 60002 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'resp_length' 'received' incremental 8 1000 ' '
DIMENSION 'bytes_sent' 'sent' incremental -8 1000 ' '

BEGIN web_log_apache.bandwidth 0
SET 'resp_length' = 6363
SET 'bytes_sent' = 4256
END

CHART web_log_apache.http_method '' 'Requests Per HTTP Method' 'requests/s' 'http methods' 'web_log.http_method' stacked 60005 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'GET' 'GET' incremental 1 1 ' '
DIMENSION 'HEAD' 'HEAD' incremental 1 1 ' '

BEGIN web_log_apache.http_method 0
SET 'GET' = 2
SET 'HEAD' = 1
END

CHART web_log_apache.response_time '' 'Processing Time' 'milliseconds' 'timings' 'web_log.response_time' area 60003 1 '' 'python.d.plugin' 'web_log'
DIMENSION 'resp_time_min' 'min' incremental 1 1000 ' '
DIMENSION 'resp_time_max' 'max' incremental 1 1000 ' '
DIMENSION 'resp_time_avg' 'avg' incremental 1 1000 ' '

BEGIN web_log_apache.response_time 0
SET 'resp_time_min' = 14886
SET 'resp_time_max' = 211004
SET 'resp_time_avg' = 145164
END

BEGIN netdata.runtime_web_log_apache 0
SET run_time = 8
END

2020-04-14 08:40:41: python.d DEBUG: web_log[apache_log] : update => [OK] (elapsed time: 8, failed retries in a row: 0)
BEGIN web_log_apache_vhosts.requests_per_ipproto 1000585
SET 'req_ipv4' = 0
SET 'req_ipv6' = 0
END

BEGIN web_log_apache_vhosts.clients_all 1000585
SET 'unique_tot_ipv4' = 0
SET 'unique_tot_ipv6' = 0
END

BEGIN web_log_apache_vhosts.response_statuses 1000585
SET 'successful_requests' = 0
SET 'server_errors' = 0
SET 'redirects' = 0
SET 'bad_requests' = 0
SET 'other_requests' = 0
END
```

**Comment by sna-king** [comment]
that is most silly thing that i have ever seen in a logical machine
the same config in other server is run now .

**Comment by ilyam8** [comment]
@sna-king i see i works. Have you debug it as `netdata` user or as `root`? Thi is likely the problem.

There is `error.log`, check it. (`... | grep web_log`)

**Comment by sna-king** [comment]
> 
> 
> @sna-king i see i works. Have you debug it as `netdata` user or as `root`? Thi is likely the problem.
> 
> There is `error.log`, check it. (`... | grep web_log`)

its running as netdata i think because its running on docker.

**Comment by ilyam8** [comment]
it is, but when you run the plugin in the debug mode it is likely you do it not as user `netdata`.

should i run grep web_log error.log in a especial path?

```cmd
1 ilyam:sd $ docker logs friendly_mccarthy  2>&1 | grep web_log
2020-04-14 13:15:55: go.d INFO: main[main] module 'web_log' disabled by default
2020-04-14 13:15:56: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs
2020-04-14 13:15:56: python.d ERROR: web_log[nginx_log] : /var/log/nginx/access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[nginx_log] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[nginx_log2] : /var/log/nginx/localhost.access_log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[nginx_log2] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[apache_log] : /var/log/apache2/access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[apache_log] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[apache_log2] : /var/log/apache2/access_log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[apache_log2] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[apache_log3] : /var/log/httpd/access_log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[apache_log3] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[apache_vhosts_log] : /var/log/apache2/other_vhosts_access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[apache_vhosts_log] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[gunicorn_log] : /var/log/gunicorn/access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[gunicorn_log] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[gunicorn_log2] : /var/log/gunicorn/gunicorn-access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[gunicorn_log2] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[apache_cache] : /var/log/apache/cache.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[apache_cache] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[apache2_cache] : /var/log/apache2/cache.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[apache2_cache] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[httpd_cache] : /var/log/httpd/cache.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[httpd_cache] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[squid_log1] : /var/log/squid3/access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[squid_log1] : check failed
2020-04-14 13:15:56: python.d ERROR: web_log[squid_log2] : /var/log/squid/access.log not readable or not exist
2020-04-14 13:15:56: python.d INFO: plugin[main] : web_log[squid_log2] : check failed
```

**Comment by sna-king** [comment]
> ```batchfile
> friendly_mccarthy  2>&1 | grep web_log
> ```

i think yes now im getting the error
so do you suggest me to run the netdata image and set the root access for it(i think the is a environment variable for this )
```
2020-04-14 10:23:22: python.d INFO: plugin[main] : web_log[apache_cache] : check failed
2020-04-14 10:23:22: python.d ERROR: web_log[apache2_cache] : /var/log/apache2/cache.log not readable or not exist
2020-04-14 10:23:22: python.d INFO: plugin[main] : web_log[apache2_cache] : check failed
2020-04-14 10:23:22: python.d ERROR: web_log[httpd_cache] : /var/log/httpd/cache.log not readable or not exist
2020-04-14 10:23:22: python.d INFO: plugin[main] : web_log[httpd_cache] : check failed
2020-04-14 10:23:22: python.d ERROR: web_log[squid_log1] : /var/log/squid3/access.log not readable or not exist
2020-04-14 10:23:22: python.d INFO: plugin[main] : web_log[squid_log1] : check failed
2020-04-14 10:23:22: python.d ERROR: web_log[squid_log2] : /var/log/squid/access.log not readable or not exist
2020-04-14 10:23:22: python.d INFO: plugin[main] : web_log[squid_log2] : check failed
2020-04-14 12:56:28: go.d INFO: main[main] module 'web_log' disabled by default
2020-04-14 12:56:29: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs
2020-04-14 12:56:29: python.d ERROR: web_log[nginx_log] : /var/log/nginx/access.log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[nginx_log] : check failed
2020-04-14 12:56:29: python.d ERROR: web_log[nginx_log2] : /var/log/nginx/localhost.access_log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[nginx_log2] : check failed
2020-04-14 12:56:29: python.d ERROR: web_log[apache_log] : /var/log/apache2/ajc-access.log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[apache_log] : check failed
2020-04-14 12:56:29: python.d ERROR: web_log[apache_log2] : /var/log/apache2/access_log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[apache_log2] : check failed
2020-04-14 12:56:29: python.d ERROR: web_log[apache_log3] : /var/log/httpd/access_log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[apache_log3] : check failed
2020-04-14 12:56:29: python.d ERROR: web_log[apache_vhosts_log] : /var/log/apache2/other_vhosts_access.log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[apache_vhosts_log] : check failed
2020-04-14 12:56:29: python.d ERROR: web_log[gunicorn_log] : /var/log/gunicorn/access.log not readable or not exist
2020-04-14 12:56:29: python.d INFO: plugin[main] : web_log[gunicorn_log] : check failed
```

**Comment by ilyam8** [comment]
> 2020-04-14 12:56:29: python.d ERROR: web_log[apache_log2] : /var/log/apache2/access_log not readable or not exist


Show logs dirs permissions. From the host prospective.

**Comment by sna-king** [comment]
> 
> 
> > 2020-04-14 12:56:29: python.d ERROR: web_log[apache_log2] : /var/log/apache2/access_log not readable or not exist
> 
> Show logs dirs permissions. From the host prospective.

one think is that the our sys admins do sth with the test server that gives docker root permission
for example we don't need type sudo before any docker command so do you think that is make this different.
and more important what is the solution ?

**Comment by ilyam8** [comment]
> for example we don't need type sudo before any docker command so do you think that makes this different?

Your user in the `docker` group.

and more important what is the solution ?

Make log files readable by `netdata` user/group (uid/gid matters). I suggest to ask your sys admins. It seems it is their area.

**Comment by ilyam8** [comment]
There is no problems with netdata/web_log collector, so i am closing the issue.
