### ISSUE TITLE
SNMP not recognizing OID

### ISSUE THREAD

**Issue by djrm05** [netdata/netdata#8711]
Hi,

I'm trying to monitor a desktop from netdata using snmp, however I'm stuck in the snmp.conf file as it doesn't recognize the OID.
This is the conf file:
```
{
    "enable_autodetect": false,
    "update_every": 5,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "192.168.1.2",
            "community": "public",
            "update_every": 5,
            "max_request_size": 50,
            "options": {
                "timeout": 10000
            },
            "charts": {
                "systemCPU-Usage": {
                    "title": "CPU use",
                    "units": "percentage",
                    "type": "line",
                    "priority": 1,
                    "family": "systemInfo",
                    "dimensions": {
                        "use": {
                            "oid": "1.3.6.1.4.1.24681.1.2.1",
                            "algorithm": "absolute"
                        }

                    }
                }
            }
        }
    ]
}  
```
When I try to test it I got this error:

```
sudo /usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
2020-04-14 14:58:51: node.d.plugin: ERROR: snmp: 192.168.1.2: Received error = { RequestFailedError: NoSuchName: 1.3.6.1.4.1.24681.1.2.1
    at Req.Session.onSimpleGetResponse [as onResponse] (/usr/libexec/netdata/node.d/node_modules/net-snmp.js:1844:25)
    at Session.onMsg (/usr/libexec/netdata/node.d/node_modules/net-snmp.js:1806:21)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
  name: 'RequestFailedError',
  message: 'NoSuchName: 1.3.6.1.4.1.24681.1.2.1',
  status: 2 } varbinds = undefined
DISABLE
```
But trying to query directly i got the expected value:
```
snmpwalk 192.168.1.2 -c public -v2c 1.3.6.1.4.1.24681.1.2.1
iso.3.6.1.4.1.24681.1.2.1.0 = STRING: "2.30 %"
```

Could someone help me to get this sorted please?

Thanks!

**Comment by ilyam8** [comment]
> 1.3.6.1.4.1.24681.1.2.1

try 1.3.6.1.4.1.24681.1.2.1.0


But anyway snmp plugin cant handle strings

> iso.3.6.1.4.1.24681.1.2.1.0 = STRING: "2.30 %"

**Comment by ilyam8** [comment]
> snmpwalk 192.168.1.2 -c public -v2c 1.3.6.1.4.1.24681.1.2.1

if you would go `snmpget` you would get the error
