### ISSUE TITLE
Older openssl libraries cause ACLK reconnection failure

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8812]
## Summary

Old openssl libraries do not handle a renegotiation request properly and as a result the connection is not established. 

Verified in openssl versions 1.0.2q and 1.0.2g

The following is an example

```
2020-04-23 17:23:00: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-04-23 17:23:00: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: staging.netdata.cloud 443 /api/v1/auth/node/548dd3d4-8563-11ea-b9ce-525400bae92f/challenge
2020-04-23 17:23:00: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-04-23 17:23:00: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-04-23 17:23:01: netdata INFO  : ACLK_Main : aclk_send_https_request POST
2020-04-23 17:23:01: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-04-23 17:23:01: netdata ERROR : ACLK_Main : Already Connected. Only one connection supported at a time.
2020-04-23 17:23:01: netdata ERROR : ACLK_Main : Closing lws connectino due to libmosquitto error.
2020-04-23 17:23:01: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_CLIENT_CLOSED
2020-04-23 17:23:01: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_WSI_DESTROY
2020-04-23 17:23:01: netdata INFO  : ACLK_Main : Using challenge-response: 548dd3d4-8563-11ea-b9ce-525400bae92f / 69B6q9LfONIQBQ4A9OUqykN4org=
2020-04-23 17:23:01: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 512.391 seconds
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: staging.netdata.cloud 443 /api/v1/auth/node/548dd3d4-8563-11ea-b9ce-525400bae92f/challenge
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : aclk_send_https_request POST
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Using challenge-response: 548dd3d4-8563-11ea-b9ce-525400bae92f / SCZ8f2nDIyyA6KJRM0WbvhZBaXk=
2020-04-23 17:31:34: netdata ERROR : ACLK_Main : Libwebsockets: SSL error: certificate signature failure (preverify_ok=0;err=7;depth=1)

2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_CLIENT_CONNECTION_ERROR
2020-04-23 17:31:34: netdata ERROR : ACLK_Main : Could not connect MQTT over WSS server "staging.netdata.cloud:443". LwsReason:"client connect failed"
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_WSI_DESTROY
2020-04-23 17:31:34: netdata INFO  : ACLK_Main : /home/stelios/netdata-inst//netdata/usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'ACLK_CONN_FAIL' 'FAIL' '30,1,58,58,19,29'
2020-04-23 17:31:35: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 
```

**Comment by Ferroin** [comment]
Ubuntu 16.04 is on 1.0.2g so it is almost certainly affected by this.

CentOS 7 claims to be using 1.0.2k and might be affected by this.

Debian 8 is on 1.0.1l and thus may be affected by this.

All other distributions on our official support list appear to be using OpenSSL 1.1.0 or newer.

**Comment by amoss** [comment]
I've found a way to test the disconnection precisely. Using the nodefarm sets up a collection of VirtualBox VMs running on the host. You can then find the ACLK sockets on the host using
```
ss -p dst 104.31/16 | sort -k5
tcp     ESTAB   0        0            192.168.1.2:33510     104.31.80.87:https   users:(("firefox-esr",pid=3672,fd=82))                                         
tcp     ESTAB   0        0            192.168.1.2:36928     104.31.81.87:https                                                                                  
tcp     ESTAB   0        0            192.168.1.2:37058     104.31.81.87:https                                                                                  
tcp     ESTAB   0        0            192.168.1.2:37100     104.31.81.87:https                                                                                  
tcp     ESTAB   0        0            192.168.1.2:37136     104.31.81.87:https                                                                                  
tcp     ESTAB   0        0            192.168.1.2:37174     104.31.81.87:https                                                                                  
tcp     ESTAB   0        0            192.168.1.2:37256     104.31.81.87:https                                                                                  
tcp     ESTAB   0        0            192.168.1.2:54918     104.31.80.87:https   users:(("netdata",pid=24767,fd=34))
```
To simulate a disconnection on the network side you can then kill a socket on the host so that the RST is sent into the VM using
```
sudo ss -K sport 40822
```
This lets us watch the reconnection sequence, although I have not yet worked out how to identify which ACLK belongs to which VM. There is some weird stuff going on when we destroy the context that I'm just starting to look into:
```
2020-04-28 09:34:55: netdata INFO  : ACLK_Main : (1567@aclk/agent:aclk_disconnect): Disconnect detected (0 queued queries)
2020-04-28 09:35:26: netdata INFO  : ACLK_Main : (0158@libnetdata:thread_start   ): thread created with task id 6550
2020-04-28 09:35:26: netdata INFO  : ACLK_Main : (0131@libnetdata:thread_set_name): set name of thread 6550 to ACLK_Main
2020-04-28 09:35:26: netdata INFO  : ACLK_Main : (1349@aclk/agent:aclk_main      ): Waiting for netdata to be ready
2020-04-28 09:35:26: netdata INFO  : ACLK_Main : (1354@aclk/agent:aclk_main      ): Waiting for Cloud to be enabled
2020-04-28 09:35:26: netdata INFO  : ACLK_Main : (1369@aclk/agent:aclk_main      ): Waiting for netdata to be claimed
20
```
This happens every time the connection is killed so something is very wrong.

**Comment by amoss** [comment]
Ok, so I couldn't see it crash inside the VM because it was restarting automatically and I had a filter on the logs. Replicated it inside gdb:
```
(gdb) bt
#0  0x000055555565ad37 in __lws_close_free_wsi ()
#1  0x000055555565e510 in lws_service_fd_tsi ()
#2  0x000055555567a7a9 in _lws_plat_service_tsi ()
#3  0x000055555565e78d in lws_service ()
#4  0x000055555562a982 in aclk_lws_wss_service_loop () at aclk/aclk_lws_wss_client.c:554
#5  0x00005555555df74d in _link_event_loop () at aclk/mqtt.c:246
#6  aclk_main (ptr=0x5555558f6448 <static_threads+392>) at aclk/agent_cloud_link.c:1436
#7  0x00005555555d57d0 in thread_start (ptr=0x555555b688a0) at libnetdata/threads/threads.c:170
#8  0x00007ffff63034a4 in start_thread (arg=0x7ffff1d0f700) at pthread_create.c:456
#9  0x00007ffff6045d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by amoss** [comment]
We can't destroy the context easily as the event happens in a callback inside the context. I will propagate the notification up into the main loop and tear it down from the outside.
