### ISSUE TITLE
Core dump during shutdown

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#9507]
##### Bug report summary
- ACLK enabled
- Start agent and shutdown (control - C) 

Occasionally there is a core dump : 
```
#0  0x000055a15dbe6e1a in aclk_query_threads_cleanup (query_threads=0x7f9e3f1d5d20) at aclk/aclk_query.c:468
#1  0x000055a15dbe3fa2 in aclk_main (ptr=0x55a15dd1d3c8 <static_threads+392>) at aclk/agent_cloud_link.c:1011
#2  0x000055a15db4c28d in thread_start (ptr=0x55a16184efb0) at libnetdata/threads/threads.c:184
#3  0x00007f9e4557c609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007f9e454a3103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
#0  0x000055a15dbe6e1a in aclk_query_threads_cleanup (query_threads=0x7f9e3f1d5d20) at aclk/aclk_query.c:468
468	            netdata_thread_join(*(query_threads->thread_list[i]->thread), NULL);
```

```
(gdb) p query_threads->thread_list 
$6 = (struct aclk_query_thread **) 0x0
```

Also 
```
2020-07-09 09:51:36: netdata INFO  : ACLK_Stats : thread with task id 473240 finished
2020-07-09 09:51:36: netdata INFO  : MAIN : Waiting 1 threads to finish...
2020-07-09 09:51:37: netdata INFO  : MAIN : Waiting 1 threads to finish...
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : Sending MQTT len=228 mid=513 wq=0 (0-bytes) readq=0:   {"type": "disconnect",  "msg-id": "31d6aca9-7461-420b-9d80-
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : MQTT disconnected from broker
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : Connection to cloud terminated due to agent shutdown
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : Disconnect detected (0 queued queries)
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_CLIENT_CLOSED
2020-07-09 09:51:37: netdata INFO  : ACLK_Query_0 : thread with task id 473254 finished
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_WSI_DESTROY
2020-07-09 09:51:37: netdata INFO  : ACLK_Main : thread with task id 473031 finished
2020-07-09 09:51:37: netdata INFO  : MAIN : All threads finished.
2020-07-09 09:51:37: netdata INFO  : MAIN : EXIT: freeing database memory...
2020-07-09 09:51:37: netdata INFO  : MAIN : Freeing all memory for host 'futura'...
2020-07-09 09:51:37: netdata ERROR : MAIN : Request to remove RRDVAR '00û`ÁU' from index failed. Not Found.
2020-07-09 09:51:37: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '00û`ÁU' from host 'futura', but it is not found.
2020-07-09 09:51:37: netdata ERROR : MAIN : Request to remove RRDVAR '' from index failed. Not Found.
2020-07-09 09:51:37: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '' from host 'futura', but it is not found.
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.
```

Which is traced to 
```
#1  0x000055c15e85fdb8 in freez (ptr=0x5a9fc5ece89c0) at libnetdata/libnetdata.c:173
#2  0x000055c15e8cf7a4 in rrdvar_free (host=0x55c15f16eeb0, tree=0x55c161d1fd90, rv=0x55c160fb0dc0) at database/rrdvar.c:65
#3  0x000055c15e8ce8a6 in rrdsetvar_free_variables (rs=0x55c160fb0c50) at database/rrdsetvar.c:21
#4  0x000055c15e8ceff2 in rrdsetvar_free (rs=0x55c160fb0c50) at database/rrdsetvar.c:125
#5  0x000055c15e8c7f07 in rrdset_free (st=0x55c160faec10) at database/rrdset.c:339
#6  0x000055c15e8c3382 in rrdhost_free (host=0x55c15f16eeb0) at database/rrdhost.c:712
#7  0x000055c15e8c3868 in rrdhost_free_all () at database/rrdhost.c:803
#8  0x000055c15e840bbd in netdata_cleanup_and_exit (ret=0) at daemon/main.c:44
#9  0x000055c15e846607 in signals_handle () at daemon/signals.c:261
#10 0x000055c15e8457df in main (argc=2, argv=0x7ffd399ce918) at daemon/main.c:1491
```

and digging into that

```
#5  0x000055c15e8c7f07 in rrdset_free (st=0x55c160faec10) at database/rrdset.c:339
339	    while(st->variables)  rrdsetvar_free(st->variables);
(gdb) p st->name
$1 = 0x55c160fb03e0 "netdata.aclk_cloud_req"
```

##### OS / Environment

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

##### Netdata version
netdata v1.22.1-306-g8186870c

##### Steps To Reproduce
- Start agent
- First core:  Press control - C early enough in the ACLK establishing sequence
- Second core: unfortunately random

**Comment by stelfrag** [comment]
I haven't been able to reproduce after #9509 was merged
