### ISSUE TITLE
netdata crash during queries

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#9713]
##### Bug report summary

Netdata crashes with division by zero when dbengine metrics have out of order timestamps:
```
2020-08-11 10:51:57: netdata INFO  : HEALTH : Ignoring metric with out of order timestamp.
```

The division by zero is as follows:
```
Program received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffe4091700 (LWP 90248)]
0x000000000060bf37 in rrd2rrdr_fixedstep (st=0x60660008f100, points_requested=405, after_requested=1597135155,
    before_requested=1597135635, group_method=RRDR_GROUPING_AVERAGE, resampling_time_requested=0,
    options=(RRDR_OPTION_NONZERO | RRDR_OPTION_REVERSED | RRDR_OPTION_MILLISECONDS | RRDR_OPTION_JSON_WRAP), dimensions=0x0,
    update_every=0, first_entry_t=1597036130, last_entry_t=1597135635, absolute_period_requested=1)
    at web/api/queries/query.c:818
818         long available_points = duration / update_every;
(gdb) bt
#0  0x000000000060bf37 in rrd2rrdr_fixedstep (st=0x60660008f100, points_requested=405, after_requested=1597135155,
    before_requested=1597135635, group_method=RRDR_GROUPING_AVERAGE, resampling_time_requested=0,
    options=(RRDR_OPTION_NONZERO | RRDR_OPTION_REVERSED | RRDR_OPTION_MILLISECONDS | RRDR_OPTION_JSON_WRAP), dimensions=0x0,
    update_every=0, first_entry_t=1597036130, last_entry_t=1597135635, absolute_period_requested=1)
    at web/api/queries/query.c:818
#1  0x0000000000610be0 in rrd2rrdr (st=0x60660008f100, points_requested=405, after_requested=1597135155,
    before_requested=1597135635, group_method=RRDR_GROUPING_AVERAGE, resampling_time_requested=0,
    options=(RRDR_OPTION_NONZERO | RRDR_OPTION_REVERSED | RRDR_OPTION_MILLISECONDS | RRDR_OPTION_JSON_WRAP), dimensions=0x0)
    at web/api/queries/query.c:1580
#2  0x00000000006134f5 in rrdset2anything_api_v1 (st=0x60660008f100, wb=0x600801093050, dimensions=0x0, format=0, points=405,
    after=-480, before=0, group_method=1, group_time=0, options=547, latest_timestamp=0x7fffe408ef50)
    at web/api/formatters/rrd2json.c:120
#3  0x0000000000623cd9 in web_client_api_request_v1_data (host=0x60460001ea00, w=0x6098000f0400, url=0x0)
    at web/api/web_api_v1.c:542
#4  0x00000000005f388c in web_client_api_request_v1 (host=0x60460001ea00, w=0x6098000f0400, url=0x6098000f0c94 "data")
    at web/api/web_api_v1.c:970
#5  0x000000000052e2e7 in web_client_api_request (host=0x60460001ea00, w=0x6098000f0400, url=0x6098000f0c94 "data")
    at web/server/web_client.c:604
#6  0x000000000052e1b1 in check_host_and_call (host=0x60460001ea00, w=0x6098000f0400, url=0x6098000f0c91 "v1",
    func=0x52e1cc <web_client_api_request>) at web/server/web_client.c:580
#7  0x0000000000533a8e in web_client_process_url (host=0x60460001ea00, w=0x6098000f0400, url=0x6098000f0c91 "v1")
    at web/server/web_client.c:1402
#8  0x00000000005351a3 in web_client_process_request (w=0x6098000f0400) at web/server/web_client.c:1548
#9  0x0000000000501f7f in web_server_rcv_callback (pi=0x604a0006e9a0, events=0x600e000cafc4)
    at web/server/static/static-threaded.c:257
#10 0x00000000006530c5 in poll_events_process (p=0x7fffe4090920, pi=0x604a0006e9a0, pf=0x600e000cafc0, revents=1, now=6526682)
    at libnetdata/socket/socket.c:1413
#11 0x0000000000655470 in poll_events (sockets=0xa599c0 <api_sockets>, add_callback=0x500f58 <web_server_add_callback>,
    del_callback=0x501a59 <web_server_del_callback>, rcv_callback=0x501dfa <web_server_rcv_callback>,
    snd_callback=0x50261c <web_server_snd_callback>, tmr_callback=0x50299c <web_server_tmr_callback>,
    access_list=0x600800c8b750, allow_dns=1, data=0x0, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=60,
    timer_milliseconds=1000, timer_data=0x6034000af440, max_tcp_sockets=2730) at libnetdata/socket/socket.c:1694
#12 0x00000000005032b2 in socket_listen_main_static_threaded_worker (ptr=0x6034000af440)
    at web/server/static/static-threaded.c:392
#13 0x0000000000629bc2 in thread_start (ptr=0x600800c93dd0) at libnetdata/threads/threads.c:184
#14 0x00007ffff4e64868 in __asan::AsanThread::ThreadStart (this=0x7fffe4093000)
    at ../../../../libsanitizer/asan/asan_thread.cc:99
#15 0x00007ffff35a5ea5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007ffff32ce8dd in clone () from /lib64/libc.so.6
```

##### OS / Environment

```
Linux CentOS-7-mfundul 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Netdata version

 
netdata v1.24.0-9-g6caa2b6
##### Component Name

database
##### Steps To Reproduce

1. Set-up streaming with tens of children.
2. Restart the agent after some time.

##### Expected behavior

The agent shouldn't crash.

**Comment by cakrit** [comment]
This was seen in #7011 as well, we should probably deal with it when we're done with the high prio ones.

**Comment by stelfrag** [comment]
Cannot reproduce
