### ISSUE TITLE
Enable nvidia plugin 

### ISSUE THREAD

**Issue by JaseNZC** [netdata/netdata#9942]
Running latest stable version on a up to date kali linux.

This is probably as plain as the nose on my face but I want to enable the nvidia_smi plugin. It mentions this is off by default and need to be turned on.
Where is this setting, I had a look in both the main config file as well as the nvidia_smi.config file. 
Was not able to see anywhere that lists to enable this.

Any body able to put me in the right direction

**Comment by ilyam8** [comment]
Hi

It is `python.d.conf`

**Comment by JaseNZC** [comment]
yup found it thanks, was not where I thought it would be.

`nano /usr/lib/netdata/conf.d/python.d.conf`

**Comment by ilyam8** [comment]
this one is stock config and it is overwritten on every update

cd to `/etc/netdata` and

> ./edit-config python.d.conf

**Comment by JaseNZC** [comment]
yup sorted and turned on but does not seem to work for me. 

Back to the drawing board I guess.

Running latest version of ubuntu and latest netdata

**Comment by ilyam8** [comment]
`python.d.plugin` has debug mode

as `netdata` user

> ./python.d.plugin debug nvidia_smi

**Comment by JaseNZC** [comment]
for me to run it just leaves a whole heap of a mess trying to debug it.

`etdata@pen:/$ /usr/libexec/netdata/plugins.d/python.d.plugin nvidia_smi debug trace
2020-09-17 19:05:11: python.d INFO: plugin[main] : using python v2
2020-09-17 19:05:11: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-09-17 19:05:11: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2020-09-17 19:05:11: python.d ERROR: plugin[main] : error on loading '/etc/netdata/python.d.conf' : ParserError()
2020-09-17 19:05:11: python.d ERROR: plugin[main] : Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 516, in load_config
    config = load_config(abs_path)
  File "/usr/libexec/netdata/python.d/python_modules/bases/loaders.py", line 46, in load_config
    return load_yaml(stream)
  File "/usr/libexec/netdata/python.d/python_modules/bases/loaders.py", line 39, in load_yaml
    return loader.get_single_data()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/constructor.py", line 38, in get_single_data
    node = self.get_single_node()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 37, in get_single_node
    document = self.compose_document()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 56, in compose_document
    node = self.compose_node(None, None)
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 85, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/composer.py", line 128, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/parser.py", line 99, in check_event
    self.current_event = self.state()
  File "/usr/libexec/netdata/python.d/python_modules/pyyaml2/parser.py", line 440, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "/etc/netdata/python.d.conf", line 10, column 1
expected <block end>, but found '<block mapping start>'
  in "/etc/netdata/python.d.conf", line 74, column 2`

**Comment by ilyam8** [comment]
> 2020-09-17 19:05:11: python.d ERROR: plugin[main] : error on loading '/etc/netdata/python.d.conf' : ParserError()

You have some syntax errors in your `/etc/netdata/python.d.conf`

Check it using http://www.yamllint.com/ (copy paste the config in there and click `Go`)

**Comment by ilyam8** [comment]
`python.d.conf` format is 

```yaml
key1: value
key2: value
...
```

**Comment by JaseNZC** [comment]
The plot thickens as its a valid yaml file still putting out the same error.

**Comment by JaseNZC** [comment]
[python.dconf.txt](https://github.com/netdata/netdata/files/5237105/python.dconf.txt)

**Comment by ilyam8** [comment]
well, it is not valid

>  ParserError: while parsing a block mapping in "/etc/netdata/python.d.conf", line 10, column 1 expected <block end>, but found '<block mapping start>' in "/etc/netdata/python.d.conf", line 74, column 2

share `/etc/netdata/python.d.conf`

**Comment by ilyam8** [comment]
There is extra space
```yaml
# nginx: yes
# nginx_plus: yes
 nvidia_smi: yes
```

=>

```yaml
# nginx: yes
# nginx_plus: yes
nvidia_smi: yes
```

**Comment by ilyam8** [comment]
<img width="913" alt="Screenshot 2020-09-17 at 10 38 46" src="https://user-images.githubusercontent.com/22274335/93435343-fa55c600-f8d1-11ea-9d39-52623bb0c854.png">

---

Removing the space solved the problem!

**Comment by JaseNZC** [comment]
Thanks for your help learnt a lot and sorted it out
enabled: yes was also one space out.

All good to go gpu's showing up now. 

Cheers @ilyam8
