### ISSUE TITLE
PostgreSQL python.d plugin error

### ISSUE THREAD

**Issue by thedemonium** [netdata/netdata#9970]
Hello, I'm unable to get postgresql monitoring enabled. 

```
root@netdata:~# cat  /etc/netdata/python.d/postgres.conf
postgres:
    name: db
    database    : 'db'
    user        : 'netdatamonitor'
    password    : 'pass'
    host        : '192.168.65.13'
    port        : 6432
```

Seems I have everything set correctly, but still receiving this error:

```
netdata:~# /usr/libexec/netdata/plugins.d/python.d.plugin trace debug 1 postgres
2020-09-22 11:58:11: python.d INFO: plugin[main] : using python v2
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : [postgres] looking for 'postgres.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : [postgres] loading '/etc/netdata/python.d/postgres.conf'
2020-09-22 11:58:11: python.d DEBUG: plugin[main] : [postgres] '/etc/netdata/python.d/postgres.conf' is loaded
2020-09-22 11:58:11: python.d INFO: plugin[main] : [postgres] built 1 job(s) configs
2020-09-22 11:58:11: python.d ERROR: postgres[postgres] : ERROR:  Unsupported startup parameter: options

2020-09-22 11:58:11: python.d ERROR: postgres[postgres] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/postgres.chart.py", line 961, in connect
    self.conn = psycopg2.connect(**self.conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: ERROR:  Unsupported startup parameter: options


2020-09-22 11:58:11: python.d ERROR: postgres[postgres] : failed to connect to {'database': 'db', 'port': 6432, 'host': '192.168.65.13', 'user': 'netdatamonitor', 'connect_timeout': 2, 'password': '*****', 'options': '-c statement_timeout=5000'}
2020-09-22 11:58:11: python.d INFO: plugin[main] : postgres[postgres] : check failed
2020-09-22 11:58:11: python.d INFO: plugin[main] : no jobs to serve
2020-09-22 11:58:11: python.d INFO: plugin[main] : exiting from main...
root@netdata:~# 
```

Any hint in which way I should proceed? Thanks

**Comment by OdysLam** [comment]
@thedemonium I see that you found a solution and closed the issue. What was the problem? 

Also, welcome to our little community :)

**Comment by ilyam8** [comment]
The question not to me, but sharing my observations:

I see

```
2020-09-22 11:58:11: python.d ERROR: postgres[postgres] : ERROR:  Unsupported startup parameter: options
...
2020-09-22 11:58:11: python.d ERROR: postgres[postgres] : failed to connect to {'database': 'db', 'port': 6432, 'host': '192.168.65.13', 'user': 'netdatamonitor', 'connect_timeout': 2, 'password': '*****', 'options': '-c statement_timeout=5000'}
2020-09-22 11:58:11: python.d INFO: plugin[main] : postgres[postgres] : check failed
```

https://github.com/netdata/netdata/blob/83c0121c53c25c58e4308e9723f5395af29ef9c0/collectors/python.d.plugin/postgres/postgres.chart.py#L934-L935


Could be an old `psycopg2` lib 🤔 🤷‍♂️
